package emu.grasscutter.net.packet;

public final class PacketOpcodes {
    // Empty
    public static final int NONE = 0;

    public static final int Unk5000_DAGEGOHAODP = 6447; // 烦人的数据包

    /* my fix */
    public static final int AvatarAddNotify = 4216;
    public static final int AvatarPromoteReq = 21972;
    public static final int AvatarPromoteRsp = 1987;    // test
    public static final int EntityAiSyncNotify = 23720;
    public static final int DungeonSettleNotify = 8007;
    public static final int AntiAddictNotify = 20752;
    public static final int HitClientTrivialNotify = 25759;
    public static final int EvtAiSyncCombatThreatInfoNotify = 1442;
    public static final int AvatarFightPropUpdateNotify = 20328;
    public static final int AvatarFightPropNotify = 287;
    public static final int EnterTransPointRegionNotify = 9692;
    public static final int ExitTransPointRegionNotify = 27579;
    public static final int EvtEntityRenderersChangedNotify = 7358;
    public static final int AddNoGachaAvatarCardNotify = 28082; // 非抽卡途径获得角色
    public static final int StoreItemDelNotify = 9567; // 最后一个命座解锁时扣除命星
    public static final int ClientAbilitiesInitFinishCombineNotify = 6545;
    public static final int ClientScriptEventNotify = 29125;
    public static final int PersonalLineAllDataRsp = 28577;
    public static final int AchievementUpdateNotify = 26226; // 成就
    public static final int AskAddFriendRsp = 25067;
    public static final int MeetNpcReq = 5799;
    public static final int AvatarDelNotify = 24313; //24313 or 27625
    public static final int AvatarFetterLevelRewardReq = 7455; //oldVersion
    public static final int AvatarFetterLevelRewardRsp = 21750;
    public static final int WorldChestOpenNotify = 2812;
    public static final int WidgetCoolDownNotify = 20751;
    public static final int ForgeFormulaDataNotify = 9617;
    public static final int ForgeStartReq = 29987;
    public static final int ForgeStartRsp = 387574; //oldVersion 单个retcode 不用核对cmdid
    public static final int AvatarSatiationDataNotify = 4982;
    public static final int GetBlossomBriefInfoListRsp = 27512; // proto字段未更新
    public static final int BlossomBriefInfoNotify = 26657;
    public static final int WorldOwnerBlossomBriefInfoNotify = 8720; // 26657 or 8720 // proto字段未更新
    public static final int AvatarSkillChangeNotify = 4410;
    public static final int AvatarSkillDepotChangeNotify = 25309;
    public static final int AvatarSkillInfoNotify = 25299;
    public static final int AvatarSkillMaxChargeCountNotify = 28497;
    public static final int GetShopmallDataRsp = 23211; // 虚假的值 todo
    public static final int BuyGoodsReq = 4523; // ShopGoods 的 proto 可能有问题
    public static final int BuyGoodsRsp = 21; // ShopGoods 的 proto 可能有问题
    public static final int BuyResinReq = 213790; //oldVersion 等待抓取
    public static final int BuyResinRsp = 3981;
    public static final int CombineFormulaDataNotify = 9746;
    public static final int CardProductRewardNotify = 4506;
    public static final int CombineReq = 21559;
    public static final int CombineRsp = 29627; // proto 字段可能有部分解错了
    public static final int TakeCompoundOutputReq = 24016;
    public static final int TakeCompoundOutputRsp = 1235;
    public static final int PlayerCompoundMaterialReq = 530;
    public static final int PlayerCompoundMaterialRsp = 22858;
    public static final int CompoundDataNotify = 5964;
    public static final int CoopDataNotify = 25237;
    public static final int DelTeamEntityNotify = 29714; // 29714 or 26259
    public static final int UpdateAbilityCreatedMovingPlatformNotify = 6274;
    public static final int DropHintNotify = 3881;
    public static final int DungeonEntryToBeExploreNotify = 1436; // 1436 or 21790
    public static final int DungeonRestartRsp = 2128; // 2128 or 22307
    public static final int DungeonWayPointNotify = 3239;
    public static final int EnterTrialAvatarActivityDungeonRsp = 244; // 244 or 1551
    public static final int EvtAvatarEnterFocusNotify = 29042;
    public static final int EvtAvatarExitFocusNotify = 20290; // 20290 or 8696
    public static final int EvtAvatarSitDownNotify = 22638;
    public static final int EvtAvatarUpdateFocusNotify = 8696; // 20290 or 8696
    public static final int ForgeDataNotify = 20023;
    public static final int ForgeGetQueueDataRsp = 27281;
    public static final int ForgeQueueDataNotify = 28170;
    public static final int FurnitureMakeStartRsp = 29740; // 29740 or 24667
    public static final int GachaWishReq = 25407;
    public static final int GachaWishRsp = 23268;
    public static final int GetAuthkeyReq = 28308;
    public static final int GetAuthkeyRsp = 154;
    public static final int GetCompoundDataReq = 25870; // 在例如打开烹饪界面时出现
    public static final int GetCompoundDataRsp = 4557;
    public static final int GetDailyDungeonEntryInfoReq = 23858; // 23858 or 26515
    public static final int GetDungeonEntryExploreConditionReq = 21790; // 1436 or 21790
    public static final int GivingRecordNotify = 951;
    public static final int GmTalkRsp = 27437;
    public static final int GadgetAutoPickDropInfoNotify = 21438;
    public static final int ExecuteGadgetLuaReq = 5759; // 解的proto字段有可能是错的
    public static final int ExecuteGadgetLuaRsp = 198805; //oldVersion 单个retcode不用解
    public static final int LevelupCityReq = 8394;
    public static final int LevelupCityRsp = 3655;
    public static final int MassiveEntityElementOpBatchNotify = 29700;
    public static final int McoinExchangeHcoinReq = 5528;
    public static final int McoinExchangeHcoinRsp = 21052;
    public static final int MonsterAIConfigHashNotify = 22925;
    public static final int MonsterAlertChangeNotify = 6613;
    public static final int MonsterSummonTagNotify = 21455;
    public static final int MusicGameSettleReq = 7153;
    public static final int MusicGameSettleRsp = 25598; // 25598 or 6575
    public static final int MusicGameStartReq = 3045; // 3045 or 20846
    public static final int MusicGameStartRsp = 27757; // 27757 or 20172 or 28729
    public static final int PathfindingEnterSceneRsp = 496824; //oldVersion 单个retcode不用解
    public static final int PersonalSceneJumpRsp = 1612;
    public static final int PlayerApplyEnterHomeNotify = 8132; // 8132 or 38
    public static final int PlayerApplyEnterHomeResultNotify = 22086;
    public static final int PlayerApplyEnterHomeResultReq = 378; // 378 or 1860
    public static final int PlayerApplyEnterHomeResultRsp = 21189;
    public static final int CompoundUnlockNotify = 28422;
    public static final int CoopChapterUpdateNotify = 6478;
    public static final int ProudSkillChangeNotify = 29262;
    public static final int ProudSkillExtraLevelNotify = 28513;
    public static final int QuestDelNotify = 1774;
    public static final int QuestDestroyEntityReq = 25911;
    public static final int QuestDestroyEntityRsp = 3908;
    public static final int QuestGlobalVarNotify = 26464;
    public static final int QuestUpdateQuestVarReq = 24014;
    public static final int QuestUpdateQuestVarRsp = 3297;
    public static final int ReceivedTrialAvatarActivityRewardReq = 5449; // 5449 or 5667
    public static final int ReceivedTrialAvatarActivityRewardRsp = 1551; // 244 or 1551
    public static final int ReliquaryDecomposeReq = 4929;
    public static final int ReliquaryDecomposeRsp = 21659;
    public static final int ReliquaryUpgradeReq = 24032;
    public static final int ReliquaryUpgradeRsp = 20217;
    public static final int SceneAudioNotify = 21580;
    public static final int SceneEntityMoveNotify = 153951; // 7026 or 22008
    public static final int SceneEntityUpdateNotify = 399729; // 1936 or 6409
    public static final int ScenePlayerSoundNotify = 1408;
    public static final int SceneWeatherForcastReq = 23364;
    public static final int ServerDisconnectClientNotify = 1387;
    public static final int SetCoopChapterViewedRsp = 2246; // 2246 or 29751 or 22019
    public static final int SetPlayerBornDataReq = 25726;
    public static final int ShowCommonTipsNotify = 20003; //oldVersion
    public static final int StartCoopPointReq = 27436;
    public static final int StartCoopPointRsp = 2147;
    public static final int TakeAchievementGoalRewardReq = 4455; // 4455 or 24332
    public static final int TakeAchievementGoalRewardRsp = 26805; // 26805 or 1595
    public static final int TakeAchievementRewardReq = 24332; // 4455 or 24332
    public static final int TakeAchievementRewardRsp = 1595; // 26805 or 1595
    public static final int TakeBattlePassMissionPointReq = 6231;
    public static final int TakeBattlePassRewardReq = 29828;
    public static final int TakeBattlePassRewardRsp = 941;
    public static final int TakeFurnitureMakeReq = 2795;
    public static final int TakeFurnitureMakeRsp = 6584;
    public static final int TakePlayerLevelRewardRsp = 21700;
    public static final int UnlockNameCardNotify = 20229;
    public static final int UnlockPersonalLineReq = 2554; // 2554 or 727
    public static final int UnlockPersonalLineRsp = 24052;
    // 做饭
    public static final int PlayerCookArgsReq = 6593;
    public static final int PlayerCookArgsRsp = 669067; //oldVersion 主要字段没有特征 先不解
    public static final int PlayerCookReq = 192;
    public static final int PlayerCookRsp = 23979;
    // 销毁材料
    public static final int DestroyMaterialReq = 28057;
    public static final int DestroyMaterialRsp = 21531;
    // 解锁命座
    public static final int UnlockAvatarTalentReq = 6454;
    public static final int UnlockAvatarTalentRsp = 23185;
    // 房主踢人
    public static final int SceneKickPlayerReq = 27213;
    public static final int SceneKickPlayerRsp = 7966; // 7966 or 20150 or 9301 or 24287 or 5497 or 21021 or 7700
    // 自己退房间
    public static final int PlayerGetForceQuitBanInfoReq = 29558;
    // 任务创建的实体 例如风魔龙的眼泪
    public static final int QuestCreateEntityReq = 21882;
    public static final int QuestCreateEntityRsp = 8838;
    // 返回单人世界 作用未知
    public static final int BackMyWorldReq = 343333; // 虚假的值 todo
    public static final int BackMyWorldRsp = 23771;
    // 任务传送
    public static final int QuestTransmitReq = 24079;
    public static final int QuestTransmitRsp = 2300;
    // 客户端退出游戏
    public static final int PlayerForceExitReq = 26372;
    public static final int PlayerForceExitRsp = 666;
    // 切换配队
    public static final int ChooseCurAvatarTeamReq = 29682;
    public static final int ChooseCurAvatarTeamRsp = 5985;
    // 添加配队容量
    public static final int AddBackupAvatarTeamReq = 23418;
    public static final int AddBackupAvatarTeamRsp = 7643; // 随便编的值
    // 场景能力变化 例如秘境解锁方碑创造风场的风场
    public static final int SceneForceLockNotify = 27356;
    public static final int SceneForceUnlockNotify = 2583;
    // 调整时间
    public static final int SkipPlayerGameTimeReq = 29432; // 玩家通过esc调整时间
    public static final int SkipPlayerGameTimeRsp = 338;
    public static final int ChangeGameTimeReq = 9437;
    public static final int ChangeGameTimeRsp = 29694;
    // 角色在秘境死亡
    public static final int DungeonPlayerDieReq = 23261;
    public static final int DungeonPlayerDieRsp = 788161; //oldVersion
    // 机关相关
    public static final int PlatformChangeRouteNotify = 841002; //oldVersion
    public static final int PlatformStartRouteNotify = 2989;
    public static final int PlatformStopRouteNotify = 898349; //oldVersion
    // 可能是主角切换元素
    public static final int AvatarChangeElementTypeReq = 21263;
    public static final int AvatarChangeElementTypeRsp = 401803; //oldVersion 单个retcode不用解
    // 联机配队
    public static final int ChangeMpTeamAvatarReq = 28747;
    public static final int ChangeMpTeamAvatarRsp = 28252;
    // 装备卸下
    public static final int TakeoffEquipReq = 24083;
    public static final int TakeoffEquipRsp = 7489;
    // 纪行
    public static final int SetBattlePassViewedReq = 26483;
    public static final int SetBattlePassViewedRsp = 9890; // 可能是 22048 533 26489 902 28919 9890 23101 21184 9036 目前实测都无效
    // 深渊
    public static final int TowerAllDataRsp = 22979;
    public static final int TowerBriefDataNotify = 6643;
    public static final int TowerCurLevelRecordChangeNotify = 7108;
    public static final int TowerDailyRewardProgressChangeNotify = 26940;
    public static final int EnterTrialAvatarActivityDungeonReq = 20982;
    public static final int TowerEnterLevelReq = 22746;
    public static final int TowerEnterLevelRsp = 21726;
    public static final int TowerFloorRecordChangeNotify = 25333;
    public static final int TowerGetFloorStarRewardReq = 5963;
    public static final int TowerGetFloorStarRewardRsp = 21871;
    public static final int TowerLevelEndNotify = 22669;
    public static final int TowerLevelStarCondNotify = 23130;
    public static final int TowerRecordHandbookRsp = 23004;
    public static final int TowerTeamSelectReq = 21495;
    public static final int TowerTeamSelectRsp = 474340; //oldVersion 单个retcode不用解
    public static final int TrialAvatarFirstPassDungeonNotify = 8103;

    // Opcodes 5.0.0
    public static final int AddQuestContentProgressReq = 20088;
    public static final int AddQuestContentProgressRsp = 22640;
    public static final int AvatarChangeCostumeNotify = 5367;
    public static final int AvatarDataNotify = 23378;
    public static final int AvatarEquipChangeNotify = 6767;
    public static final int AvatarTeamAllDataNotify = 22603;
    public static final int AvatarTeamUpdateNotify = 28759;
    public static final int ChangeAvatarReq = 3470;
    public static final int ChangeAvatarRsp = 2046;
    public static final int ClientAbilityChangeNotify = 27339;
    public static final int ClientAbilityInitFinishNotify = 28413;
    public static final int CombatInvocationsNotify = 5253;
    public static final int CutSceneBeginNotify = 455;
    public static final int CutSceneEndNotify = 29561;
    public static final int CutSceneFinishNotify = 8491;
    public static final int DungeonEntryInfoReq = 6446;
    public static final int DropItemReq = 23432;
    public static final int DropItemRsp = 2505;
    public static final int EntityFightPropChangeReasonNotify = 7107;
    public static final int EntityFightPropNotify = 1688;
    public static final int EntityFightPropUpdateNotify = 6590;
    public static final int EnterSceneDoneReq = 4561;
    public static final int EnterSceneDoneRsp = 793;
    public static final int EnterScenePeerNotify = 9626;
    public static final int EnterSceneReadyReq = 20524;
    public static final int EnterSceneReadyRsp = 7914;
    public static final int EvtBeingHitNotify = 4586;
    public static final int EvtBeingHealedNotify = 26087;
    public static final int EvtBeingHitsCombineNotify = 5583;
    public static final int EvtCreateGadgetNotify = 21187;
    public static final int EvtDoSkillSuccNotify = 1941;
    public static final int FinishedParentQuestNotify = 25902;
    public static final int FinishedParentQuestUpdateNotify = 28362;
    public static final int GadgetInteractReq = 26009;
    public static final int GadgetInteractRsp = 28160;
    public static final int GetPlayerFriendListReq = 21607;
    public static final int GetPlayerFriendListRsp = 893;
    public static final int GetPlayerSocialDetailReq = 3597;
    public static final int GetPlayerSocialDetailRsp = 1771;
    public static final int GetPlayerTokenReq = 6013;
    public static final int GetPlayerTokenRsp = 24174;
    public static final int GetSceneAreaReq = 8189;
    public static final int GetSceneAreaRsp = 27301;
    public static final int GetScenePointReq = 23449;
    public static final int GetScenePointRsp = 29349;
    public static final int HostPlayerNotify = 2109;
    public static final int LifeStateChangeNotify = 29321;
    public static final int MarkMapReq = 9550;
    public static final int NpcTalkReq = 24255;
    public static final int NpcTalkRsp = 23865;
    public static final int OpenStateChangeNotify = 26658;
    public static final int OpenStateUpdateNotify = 29093;
    public static final int PathfindingEnterSceneReq = 2374;
    public static final int PingReq = 5983;
    public static final int PingRsp = 22595;
    public static final int PlayerDataNotify = 7961;
    public static final int PlayerEnterSceneInfoNotify = 26700;
    public static final int PlayerEnterSceneNotify = 3595;
    public static final int PlayerGameTimeNotify = 4423;
    public static final int PlayerLoginReq = 2422;
    public static final int PlayerLoginRsp = 27771;
    public static final int PlayerSetPauseReq = 8076;
    public static final int PlayerSetPauseRsp = 25030;
    public static final int PlayerStoreNotify = 7845;
    public static final int PlayerWorldSceneInfoListNotify = 8028;
    public static final int PostEnterSceneReq = 3633;
    public static final int PostEnterSceneRsp = 22743;
    public static final int PrivateChatNotify = 6396;
    public static final int PrivateChatReq = 24426;
    public static final int PullPrivateChatReq = 8925;
    public static final int PullPrivateChatRsp = 29160;
    public static final int PullRecentChatReq = 6977;
    public static final int PullRecentChatRsp = 26725;
    public static final int QuestDestroyNpcReq = 1472;
    public static final int QuestDestroyNpcRsp = 23800;
    public static final int QuestListNotify = 23350;
    public static final int QuestListUpdateNotify = 3344;
    public static final int QuestProgressUpdateNotify = 28348;
    public static final int SceneAreaWeatherNotify = 21395;
    public static final int SceneDataNotify = 23046;
    public static final int SceneEntityAppearNotify = 6263;
    public static final int SceneEntityDisappearNotify = 29127;
    public static final int SceneInitFinishReq = 377;
    public static final int SceneInitFinishRsp = 24671;
    public static final int ScenePlayerInfoNotify = 7477;
    public static final int SceneTeamUpdateNotify = 29107;
    public static final int SceneTimeNotify = 29187;
    public static final int SceneTransToPointReq = 4027;
    public static final int SceneTransToPointRsp = 24104;
    public static final int ServerTimeNotify = 28606;
    public static final int SetUpAvatarTeamReq = 22244;
    public static final int SetUpAvatarTeamRsp = 306;
    public static final int SetEntityClientDataNotify = 5306;
    public static final int StoreItemChangeNotify = 2646;
    public static final int StoreWeightLimitNotify = 3034;
    public static final int SyncScenePlayTeamEntityNotify = 26946;
    public static final int SyncTeamEntityNotify = 29231;
    public static final int ToTheMoonEnterSceneReq = 6116;
    public static final int UnionCmdNotify = 9762;
    public static final int WearEquipReq = 7023;
    public static final int WearEquipRsp = 3218;
    public static final int WindSeedType1Notify = 7486;
    public static final int WorldDataNotify = 23950;
    public static final int WorldRoutineChangeNotify = 22801;
    public static final int WorldRoutineTypeRefreshNotify = 1571;
    public static final int WorldRoutineTypeCloseNotify = 3414;
    public static final int ToTheMoonQueryPathRsp = 6148;
    public static final int PlayerInvestigationNotify = 6848;
    public static final int EnterCustomDungeonRsp = 6315; // proto
    public static final int AvatarGainCostumeNotify = 25978;
    public static final int PlayerQuitDungeonRsp = 27043;
    public static final int GetAllMailResultNotify = 20649;
    public static final int RemotePlayerWidgetNotify = 28693;
    public static final int PlayerLuaShellNotify = 5224;
    public static final int GetPlayerAskFriendListRsp = 3915;
    public static final int BattlePassAllDataNotify = 27624;
    public static final int PlayerGameTimeByLuaNotify = 2122;
    public static final int PlayerInvestigationAllInfoNotify = 1519;
    public static final int EvtAvatarLockChairRsp = 5831;
    public static final int AvatarChangeCostumeRsp = 3408;
    public static final int TakeBattlePassMissionPointRsp = 23201;
    public static final int EvtAvatarStandUpNotify = 28594;
    public static final int AvatarLifeStateChangeNotify = 4653;
    public static final int PlayerInvestigationTargetNotify = 5321;
    public static final int AvatarFlycloakChangeNotify = 28644;
    public static final int EvtBulletHitNotify = 2465;
    public static final int AvatarPromoteGetRewardRsp = 5757;
    public static final int AvatarPropNotify = 21114;
    public static final int SetOpenStateRsp = 7944;
    public static final int RedeemLegendaryKeyRsp = 22912;
    public static final int BattlePassCurScheduleUpdateNotify = 1819;
    public static final int NormalUidOpNotify = 8839;
    public static final int ShowTemplateReminderNotify = 27975;
    public static final int SceneEntityDrownRsp = 1742;
    public static final int EntityAuthorityChangeNotify = 7710;
    public static final int PlayerTimeNotify = 2272;
    public static final int QuestUpdateQuestVarNotify = 29565;
    public static final int ServerGlobalValueChangeNotify = 25816;
    public static final int GetInvestigationMonsterRsp = 21253;
    public static final int AvatarDieAnimationEndReq = 943;
    public static final int AvatarDieAnimationEndRsp = 20675;
    public static final int SetNameCardReq = 20106;
    public static final int SetNameCardRsp = 27175;
    public static final int SetPlayerNameReq = 9269;
    public static final int SetPlayerNameRsp = 24044;
    public static final int SetPlayerSignatureReq = 1006;
    public static final int SetPlayerSignatureRsp = 24101;
    public static final int PersonalSceneJumpReq = 25750;
    public static final int GetProfilePictureDataReq = 22511;
    public static final int GetProfilePictureDataRsp = 1846;
    public static final int ProfilePictureUpdateNotify = 5942;
    public static final int SetPlayerHeadImageReq = 21526;
    public static final int SetPlayerHeadImageRsp = 21563;
    public static final int GetAllUnlockNameCardReq = 5009;
    public static final int GetAllUnlockNameCardRsp = 2632;
    public static final int SetPlayerBirthdayReq = 26726;
    public static final int SetPlayerBirthdayRsp = 9150;
    public static final int GalleryWillStartCountdownNotify = 2443;
    public static final int GetWidgetSlotRsp = 5441;
    public static final int AvatarExpeditionDataNotify = 22907;
    public static final int BattlePassChangeRewardPlanReq = 2925;
    public static final int BattlePassChangeRewardPlanRsp = 20530;
    public static final int BattlePassMissionUpdateNotify = 3190;
    public static final int GetParentQuestVideoKeyReq = 24330;
    public static final int GetParentQuestVideoKeyRsp = 28710;
    public static final int VehicleStaminaNotify = 1047;
    public static final int ServerBuffChangeNotify = 21009;
    public static final int VehicleInteractReq = 25867;
    public static final int VehicleInteractRsp = 27433;
    public static final int ScenePlayerLocationNotify = 29696;
    public static final int PlayerPropChangeNotify = 27937;
    public static final int PlayerPropChangeReasonNotify = 25374;
    public static final int PlayerPropNotify = 25998;
    public static final int GetDailyDungeonEntryInfoRsp = 6779;
    public static final int DungeonPreloadMonsterNotify = 27900;
    public static final int RegionSearchNotify = 22051;
    public static final int EffigyChallengeV4PrepareNotify = 25107;
    public static final int GetCityHuntingOfferRsp = 7671;
    public static final int GMShowNavMeshRsp = 2319;
    public static final int DealAddFriendRsp = 29289;
    public static final int CodexDataUpdateNotify = 27330;
    public static final int FishBattleEndRsp = 23385;
    public static final int GetUgcDungeonBriefListRsp = 3263; // proto
    public static final int AchievementAllDataNotify = 259;
    public static final int HideAndSeekSelectAvatarRsp = 27773;
    public static final int ChapterStateNotify = 25075;
    public static final int DataResVersionNotify = 7450;
    public static final int GCGReplayAskDuelRsp = 7905; // proto
    public static final int GetCustomDungeonRsp = 9793; // proto
    public static final int IslandPartySailInfoNotify = 5059; // proto
    public static final int MarkMapRsp = 21436;
    public static final int OtherPlayerEnterHomeNotify = 22683;
    public static final int SalvagePreventSettleNotify = 26962; // proto
    public static final int SceneEntitiesMovesRsp = 27402; // proto
    public static final int GetActivityInfoReq = 9710;
    public static final int GetActivityInfoRsp = 7719;
    public static final int ChatChannelUpdateNotify = 22161; // proto
    public static final int ChatChannelInfoNotify = 6555; // proto
    public static final int PlayerChatNotify = 25824;
    public static final int SetWidgetSlotReq = 22701;
    public static final int SetWidgetSlotRsp = 7049;
    public static final int WidgetSlotChangeNotify = 24715;
    public static final int CreateVehicleReq = 9915;
    public static final int CreateVehicleRsp = 22592;
    public static final int DungeonEntryInfoRsp = 27112;
    public static final int PlayerEnterDungeonReq = 7557;
    public static final int PlayerEnterDungeonRsp = 3067;
    public static final int PlayerQuitDungeonReq = 25440;
    public static final int SelectWorktopOptionReq = 23125;
    public static final int SelectWorktopOptionRsp = 1697;
    public static final int UseItemReq = 9576;
    public static final int UseItemRsp = 7672;
    public static final int EvtAiSyncSkillCdNotify = 28128;
    public static final int DungeonChallengeBeginNotify = 28604;
    public static final int ChallengeDataNotify = 25295;
    public static final int GetCityReputationInfoReq = 23347; // code
    public static final int GetCityReputationInfoRsp = 9100; // code
    public static final int GetTribeReputationInfoReq = 2288; // code
    public static final int GetTribeReputationInfoRsp = 198; // code
    public static final int WorktopOptionNotify = 28583;
    public static final int GadgetStateNotify = 21201;
    public static final int DungeonChallengeFinishNotify = 753;
    public static final int ToTheMoonEnterSceneRsp = 2333;
    public static final int WorldPlayerDieNotify = 2689;
    public static final int WorldPlayerReviveReq = 2401;
    public static final int WorldPlayerReviveRsp = 22159;
    public static final int EntityPropNotify = 4041;
    public static final int GetFriendShowAvatarInfoRsp = 27251;
    public static final int GetPlayerBlacklistReq = 6441;
    public static final int GetPlayerAskFriendListReq = 1813;
    public static final int GetPlayerBlacklistRsp = 23797;
    public static final int GetPlayerMpModeAvailabilityRsp = 25740;
    public static final int UpdatePlayerShowAvatarListReq = 3998;
    public static final int UpdatePlayerShowAvatarListRsp = 20659;
    public static final int UpdatePlayerShowNameCardListReq = 7487;
    public static final int UpdatePlayerShowNameCardListRsp = 8022;
    public static final int AvatarFetterDataNotify = 4274;
    public static final int WidgetDoBagReq = 1993;
    public static final int WidgetDoBagRsp = 9170;
    public static final int WidgetGadgetAllDataNotify = 26345;
    public static final int WidgetGadgetDataNotify = 380;
    public static final int HomeChooseModuleReq = 8855;
    public static final int HomeChooseModuleRsp = 2292;
    public static final int TryEnterHomeReq = 29384;
    public static final int TryEnterHomeRsp = 21829;
    public static final int HomeBasicInfoNotify = 20840;
    public static final int HomeLimitedShopInfoNotify = 23361;
    public static final int PlayerQuitFromHomeNotify = 3135;
    public static final int AllMarkPointNotify = 24780;
    public static final int BatchDelMapMarkReq = 7369; // code
    public static final int BatchDelMapMarkRsp = 2768; // code
    public static final int HomeModuleSeenReq = 24019;
    public static final int HomeModuleSeenRsp = 5790;
    public static final int ItemAddHintNotify = 26599;
    public static final int PlayerHomeCompInfoNotify = 20264;
    public static final int GetAreaExplorePointReq = 21085; // code
    public static final int GetAreaExplorePointRsp = 29332; // code
    public static final int HomeComfortInfoNotify = 279;
    public static final int HomeModuleUnlockNotify = 27507;
    public static final int FurnitureCurModuleArrangeCountNotify = 21517;
    public static final int HomeMarkPointNotify = 22396;
    public static final int HomeAllUnlockedBgmIdListNotify = 22324;
    public static final int HomeAvatarAllFinishRewardNotify = 9322;
    public static final int HomeGetBasicInfoReq = 9267;
    public static final int HomePreChangeEditModeNotify = 3607;
    public static final int HomeChangeEditModeReq = 22458;
    public static final int HomeChangeEditModeRsp = 2916;
    public static final int HomeEnterEditModeFinishReq = 9796;
    public static final int HomeEnterEditModeFinishRsp = 28448;
    public static final int HomeChangeBgmNotify = 29481;
    public static final int HomeChangeBgmReq = 4543;
    public static final int HomeGetArrangementInfoReq = 24996;
    public static final int HomeGetArrangementInfoRsp = 9688;
    public static final int HomeUpdateArrangementInfoRsp = 25852;
    public static final int HomeUpdateArrangementInfoReq = 344;
    public static final int GetShopReq = 4619;
    public static final int GetShopRsp = 5665; // ShopGoods proto
    public static final int ActivityScheduleInfoNotify = 28401;
    public static final int GetActivityScheduleRsp = 26417;
    public static final int PersonalLineAllDataReq = 28403;
    public static final int CodexDataFullNotify = 9784; // proto
    public static final int PlayerMatchSuccNotify = 7007; // proto
    public static final int SalvageEscortSettleNotify = 7421; // proto
    public static final int ServerUpdateGlobalValueNotify = 1498; // proto
    public static final int UgcDungeonPlayRecordNotify = 7584; // proto
    public static final int ViewCodexRsp = 28795; // proto
    public static final int SaveUgcRsp = 5480; // proto
    public static final int ActivityInfoNotify = 29575;
    public static final int HomeAvatarSummonAllEventNotify = 22990;
    public static final int HomeAvatarSummonEventReq = 27629;
    public static final int HomeAvatarRewardEventNotify = 1329;
    public static final int HomeAvatarTalkFinishInfoNotify = 20880;
    public static final int HomeAvatarTalkRsp = 213;
    public static final int HomeSceneJumpReq = 5317;
    public static final int HomeSceneJumpRsp = 28622;
    public static final int HomeTransferReq = 2203;
    public static final int GetInvestigationMonsterReq = 5610; // proto
    public static final int GetHomeLevelUpRewardReq = 21606; // proto
    public static final int HomeAvatarRewardEventGetReq = 7571;
    public static final int HomeAvatarRewardEventGetRsp = 5969;
    public static final int GetAllMailNotify = 7646;
    public static final int GetGachaInfoReq = 7728;
    public static final int GetGachaInfoRsp = 9090;
    public static final int DoGachaReq = 22082;
    public static final int DoGachaRsp = 20937;
    public static final int AvatarChangeCostumeReq = 28185;
    public static final int HomeAvatarCostumeChangeNotify = 7004;
    public static final int AvatarWearFlycloakReq = 243;
    public static final int AvatarWearFlycloakRsp = 27660;
    public static final int AvatarGainFlycloakNotify = 6824;
    public static final int AvatarChangeTraceEffectReq = 28932;
    public static final int PlayerApplyEnterMpResultNotify = 8810;
    public static final int GetOnlinePlayerInfoRsp = 25443;
    public static final int PlayerApplyEnterMpNotify = 5245;
    public static final int PlayerApplyEnterMpReq = 4701;
    public static final int PlayerApplyEnterMpRsp = 24897;
    public static final int PlayerApplyEnterMpResultReq = 23674;
    public static final int PlayerApplyEnterMpAfterMatchAgreedNotify = 21662;
    public static final int DeathZoneInfoNotify = 24379;
    public static final int AddFriendNotify = 23316;
    public static final int AskAddFriendNotify = 5432;
    public static final int AskAddFriendReq = 23646;
    public static final int DealAddFriendReq = 21886;
    public static final int SetFriendRemarkNameReq = 29399;
    public static final int SetFriendRemarkNameRsp = 6029;
    public static final int GetFriendShowAvatarInfoReq = 20766;
    public static final int GetFriendShowNameCardInfoRsp = 1685;
    public static final int SetFriendEnterHomeOptionReq = 20740;
    public static final int GetOnlinePlayerListReq = 27044;
    public static final int GetOnlinePlayerListRsp = 9049;
    public static final int SetPlayerPropReq = 23363;
    public static final int GetShopmallDataReq = 21348; // proto
    public static final int GetActivityShopSheetInfoReq = 21652; // proto
    public static final int GetActivityShopSheetInfoRsp = 23513; // proto
    public static final int ServerAnnounceNotify = 25165; // proto
    public static final int EvtDestroyGadgetNotify = 26080; // proto
    public static final int ChangeWorldToSingleModeRsp = 20845; // proto
    public static final int GetWorldMpInfoReq = 6731; // proto
    public static final int GetWorldMpInfoRsp = 3080; // proto
    public static final int GetWidgetSlotReq = 9388;
    public static final int HomeSaveBlueprintToSlotRsp = 24788; // proto
    public static final int HomeGetBlueprintSlotInfoReq = 9031; // proto
    public static final int HomeGetBlueprintSlotInfoRsp = 23776; // proto
    public static final int HomeCreateBlueprintRsp = 25729; // proto
    public static final int WorldPlayerLocationNotify = 22207;
    public static final int ResinChangeNotify = 4336;
    public static final int GetAllMailReq = 7646;
    public static final int GetAllMailRsp = 22156;
    public static final int GetMailItemReq = 8354;
    public static final int GetMailItemRsp = 9691;
    public static final int MailChangeNotify = 27744;
    public static final int ReadMailNotify = 23556;
    public static final int ChangeMailStarNotify = 29855;
    public static final int DelMailReq = 8496;
    public static final int DelMailRsp = 26121;
    public static final int HitTreeNotify = 20542;
    public static final int TheaterLobbySceneJumpReq = 27152; // code
    public static final int TheaterLobbySceneJumpRsp = 25402; // code
    public static final int EvtAvatarLockChairReq = 8990;
    public static final int ObstacleModifyNotify = 2384;
    public static final int SetOpenStateReq = 24291;
    public static final int GetMapMarkTipsReq = 22105; // proto
    public static final int GetMapMarkTipsRsp = 4123; // proto
    public static final int GetCityReputationMapInfoReq = 22557; // proto
    public static final int GetCityReputationMapInfoRsp = 8829; // proto
    public static final int GetMapAreaReq = 20412;
    public static final int GetMapAreaRsp = 22235;
    public static final int GetQuestLackingResourceReq = 25557;
    public static final int PlayerOfferingDataNotify = 22692; // proto
    public static final int PlayerOfferingReq = 20022; // proto
    public static final int PlayerOfferingRsp = 22611; // proto
    public static final int OfferingInteractReq = 25413; // proto
    public static final int OfferingInteractRsp = 29863; // proto
    public static final int EnterWorldAreaReq = 479;
    public static final int EnterWorldAreaRsp = 7481;
    public static final int AbilityChangeNotify = 21684; // proto
    public static final int SceneAreaUnlockNotify = 25419;
    public static final int UnfreezeGroupLimitNotify = 2540;
    public static final int MapAreaChangeNotify = 21409;
    public static final int QueryCodexMonsterBeKilledNumReq = 5718; // proto
    public static final int QueryCodexMonsterBeKilledNumRsp = 27403; // proto
    public static final int GetRegionSearchReq = 27191;
    public static final int GetHomeExchangeWoodInfoReq = 5768;
    public static final int PlayerChatReq = 21209;
    public static final int GetWidgetQuickSlotListReq = 24642;
    public static final int TowerAllDataReq = 2265;
    public static final int GetAllSceneGalleryInfoReq = 20484; // proto
    public static final int GetPlayerHomeCompInfoReq = 23660;
    public static final int GetFurnitureCurModuleArrangeCountReq = 22795;
    public static final int FurnitureMakeReq = 25118;
    public static final int OfferingPariSearchFinishNotify = 8450; // proto
    public static final int OfferingPariSearchReq = 2718; // proto
    public static final int OfferingPariSearchResultNotify = 2291; // proto
    public static final int OfferingPariSearchRsp = 25566; // proto
    public static final int OfferingPariTakeFinishRewardReq = 8618; // proto
    public static final int OfferingPariTakeFinishRewardRsp = 5745; // proto
    public static final int TakeOfferingLevelRewardReq = 29487; // proto
    public static final int TakeOfferingLevelRewardRsp = 24073; // proto
    public static final int ScenePointUnlockNotify = 21959;
    public static final int OpenBlossomCircleCampGuideNotify = 8953;
    public static final int DungeonPlayerDieNotify = 28876;
    public static final int DungeonDieOptionReq = 4398;
    public static final int DungeonDieOptionRsp = 28706;
    public static final int ChangeTeamNameReq = 29880;
    public static final int ChangeTeamNameRsp = 7491;
    public static final int AbilityInvocationsNotify = 4844;
    public static final int WorldPlayerRTTNotify = 22234;
    public static final int PlayerApplyEnterMpResultRsp = 27380;
    public static final int PlayerGetForceQuitBanInfoRsp = 29159;
    public static final int PlayerPreEnterMpNotify = 23352;
    public static final int WorldPlayerInfoNotify = 23024;
    public static final int WeaponAwakenReq = 20421;
    public static final int WeaponAwakenRsp = 24076;
    public static final int WeaponPromoteReq = 3230;
    public static final int WeaponPromoteRsp = 25392;
    public static final int WeaponUpgradeReq = 7713;
    public static final int WeaponUpgradeRsp = 22661;
    public static final int CalcWeaponUpgradeReturnItemsReq = 20908;
    public static final int CalcWeaponUpgradeReturnItemsRsp = 6706;
    public static final int SetEquipLockStateReq = 5750;
    public static final int SetEquipLockStateRsp = 26633;
    public static final int AvatarUpgradeReq = 1568;
    public static final int AvatarUpgradeRsp = 512;
    public static final int AvatarSkillUpgradeReq = 25062;
    public static final int AvatarSkillUpgradeRsp = 7799;
    public static final int AvatarUnlockTalentNotify = 28793;
    public static final int HomeAvatarTalkReq = 21992;
    public static final int GetQuestLackingResourceRsp = 27981;
    public static final int QueryPathReq = 2339;
    public static final int QueryPathRsp = 2350;
    public static final int UnlockTransPointReq = 3518;
    public static final int UnlockTransPointRsp = 1; // proto


    // Packet Names
    public static final int PlayerEnterChildMapLayerNotify = 524312; //oldVersion 没有作用
    public static final int PlayerEnterMapLayerNotify = 475163; //oldVersion 没有作用
    public static final int ServerAnnounceRevokeNotify = 909345; //oldVersion 没有作用
    public static final int PlayerChatRsp = 737324; //oldVersion 可以忽略
    public static final int FurnitureMakeRsp = 172075; //oldVersion

    public static final int ActivityTakeWatcherRewardReq = 917663; //oldVersion
    public static final int ActivityTakeWatcherRewardRsp = 811171; //oldVersion
    public static final int ActivityUpdateWatcherNotify = 524456; //oldVersion
    public static final int AllWidgetDataNotify = 360751; //oldVersion todo proto需要的东西太多 先不搞
    // 可能是角色派遣
    public static final int AvatarExpeditionAllDataReq = 958864; //oldVersion
    public static final int AvatarExpeditionAllDataRsp = 369043; //oldVersion
    public static final int AvatarExpeditionCallBackReq = 106909; //oldVersion
    public static final int AvatarExpeditionCallBackRsp = 598446; //oldVersion
    public static final int AvatarExpeditionGetRewardReq = 655793; //oldVersion
    public static final int AvatarExpeditionGetRewardRsp = 483762; //oldVersion
    public static final int AvatarExpeditionStartReq = 360885; //oldVersion
    public static final int AvatarExpeditionStartRsp = 156088; //oldVersion

    public static final int BargainOfferPriceReq = 418306; //oldVersion
    public static final int BargainOfferPriceRsp = 549385; //oldVersion
    public static final int BargainStartNotify = 107019; //oldVersion
    public static final int BargainTerminateNotify = 868887; //oldVersion
    public static final int BeginCameraSceneLookNotify = 500314; //oldVersion 太难了先不解
    public static final int BuyBattlePassLevelReq = 394001; //oldVersion
    public static final int BuyBattlePassLevelRsp = 451346; //oldVersion

    public static final int CanUseSkillNotify = 492329; //oldVersion 不好解
    public static final int CancelCoopTaskReq = 533296; //oldVersion 未实现的数据包
    // todo 上面的可以不解
    public static final int CheckUgcStateReq = 623687; //oldVersion
    public static final int CheckUgcStateRsp = 820298; //oldVersion
    public static final int CheckUgcUpdateReq = 279629; //oldVersion
    public static final int CheckUgcUpdateRsp = 697433; //oldVersion
    public static final int ClientLockGameTimeNotify = 115870; //oldVersion 我觉得不用解
    public static final int CloseCommonTipsNotify = 689360; //oldVersion 不好解
    public static final int CombineDataNotify = 132348; //oldVersion 不好解

    public static final int CookDataNotify = 681240; //oldVersion todo
    public static final int CookRecipeDataNotify = 582959; //oldVersion

    public static final int DelBackupAvatarTeamReq = 484784; //oldVersion 等待抓取
    public static final int DelBackupAvatarTeamRsp = 918960; //oldVersion

    public static final int DeleteFriendNotify = 443852; //oldVersion 等待抓取
    public static final int DeleteFriendReq = 542163; //oldVersion
    public static final int DeleteFriendRsp = 509397; //oldVersion

    public static final int DungeonRestartReq = 370381; //oldVersion 等待抓取
    public static final int DungeonShowReminderNotify = 788185; //oldVersion 不好解
    public static final int DungeonSlipRevivePointActivateReq = 206553; //oldVersion 不好解
    public static final int DungeonSlipRevivePointActivateRsp = 394973; //oldVersion 不好解
    public static final int DungeonWayPointActivateReq = 575200; //oldVersion 不好解
    public static final int DungeonWayPointActivateRsp = 468707; //oldVersion 不好解

    public static final int EndCameraSceneLookNotify = 657338; //oldVersion 等待抓取

    public static final int EntityAiKillSelfNotify = 231443; //oldVersion 不好解

    public static final int EvtBulletDeactiveNotify = 837732; //oldVersion 懒得解了反正解不解都没事
    public static final int EvtBulletMoveNotify = 526439; //oldVersion 懒得解了反正解不解都没事

    public static final int FireworksLaunchDataNotify = 706811; //oldVersion 套娃太多了 todo
    public static final int FireworksReformDataNotify = 518397; //oldVersion 套娃太多了 todo

    public static final int ForgeGetQueueDataReq = 952800; //oldVersion 等待抓取
    public static final int ForgeQueueManipulateReq = 641518; //oldVersion
    public static final int ForgeQueueManipulateRsp = 150000; //oldVersion 疑似结构改变

    public static final int FurnitureMakeStartReq = 404091; //oldVersion

    public static final int GetAllActivatedBargainDataReq = 290129; //oldVersion 等待抓取
    public static final int GetAllActivatedBargainDataRsp = 716121; //oldVersion

    public static final int GetAllH5ActivityInfoReq = 961882; //oldVersion 等待抓取

    public static final int GetBargainDataReq = 748905; //oldVersion 不好解
    public static final int GetBargainDataRsp = 814444; //oldVersion

    public static final int GetChatEmojiCollectionReq = 822663; //oldVersion 等待抓取
    public static final int GetChatEmojiCollectionRsp = 642441; //oldVersion 不好解

    public static final int GetDungeonEntryExploreConditionRsp = 888227; //oldVersion 不好解 todo
    public static final int GetFriendShowNameCardInfoReq = 568752; //oldVersion 等待抓取
    public static final int GetHomeLevelUpRewardRsp = 814548; //oldVersion 不好解
    public static final int GetUgcBriefInfoReq = 609869; //oldVersion 跳过
    public static final int GetUgcBriefInfoRsp = 429653; //oldVersion 跳过
    public static final int GetUgcReq = 953944; //oldVersion
    public static final int GetUgcRsp = 765528; //oldVersion

    public static final int GmTalkReq = 274049; //oldVersion 等待抓取
    public static final int GroupSuiteNotify = 364223; //oldVersion 不好解
    public static final int GroupUnloadNotify = 847551; //oldVersion 不好解
    public static final int H5ActivityIdsNotify = 716487; //oldVersion 等待抓取

    // 家园
    public static final int HomeAvatarSummonEventRsp = 159473; //oldVersion
    public static final int HomeAvatarSummonFinishReq = 847603; //oldVersion
    public static final int HomeAvatarSummonFinishRsp = 634613; //oldVersion
    public static final int HomeChangeBgmRsp = 257799; //oldVersion
    public static final int HomeChangeModuleReq = 773896; //oldVersion
    public static final int HomeChangeModuleRsp = 618248; //oldVersion
    public static final int HomeGetOnlineStatusReq = 135007; //oldVersion
    public static final int HomeGetOnlineStatusRsp = 700256; //oldVersion
    public static final int HomeKickPlayerReq = 651104; //oldVersion
    public static final int HomeKickPlayerRsp = 241504; //oldVersion
    public static final int HomeNewUnlockedBgmIdListNotify = 479108; //oldVersion
    public static final int HomeResourceNotify = 176077; //oldVersion
    public static final int HomeResourceTakeFetterExpReq = 249808; //oldVersion
    public static final int HomeResourceTakeFetterExpRsp = 708570; //oldVersion
    public static final int HomeResourceTakeHomeCoinReq = 733149; //oldVersion
    public static final int HomeResourceTakeHomeCoinRsp = 544734; //oldVersion
    public static final int HomeSaveArrangementNoChangeReq = 274406; //oldVersion
    public static final int HomeSaveArrangementNoChangeRsp = 315374; //oldVersion
    public static final int HomeSceneInitFinishReq = 503791; //oldVersion
    public static final int HomeSceneInitFinishRsp = 462839; //oldVersion
    public static final int HomeTransferRsp = 241698; //oldVersion

    // 好像用不到这俩了
    public static final int ItemGivingReq = 971061; //oldVersion
    public static final int ItemGivingRsp = 594233; //oldVersion

    public static final int LaunchFireworksReq = 520750; //oldVersion 不好解
    public static final int LaunchFireworksRsp = 193071; //oldVersion 单个retcode 不用解

    public static final int ServerCondMeetQuestListUpdateNotify = 684648; //oldVersion 不好解
    public static final int MarkNewNotify = 324275; //oldVersion 不好解
    public static final int MonsterForceAlertNotify = 250802; //oldVersion 不好解
    public static final int PlayerLevelRewardUpdateNotify = 423345; //oldVersion 不好解
    public static final int QuickUseWidgetReq = 562927; //oldVersion 太麻烦了 以后再补
    public static final int QuickUseWidgetRsp = 816884; //oldVersion
    public static final int ReformFireworksReq = 784161; //oldVersion 太麻烦了 先不搞
    public static final int ReformFireworksRsp = 292642; //oldVersion 单个retcode 不用解
    public static final int SceneEntityDrownReq = 227668; //oldVersion 不好解
    public static final int SetChatEmojiCollectionReq = 367197; //oldVersion 不好解 而且看起来没什么用 跳过
    public static final int SetChatEmojiCollectionRsp = 268897; //oldVersion 单个retcode不用解

    public static final int SetFriendEnterHomeOptionRsp = 432773; //oldVersion 单个retcode 不用解
    public static final int SetPlayerBornDataRsp = 326292; //oldVersion 单个retcode不用解
    public static final int SetPlayerPropRsp = 834196; //oldVersion 单个retcode不用解

    public static final int SetUpLunchBoxWidgetReq = 400044; //oldVersion 不好解
    public static final int SetUpLunchBoxWidgetRsp = 334510; //oldVersion
    public static final int ShowClientGuideNotify = 367285; //oldVersion 不好解

    public static final int TakePlayerLevelRewardReq = 719942; //oldVersion 不好解
    public static final int TowerMiddleLevelChangeTeamNotify = 457943; //oldVersion 待抓取
    public static final int UnlockedFurnitureFormulaDataNotify = 777792; //oldVersion 不好解
    public static final int UnlockedFurnitureSuiteDataNotify = 794181; //oldVersion 不好解
}
