// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AbilityInvokeArgument.proto

package emu.grasscutter.net.proto;

public final class AbilityInvokeArgumentOuterClass {
  private AbilityInvokeArgumentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code AbilityInvokeArgument}
   */
  public enum AbilityInvokeArgument
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ABILITY_NONE = 0;</code>
     */
    ABILITY_NONE(0),
    /**
     * <code>ABILITY_META_MODIFIER_CHANGE = 1;</code>
     */
    ABILITY_META_MODIFIER_CHANGE(1),
    /**
     * <code>ABILITY_META_COMMAND_MODIFIER_CHANGE_REQUEST = 2;</code>
     */
    ABILITY_META_COMMAND_MODIFIER_CHANGE_REQUEST(2),
    /**
     * <code>ABILITY_META_SPECIAL_FLOAT_ARGUMENT = 3;</code>
     */
    ABILITY_META_SPECIAL_FLOAT_ARGUMENT(3),
    /**
     * <code>ABILITY_META_OVERRIDE_PARAM = 4;</code>
     */
    ABILITY_META_OVERRIDE_PARAM(4),
    /**
     * <code>ABILITY_META_CLEAR_OVERRIDE_PARAM = 5;</code>
     */
    ABILITY_META_CLEAR_OVERRIDE_PARAM(5),
    /**
     * <code>ABILITY_META_REINIT_OVERRIDEMAP = 6;</code>
     */
    ABILITY_META_REINIT_OVERRIDEMAP(6),
    /**
     * <code>ABILITY_META_GLOBAL_FLOAT_VALUE = 7;</code>
     */
    ABILITY_META_GLOBAL_FLOAT_VALUE(7),
    /**
     * <code>ABILITY_META_CLEAR_GLOBAL_FLOAT_VALUE = 8;</code>
     */
    ABILITY_META_CLEAR_GLOBAL_FLOAT_VALUE(8),
    /**
     * <code>ABILITY_META_ABILITY_ELEMENT_STRENGTH = 9;</code>
     */
    ABILITY_META_ABILITY_ELEMENT_STRENGTH(9),
    /**
     * <code>ABILITY_META_ADD_OR_GET_ABILITY_AND_TRIGGER = 10;</code>
     */
    ABILITY_META_ADD_OR_GET_ABILITY_AND_TRIGGER(10),
    /**
     * <code>ABILITY_META_SET_KILLED_SETATE = 11;</code>
     */
    ABILITY_META_SET_KILLED_SETATE(11),
    /**
     * <code>ABILITY_META_SET_ABILITY_TRIGGER = 12;</code>
     */
    ABILITY_META_SET_ABILITY_TRIGGER(12),
    /**
     * <code>ABILITY_META_ADD_NEW_ABILITY = 13;</code>
     */
    ABILITY_META_ADD_NEW_ABILITY(13),
    /**
     * <code>ABILITY_META_REMOVE_ABILITY = 14;</code>
     */
    ABILITY_META_REMOVE_ABILITY(14),
    /**
     * <code>ABILITY_META_SET_MODIFIER_APPLY_ENTITY = 15;</code>
     */
    ABILITY_META_SET_MODIFIER_APPLY_ENTITY(15),
    /**
     * <code>ABILITY_META_MODIFIER_DURABILITY_CHANGE = 16;</code>
     */
    ABILITY_META_MODIFIER_DURABILITY_CHANGE(16),
    /**
     * <code>ABILITY_META_ELEMENT_REACTION_VISUAL = 17;</code>
     */
    ABILITY_META_ELEMENT_REACTION_VISUAL(17),
    /**
     * <code>ABILITY_META_SET_POSE_PARAMETER = 18;</code>
     */
    ABILITY_META_SET_POSE_PARAMETER(18),
    /**
     * <code>ABILITY_META_UPDATE_BASE_REACTION_DAMAGE = 19;</code>
     */
    ABILITY_META_UPDATE_BASE_REACTION_DAMAGE(19),
    /**
     * <code>ABILITY_META_TRIGGER_ELEMENT_REACTION = 20;</code>
     */
    ABILITY_META_TRIGGER_ELEMENT_REACTION(20),
    /**
     * <code>ABILITY_META_LOSE_HP = 21;</code>
     */
    ABILITY_META_LOSE_HP(21),
    /**
     * <code>ABILITY_META_DURABILITY_IS_ZERO = 22;</code>
     */
    ABILITY_META_DURABILITY_IS_ZERO(22),
    /**
     * <code>ABILITY_META_TRIGGER_ARKHE_REACTION = 23;</code>
     */
    ABILITY_META_TRIGGER_ARKHE_REACTION(23),
    /**
     * <code>ABILITY_META_CHANGE_NYX_VALUE = 24;</code>
     */
    ABILITY_META_CHANGE_NYX_VALUE(24),
    /**
     * <code>ABILITY_ACTION_TRIGGER_ABILITY = 50;</code>
     */
    ABILITY_ACTION_TRIGGER_ABILITY(50),
    /**
     * <code>ABILITY_ACTION_SET_CRASH_DAMAGE = 51;</code>
     */
    ABILITY_ACTION_SET_CRASH_DAMAGE(51),
    /**
     * <code>ABILITY_ACTION_EFFECT = 52;</code>
     */
    ABILITY_ACTION_EFFECT(52),
    /**
     * <code>ABILITY_ACTION_SUMMON = 53;</code>
     */
    ABILITY_ACTION_SUMMON(53),
    /**
     * <code>ABILITY_ACTION_BLINK = 54;</code>
     */
    ABILITY_ACTION_BLINK(54),
    /**
     * <code>ABILITY_ACTION_CREATE_GADGET = 55;</code>
     */
    ABILITY_ACTION_CREATE_GADGET(55),
    /**
     * <code>ABILITY_ACTION_APPLY_LEVEL_MODIFIER = 56;</code>
     */
    ABILITY_ACTION_APPLY_LEVEL_MODIFIER(56),
    /**
     * <code>ABILITY_ACTION_GENERATE_ELEM_BALL = 57;</code>
     */
    ABILITY_ACTION_GENERATE_ELEM_BALL(57),
    /**
     * <code>ABILITY_ACTION_SET_RANDOM_OVERRIDE_MAP_VALUE = 58;</code>
     */
    ABILITY_ACTION_SET_RANDOM_OVERRIDE_MAP_VALUE(58),
    /**
     * <code>ABILITY_ACTION_SERVER_MONSTER_LOG = 59;</code>
     */
    ABILITY_ACTION_SERVER_MONSTER_LOG(59),
    /**
     * <code>ABILITY_ACTION_CREATE_TILE = 60;</code>
     */
    ABILITY_ACTION_CREATE_TILE(60),
    /**
     * <code>ABILITY_ACTION_DESTROY_TILE = 61;</code>
     */
    ABILITY_ACTION_DESTROY_TILE(61),
    /**
     * <code>ABILITY_ACTION_FIRE_AFTER_IMAGE = 62;</code>
     */
    ABILITY_ACTION_FIRE_AFTER_IMAGE(62),
    /**
     * <code>ABILITY_ACTION_DEDUCT_STAMINA = 63;</code>
     */
    ABILITY_ACTION_DEDUCT_STAMINA(63),
    /**
     * <code>ABILITY_ACTION_HIT_EFFECT = 64;</code>
     */
    ABILITY_ACTION_HIT_EFFECT(64),
    /**
     * <code>ABILITY_ACTION_SET_BULLET_TRACK_TARGET = 65;</code>
     */
    ABILITY_ACTION_SET_BULLET_TRACK_TARGET(65),
    /**
     * <code>ABILITY_ACTION_FIREWORK_EFFECT = 66;</code>
     */
    ABILITY_ACTION_FIREWORK_EFFECT(66),
    /**
     * <code>ABILITY_ACTION_LEVEL_BANK_ADD_STUFF = 67;</code>
     */
    ABILITY_ACTION_LEVEL_BANK_ADD_STUFF(67),
    /**
     * <code>ABILITY_ACTION_GET_MATERIAL_PARAM_FLOAT = 68;</code>
     */
    ABILITY_ACTION_GET_MATERIAL_PARAM_FLOAT(68),
    /**
     * <code>ABILITY_ACTION_GET_MATERIAL_PARAM_VECTOR = 69;</code>
     */
    ABILITY_ACTION_GET_MATERIAL_PARAM_VECTOR(69),
    /**
     * <code>ABILITY_ACTION_SPECTACLE_BUILD_RECREATE_GADGET = 70;</code>
     */
    ABILITY_ACTION_SPECTACLE_BUILD_RECREATE_GADGET(70),
    /**
     * <code>ABILITY_MIXIN_AVATAR_STEER_BY_CAMERA = 100;</code>
     */
    ABILITY_MIXIN_AVATAR_STEER_BY_CAMERA(100),
    /**
     * <code>ABILITY_MIXIN_MONSTER_DEFEND = 101;</code>
     */
    ABILITY_MIXIN_MONSTER_DEFEND(101),
    /**
     * <code>ABILITY_MIXIN_WIND_ZONE = 102;</code>
     */
    ABILITY_MIXIN_WIND_ZONE(102),
    /**
     * <code>ABILITY_MIXIN_COST_STAMINA = 103;</code>
     */
    ABILITY_MIXIN_COST_STAMINA(103),
    /**
     * <code>ABILITY_MIXIN_ELITE_SHIELD = 104;</code>
     */
    ABILITY_MIXIN_ELITE_SHIELD(104),
    /**
     * <code>ABILITY_MIXIN_ELEMENT_SHIELD = 105;</code>
     */
    ABILITY_MIXIN_ELEMENT_SHIELD(105),
    /**
     * <code>ABILITY_MIXIN_GLOBAL_SHIELD = 106;</code>
     */
    ABILITY_MIXIN_GLOBAL_SHIELD(106),
    /**
     * <code>ABILITY_MIXIN_SHIELD_BAR = 107;</code>
     */
    ABILITY_MIXIN_SHIELD_BAR(107),
    /**
     * <code>ABILITY_MIXIN_WIND_SEED_SPAWNER = 108;</code>
     */
    ABILITY_MIXIN_WIND_SEED_SPAWNER(108),
    /**
     * <code>ABILITY_MIXIN_DO_ACTION_BY_ELEMENT_REACTION = 109;</code>
     */
    ABILITY_MIXIN_DO_ACTION_BY_ELEMENT_REACTION(109),
    /**
     * <code>ABILITY_MIXIN_FIELD_ENTITY_COUNT_CHANGE = 110;</code>
     */
    ABILITY_MIXIN_FIELD_ENTITY_COUNT_CHANGE(110),
    /**
     * <code>ABILITY_MIXIN_SCENE_PROP_SYNC = 111;</code>
     */
    ABILITY_MIXIN_SCENE_PROP_SYNC(111),
    /**
     * <code>ABILITY_MIXIN_WIDGET_MP_SUPPORT = 112;</code>
     */
    ABILITY_MIXIN_WIDGET_MP_SUPPORT(112),
    /**
     * <code>ABILITY_MIXIN_DO_ACTION_BY_SELF_MODIFIER_ELEMENT_DURABILITY_RATIO = 113;</code>
     */
    ABILITY_MIXIN_DO_ACTION_BY_SELF_MODIFIER_ELEMENT_DURABILITY_RATIO(113),
    /**
     * <code>ABILITY_MIXIN_FIREWORKS_LAUNCHER = 114;</code>
     */
    ABILITY_MIXIN_FIREWORKS_LAUNCHER(114),
    /**
     * <code>ABILITY_MIXIN_ATTACK_RESULT_CREATE_COUNT = 115;</code>
     */
    ABILITY_MIXIN_ATTACK_RESULT_CREATE_COUNT(115),
    /**
     * <code>ABILITY_MIXIN_UGC_TIME_CONTROL = 116;</code>
     */
    ABILITY_MIXIN_UGC_TIME_CONTROL(116),
    /**
     * <code>ABILITY_MIXIN_AVATAR_COMBAT = 117;</code>
     */
    ABILITY_MIXIN_AVATAR_COMBAT(117),
    /**
     * <code>ABILITY_MIXIN_DEATH_ZONE_REGIONAL_PLAY_MIXIN = 118;</code>
     */
    ABILITY_MIXIN_DEATH_ZONE_REGIONAL_PLAY_MIXIN(118),
    /**
     * <code>ABILITY_MIXIN_UI_INTERACT = 119;</code>
     */
    ABILITY_MIXIN_UI_INTERACT(119),
    /**
     * <code>ABILITY_MIXIN_SHOOT_FROM_CAMERA = 120;</code>
     */
    ABILITY_MIXIN_SHOOT_FROM_CAMERA(120),
    /**
     * <code>ABILITY_MIXIN_ERASE_BRICK_ACTIVITY = 121;</code>
     */
    ABILITY_MIXIN_ERASE_BRICK_ACTIVITY(121),
    /**
     * <code>ABILITY_MIXIN_BREAKOUT = 122;</code>
     */
    ABILITY_MIXIN_BREAKOUT(122),
    /**
     * <code>ABILITY_MIXIN_DAMAGE_LOAN = 123;</code>
     */
    ABILITY_MIXIN_DAMAGE_LOAN(123),
    /**
     * <code>ABILITY_MIXIN_BROADCAST_GV = 124;</code>
     */
    ABILITY_MIXIN_BROADCAST_GV(124),
    /**
     * <code>ABILITY_MIXIN_RECEIVE_GV = 125;</code>
     */
    ABILITY_MIXIN_RECEIVE_GV(125),
    /**
     * <code>ABILITY_MIXIN_RAYCAST_SELECT_TARGET = 126;</code>
     */
    ABILITY_MIXIN_RAYCAST_SELECT_TARGET(126),
    /**
     * <code>ABILITY_MIXIN_ENERGY_CRYSTAL_TARGET = 127;</code>
     */
    ABILITY_MIXIN_ENERGY_CRYSTAL_TARGET(127),
    /**
     * <code>ABILITY_MIXIN_ROTATION_FOLLOW_CAMERA = 128;</code>
     */
    ABILITY_MIXIN_ROTATION_FOLLOW_CAMERA(128),
    /**
     * <code>ABILITY_MIXIN_BUOYANT_FORCE = 129;</code>
     */
    ABILITY_MIXIN_BUOYANT_FORCE(129),
    /**
     * <code>ABILITY_MIXIN_FILMFEST_BALL_GAME = 130;</code>
     */
    ABILITY_MIXIN_FILMFEST_BALL_GAME(130),
    /**
     * <code>ABILITY_MIXIN_CHECK_SCAN_ENTITY = 131;</code>
     */
    ABILITY_MIXIN_CHECK_SCAN_ENTITY(131),
    /**
     * <code>ABILITY_MIXIN_TIME_TRACK_PLAYER = 133;</code>
     */
    ABILITY_MIXIN_TIME_TRACK_PLAYER(133),
    /**
     * <code>ABILITY_MIXIN_PART_FOLLOW = 134;</code>
     */
    ABILITY_MIXIN_PART_FOLLOW(134),
    /**
     * <code>ABILITY_MIXIN_CHANGE_PHLOGISTON = 135;</code>
     */
    ABILITY_MIXIN_CHANGE_PHLOGISTON(135),
    /**
     * <code>ABILITY_MIXIN_HUMAN_DRAGON_COLLAB_PICK_PHLOGISTON_BALL = 136;</code>
     */
    ABILITY_MIXIN_HUMAN_DRAGON_COLLAB_PICK_PHLOGISTON_BALL(136),
    /**
     * <code>ABILITY_MIXIN_FREQUENCY_SHIELD_BAR = 137;</code>
     */
    ABILITY_MIXIN_FREQUENCY_SHIELD_BAR(137),
    /**
     * <code>ABILITY_MIXIN_VEHICLE_STEER_BY_CAMERA = 141;</code>
     */
    ABILITY_MIXIN_VEHICLE_STEER_BY_CAMERA(141),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ABILITY_NONE = 0;</code>
     */
    public static final int ABILITY_NONE_VALUE = 0;
    /**
     * <code>ABILITY_META_MODIFIER_CHANGE = 1;</code>
     */
    public static final int ABILITY_META_MODIFIER_CHANGE_VALUE = 1;
    /**
     * <code>ABILITY_META_COMMAND_MODIFIER_CHANGE_REQUEST = 2;</code>
     */
    public static final int ABILITY_META_COMMAND_MODIFIER_CHANGE_REQUEST_VALUE = 2;
    /**
     * <code>ABILITY_META_SPECIAL_FLOAT_ARGUMENT = 3;</code>
     */
    public static final int ABILITY_META_SPECIAL_FLOAT_ARGUMENT_VALUE = 3;
    /**
     * <code>ABILITY_META_OVERRIDE_PARAM = 4;</code>
     */
    public static final int ABILITY_META_OVERRIDE_PARAM_VALUE = 4;
    /**
     * <code>ABILITY_META_CLEAR_OVERRIDE_PARAM = 5;</code>
     */
    public static final int ABILITY_META_CLEAR_OVERRIDE_PARAM_VALUE = 5;
    /**
     * <code>ABILITY_META_REINIT_OVERRIDEMAP = 6;</code>
     */
    public static final int ABILITY_META_REINIT_OVERRIDEMAP_VALUE = 6;
    /**
     * <code>ABILITY_META_GLOBAL_FLOAT_VALUE = 7;</code>
     */
    public static final int ABILITY_META_GLOBAL_FLOAT_VALUE_VALUE = 7;
    /**
     * <code>ABILITY_META_CLEAR_GLOBAL_FLOAT_VALUE = 8;</code>
     */
    public static final int ABILITY_META_CLEAR_GLOBAL_FLOAT_VALUE_VALUE = 8;
    /**
     * <code>ABILITY_META_ABILITY_ELEMENT_STRENGTH = 9;</code>
     */
    public static final int ABILITY_META_ABILITY_ELEMENT_STRENGTH_VALUE = 9;
    /**
     * <code>ABILITY_META_ADD_OR_GET_ABILITY_AND_TRIGGER = 10;</code>
     */
    public static final int ABILITY_META_ADD_OR_GET_ABILITY_AND_TRIGGER_VALUE = 10;
    /**
     * <code>ABILITY_META_SET_KILLED_SETATE = 11;</code>
     */
    public static final int ABILITY_META_SET_KILLED_SETATE_VALUE = 11;
    /**
     * <code>ABILITY_META_SET_ABILITY_TRIGGER = 12;</code>
     */
    public static final int ABILITY_META_SET_ABILITY_TRIGGER_VALUE = 12;
    /**
     * <code>ABILITY_META_ADD_NEW_ABILITY = 13;</code>
     */
    public static final int ABILITY_META_ADD_NEW_ABILITY_VALUE = 13;
    /**
     * <code>ABILITY_META_REMOVE_ABILITY = 14;</code>
     */
    public static final int ABILITY_META_REMOVE_ABILITY_VALUE = 14;
    /**
     * <code>ABILITY_META_SET_MODIFIER_APPLY_ENTITY = 15;</code>
     */
    public static final int ABILITY_META_SET_MODIFIER_APPLY_ENTITY_VALUE = 15;
    /**
     * <code>ABILITY_META_MODIFIER_DURABILITY_CHANGE = 16;</code>
     */
    public static final int ABILITY_META_MODIFIER_DURABILITY_CHANGE_VALUE = 16;
    /**
     * <code>ABILITY_META_ELEMENT_REACTION_VISUAL = 17;</code>
     */
    public static final int ABILITY_META_ELEMENT_REACTION_VISUAL_VALUE = 17;
    /**
     * <code>ABILITY_META_SET_POSE_PARAMETER = 18;</code>
     */
    public static final int ABILITY_META_SET_POSE_PARAMETER_VALUE = 18;
    /**
     * <code>ABILITY_META_UPDATE_BASE_REACTION_DAMAGE = 19;</code>
     */
    public static final int ABILITY_META_UPDATE_BASE_REACTION_DAMAGE_VALUE = 19;
    /**
     * <code>ABILITY_META_TRIGGER_ELEMENT_REACTION = 20;</code>
     */
    public static final int ABILITY_META_TRIGGER_ELEMENT_REACTION_VALUE = 20;
    /**
     * <code>ABILITY_META_LOSE_HP = 21;</code>
     */
    public static final int ABILITY_META_LOSE_HP_VALUE = 21;
    /**
     * <code>ABILITY_META_DURABILITY_IS_ZERO = 22;</code>
     */
    public static final int ABILITY_META_DURABILITY_IS_ZERO_VALUE = 22;
    /**
     * <code>ABILITY_META_TRIGGER_ARKHE_REACTION = 23;</code>
     */
    public static final int ABILITY_META_TRIGGER_ARKHE_REACTION_VALUE = 23;
    /**
     * <code>ABILITY_META_CHANGE_NYX_VALUE = 24;</code>
     */
    public static final int ABILITY_META_CHANGE_NYX_VALUE_VALUE = 24;
    /**
     * <code>ABILITY_ACTION_TRIGGER_ABILITY = 50;</code>
     */
    public static final int ABILITY_ACTION_TRIGGER_ABILITY_VALUE = 50;
    /**
     * <code>ABILITY_ACTION_SET_CRASH_DAMAGE = 51;</code>
     */
    public static final int ABILITY_ACTION_SET_CRASH_DAMAGE_VALUE = 51;
    /**
     * <code>ABILITY_ACTION_EFFECT = 52;</code>
     */
    public static final int ABILITY_ACTION_EFFECT_VALUE = 52;
    /**
     * <code>ABILITY_ACTION_SUMMON = 53;</code>
     */
    public static final int ABILITY_ACTION_SUMMON_VALUE = 53;
    /**
     * <code>ABILITY_ACTION_BLINK = 54;</code>
     */
    public static final int ABILITY_ACTION_BLINK_VALUE = 54;
    /**
     * <code>ABILITY_ACTION_CREATE_GADGET = 55;</code>
     */
    public static final int ABILITY_ACTION_CREATE_GADGET_VALUE = 55;
    /**
     * <code>ABILITY_ACTION_APPLY_LEVEL_MODIFIER = 56;</code>
     */
    public static final int ABILITY_ACTION_APPLY_LEVEL_MODIFIER_VALUE = 56;
    /**
     * <code>ABILITY_ACTION_GENERATE_ELEM_BALL = 57;</code>
     */
    public static final int ABILITY_ACTION_GENERATE_ELEM_BALL_VALUE = 57;
    /**
     * <code>ABILITY_ACTION_SET_RANDOM_OVERRIDE_MAP_VALUE = 58;</code>
     */
    public static final int ABILITY_ACTION_SET_RANDOM_OVERRIDE_MAP_VALUE_VALUE = 58;
    /**
     * <code>ABILITY_ACTION_SERVER_MONSTER_LOG = 59;</code>
     */
    public static final int ABILITY_ACTION_SERVER_MONSTER_LOG_VALUE = 59;
    /**
     * <code>ABILITY_ACTION_CREATE_TILE = 60;</code>
     */
    public static final int ABILITY_ACTION_CREATE_TILE_VALUE = 60;
    /**
     * <code>ABILITY_ACTION_DESTROY_TILE = 61;</code>
     */
    public static final int ABILITY_ACTION_DESTROY_TILE_VALUE = 61;
    /**
     * <code>ABILITY_ACTION_FIRE_AFTER_IMAGE = 62;</code>
     */
    public static final int ABILITY_ACTION_FIRE_AFTER_IMAGE_VALUE = 62;
    /**
     * <code>ABILITY_ACTION_DEDUCT_STAMINA = 63;</code>
     */
    public static final int ABILITY_ACTION_DEDUCT_STAMINA_VALUE = 63;
    /**
     * <code>ABILITY_ACTION_HIT_EFFECT = 64;</code>
     */
    public static final int ABILITY_ACTION_HIT_EFFECT_VALUE = 64;
    /**
     * <code>ABILITY_ACTION_SET_BULLET_TRACK_TARGET = 65;</code>
     */
    public static final int ABILITY_ACTION_SET_BULLET_TRACK_TARGET_VALUE = 65;
    /**
     * <code>ABILITY_ACTION_FIREWORK_EFFECT = 66;</code>
     */
    public static final int ABILITY_ACTION_FIREWORK_EFFECT_VALUE = 66;
    /**
     * <code>ABILITY_ACTION_LEVEL_BANK_ADD_STUFF = 67;</code>
     */
    public static final int ABILITY_ACTION_LEVEL_BANK_ADD_STUFF_VALUE = 67;
    /**
     * <code>ABILITY_ACTION_GET_MATERIAL_PARAM_FLOAT = 68;</code>
     */
    public static final int ABILITY_ACTION_GET_MATERIAL_PARAM_FLOAT_VALUE = 68;
    /**
     * <code>ABILITY_ACTION_GET_MATERIAL_PARAM_VECTOR = 69;</code>
     */
    public static final int ABILITY_ACTION_GET_MATERIAL_PARAM_VECTOR_VALUE = 69;
    /**
     * <code>ABILITY_ACTION_SPECTACLE_BUILD_RECREATE_GADGET = 70;</code>
     */
    public static final int ABILITY_ACTION_SPECTACLE_BUILD_RECREATE_GADGET_VALUE = 70;
    /**
     * <code>ABILITY_MIXIN_AVATAR_STEER_BY_CAMERA = 100;</code>
     */
    public static final int ABILITY_MIXIN_AVATAR_STEER_BY_CAMERA_VALUE = 100;
    /**
     * <code>ABILITY_MIXIN_MONSTER_DEFEND = 101;</code>
     */
    public static final int ABILITY_MIXIN_MONSTER_DEFEND_VALUE = 101;
    /**
     * <code>ABILITY_MIXIN_WIND_ZONE = 102;</code>
     */
    public static final int ABILITY_MIXIN_WIND_ZONE_VALUE = 102;
    /**
     * <code>ABILITY_MIXIN_COST_STAMINA = 103;</code>
     */
    public static final int ABILITY_MIXIN_COST_STAMINA_VALUE = 103;
    /**
     * <code>ABILITY_MIXIN_ELITE_SHIELD = 104;</code>
     */
    public static final int ABILITY_MIXIN_ELITE_SHIELD_VALUE = 104;
    /**
     * <code>ABILITY_MIXIN_ELEMENT_SHIELD = 105;</code>
     */
    public static final int ABILITY_MIXIN_ELEMENT_SHIELD_VALUE = 105;
    /**
     * <code>ABILITY_MIXIN_GLOBAL_SHIELD = 106;</code>
     */
    public static final int ABILITY_MIXIN_GLOBAL_SHIELD_VALUE = 106;
    /**
     * <code>ABILITY_MIXIN_SHIELD_BAR = 107;</code>
     */
    public static final int ABILITY_MIXIN_SHIELD_BAR_VALUE = 107;
    /**
     * <code>ABILITY_MIXIN_WIND_SEED_SPAWNER = 108;</code>
     */
    public static final int ABILITY_MIXIN_WIND_SEED_SPAWNER_VALUE = 108;
    /**
     * <code>ABILITY_MIXIN_DO_ACTION_BY_ELEMENT_REACTION = 109;</code>
     */
    public static final int ABILITY_MIXIN_DO_ACTION_BY_ELEMENT_REACTION_VALUE = 109;
    /**
     * <code>ABILITY_MIXIN_FIELD_ENTITY_COUNT_CHANGE = 110;</code>
     */
    public static final int ABILITY_MIXIN_FIELD_ENTITY_COUNT_CHANGE_VALUE = 110;
    /**
     * <code>ABILITY_MIXIN_SCENE_PROP_SYNC = 111;</code>
     */
    public static final int ABILITY_MIXIN_SCENE_PROP_SYNC_VALUE = 111;
    /**
     * <code>ABILITY_MIXIN_WIDGET_MP_SUPPORT = 112;</code>
     */
    public static final int ABILITY_MIXIN_WIDGET_MP_SUPPORT_VALUE = 112;
    /**
     * <code>ABILITY_MIXIN_DO_ACTION_BY_SELF_MODIFIER_ELEMENT_DURABILITY_RATIO = 113;</code>
     */
    public static final int ABILITY_MIXIN_DO_ACTION_BY_SELF_MODIFIER_ELEMENT_DURABILITY_RATIO_VALUE = 113;
    /**
     * <code>ABILITY_MIXIN_FIREWORKS_LAUNCHER = 114;</code>
     */
    public static final int ABILITY_MIXIN_FIREWORKS_LAUNCHER_VALUE = 114;
    /**
     * <code>ABILITY_MIXIN_ATTACK_RESULT_CREATE_COUNT = 115;</code>
     */
    public static final int ABILITY_MIXIN_ATTACK_RESULT_CREATE_COUNT_VALUE = 115;
    /**
     * <code>ABILITY_MIXIN_UGC_TIME_CONTROL = 116;</code>
     */
    public static final int ABILITY_MIXIN_UGC_TIME_CONTROL_VALUE = 116;
    /**
     * <code>ABILITY_MIXIN_AVATAR_COMBAT = 117;</code>
     */
    public static final int ABILITY_MIXIN_AVATAR_COMBAT_VALUE = 117;
    /**
     * <code>ABILITY_MIXIN_DEATH_ZONE_REGIONAL_PLAY_MIXIN = 118;</code>
     */
    public static final int ABILITY_MIXIN_DEATH_ZONE_REGIONAL_PLAY_MIXIN_VALUE = 118;
    /**
     * <code>ABILITY_MIXIN_UI_INTERACT = 119;</code>
     */
    public static final int ABILITY_MIXIN_UI_INTERACT_VALUE = 119;
    /**
     * <code>ABILITY_MIXIN_SHOOT_FROM_CAMERA = 120;</code>
     */
    public static final int ABILITY_MIXIN_SHOOT_FROM_CAMERA_VALUE = 120;
    /**
     * <code>ABILITY_MIXIN_ERASE_BRICK_ACTIVITY = 121;</code>
     */
    public static final int ABILITY_MIXIN_ERASE_BRICK_ACTIVITY_VALUE = 121;
    /**
     * <code>ABILITY_MIXIN_BREAKOUT = 122;</code>
     */
    public static final int ABILITY_MIXIN_BREAKOUT_VALUE = 122;
    /**
     * <code>ABILITY_MIXIN_DAMAGE_LOAN = 123;</code>
     */
    public static final int ABILITY_MIXIN_DAMAGE_LOAN_VALUE = 123;
    /**
     * <code>ABILITY_MIXIN_BROADCAST_GV = 124;</code>
     */
    public static final int ABILITY_MIXIN_BROADCAST_GV_VALUE = 124;
    /**
     * <code>ABILITY_MIXIN_RECEIVE_GV = 125;</code>
     */
    public static final int ABILITY_MIXIN_RECEIVE_GV_VALUE = 125;
    /**
     * <code>ABILITY_MIXIN_RAYCAST_SELECT_TARGET = 126;</code>
     */
    public static final int ABILITY_MIXIN_RAYCAST_SELECT_TARGET_VALUE = 126;
    /**
     * <code>ABILITY_MIXIN_ENERGY_CRYSTAL_TARGET = 127;</code>
     */
    public static final int ABILITY_MIXIN_ENERGY_CRYSTAL_TARGET_VALUE = 127;
    /**
     * <code>ABILITY_MIXIN_ROTATION_FOLLOW_CAMERA = 128;</code>
     */
    public static final int ABILITY_MIXIN_ROTATION_FOLLOW_CAMERA_VALUE = 128;
    /**
     * <code>ABILITY_MIXIN_BUOYANT_FORCE = 129;</code>
     */
    public static final int ABILITY_MIXIN_BUOYANT_FORCE_VALUE = 129;
    /**
     * <code>ABILITY_MIXIN_FILMFEST_BALL_GAME = 130;</code>
     */
    public static final int ABILITY_MIXIN_FILMFEST_BALL_GAME_VALUE = 130;
    /**
     * <code>ABILITY_MIXIN_CHECK_SCAN_ENTITY = 131;</code>
     */
    public static final int ABILITY_MIXIN_CHECK_SCAN_ENTITY_VALUE = 131;
    /**
     * <code>ABILITY_MIXIN_TIME_TRACK_PLAYER = 133;</code>
     */
    public static final int ABILITY_MIXIN_TIME_TRACK_PLAYER_VALUE = 133;
    /**
     * <code>ABILITY_MIXIN_PART_FOLLOW = 134;</code>
     */
    public static final int ABILITY_MIXIN_PART_FOLLOW_VALUE = 134;
    /**
     * <code>ABILITY_MIXIN_CHANGE_PHLOGISTON = 135;</code>
     */
    public static final int ABILITY_MIXIN_CHANGE_PHLOGISTON_VALUE = 135;
    /**
     * <code>ABILITY_MIXIN_HUMAN_DRAGON_COLLAB_PICK_PHLOGISTON_BALL = 136;</code>
     */
    public static final int ABILITY_MIXIN_HUMAN_DRAGON_COLLAB_PICK_PHLOGISTON_BALL_VALUE = 136;
    /**
     * <code>ABILITY_MIXIN_FREQUENCY_SHIELD_BAR = 137;</code>
     */
    public static final int ABILITY_MIXIN_FREQUENCY_SHIELD_BAR_VALUE = 137;
    /**
     * <code>ABILITY_MIXIN_VEHICLE_STEER_BY_CAMERA = 141;</code>
     */
    public static final int ABILITY_MIXIN_VEHICLE_STEER_BY_CAMERA_VALUE = 141;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AbilityInvokeArgument valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AbilityInvokeArgument forNumber(int value) {
      switch (value) {
        case 0: return ABILITY_NONE;
        case 1: return ABILITY_META_MODIFIER_CHANGE;
        case 2: return ABILITY_META_COMMAND_MODIFIER_CHANGE_REQUEST;
        case 3: return ABILITY_META_SPECIAL_FLOAT_ARGUMENT;
        case 4: return ABILITY_META_OVERRIDE_PARAM;
        case 5: return ABILITY_META_CLEAR_OVERRIDE_PARAM;
        case 6: return ABILITY_META_REINIT_OVERRIDEMAP;
        case 7: return ABILITY_META_GLOBAL_FLOAT_VALUE;
        case 8: return ABILITY_META_CLEAR_GLOBAL_FLOAT_VALUE;
        case 9: return ABILITY_META_ABILITY_ELEMENT_STRENGTH;
        case 10: return ABILITY_META_ADD_OR_GET_ABILITY_AND_TRIGGER;
        case 11: return ABILITY_META_SET_KILLED_SETATE;
        case 12: return ABILITY_META_SET_ABILITY_TRIGGER;
        case 13: return ABILITY_META_ADD_NEW_ABILITY;
        case 14: return ABILITY_META_REMOVE_ABILITY;
        case 15: return ABILITY_META_SET_MODIFIER_APPLY_ENTITY;
        case 16: return ABILITY_META_MODIFIER_DURABILITY_CHANGE;
        case 17: return ABILITY_META_ELEMENT_REACTION_VISUAL;
        case 18: return ABILITY_META_SET_POSE_PARAMETER;
        case 19: return ABILITY_META_UPDATE_BASE_REACTION_DAMAGE;
        case 20: return ABILITY_META_TRIGGER_ELEMENT_REACTION;
        case 21: return ABILITY_META_LOSE_HP;
        case 22: return ABILITY_META_DURABILITY_IS_ZERO;
        case 23: return ABILITY_META_TRIGGER_ARKHE_REACTION;
        case 24: return ABILITY_META_CHANGE_NYX_VALUE;
        case 50: return ABILITY_ACTION_TRIGGER_ABILITY;
        case 51: return ABILITY_ACTION_SET_CRASH_DAMAGE;
        case 52: return ABILITY_ACTION_EFFECT;
        case 53: return ABILITY_ACTION_SUMMON;
        case 54: return ABILITY_ACTION_BLINK;
        case 55: return ABILITY_ACTION_CREATE_GADGET;
        case 56: return ABILITY_ACTION_APPLY_LEVEL_MODIFIER;
        case 57: return ABILITY_ACTION_GENERATE_ELEM_BALL;
        case 58: return ABILITY_ACTION_SET_RANDOM_OVERRIDE_MAP_VALUE;
        case 59: return ABILITY_ACTION_SERVER_MONSTER_LOG;
        case 60: return ABILITY_ACTION_CREATE_TILE;
        case 61: return ABILITY_ACTION_DESTROY_TILE;
        case 62: return ABILITY_ACTION_FIRE_AFTER_IMAGE;
        case 63: return ABILITY_ACTION_DEDUCT_STAMINA;
        case 64: return ABILITY_ACTION_HIT_EFFECT;
        case 65: return ABILITY_ACTION_SET_BULLET_TRACK_TARGET;
        case 66: return ABILITY_ACTION_FIREWORK_EFFECT;
        case 67: return ABILITY_ACTION_LEVEL_BANK_ADD_STUFF;
        case 68: return ABILITY_ACTION_GET_MATERIAL_PARAM_FLOAT;
        case 69: return ABILITY_ACTION_GET_MATERIAL_PARAM_VECTOR;
        case 70: return ABILITY_ACTION_SPECTACLE_BUILD_RECREATE_GADGET;
        case 100: return ABILITY_MIXIN_AVATAR_STEER_BY_CAMERA;
        case 101: return ABILITY_MIXIN_MONSTER_DEFEND;
        case 102: return ABILITY_MIXIN_WIND_ZONE;
        case 103: return ABILITY_MIXIN_COST_STAMINA;
        case 104: return ABILITY_MIXIN_ELITE_SHIELD;
        case 105: return ABILITY_MIXIN_ELEMENT_SHIELD;
        case 106: return ABILITY_MIXIN_GLOBAL_SHIELD;
        case 107: return ABILITY_MIXIN_SHIELD_BAR;
        case 108: return ABILITY_MIXIN_WIND_SEED_SPAWNER;
        case 109: return ABILITY_MIXIN_DO_ACTION_BY_ELEMENT_REACTION;
        case 110: return ABILITY_MIXIN_FIELD_ENTITY_COUNT_CHANGE;
        case 111: return ABILITY_MIXIN_SCENE_PROP_SYNC;
        case 112: return ABILITY_MIXIN_WIDGET_MP_SUPPORT;
        case 113: return ABILITY_MIXIN_DO_ACTION_BY_SELF_MODIFIER_ELEMENT_DURABILITY_RATIO;
        case 114: return ABILITY_MIXIN_FIREWORKS_LAUNCHER;
        case 115: return ABILITY_MIXIN_ATTACK_RESULT_CREATE_COUNT;
        case 116: return ABILITY_MIXIN_UGC_TIME_CONTROL;
        case 117: return ABILITY_MIXIN_AVATAR_COMBAT;
        case 118: return ABILITY_MIXIN_DEATH_ZONE_REGIONAL_PLAY_MIXIN;
        case 119: return ABILITY_MIXIN_UI_INTERACT;
        case 120: return ABILITY_MIXIN_SHOOT_FROM_CAMERA;
        case 121: return ABILITY_MIXIN_ERASE_BRICK_ACTIVITY;
        case 122: return ABILITY_MIXIN_BREAKOUT;
        case 123: return ABILITY_MIXIN_DAMAGE_LOAN;
        case 124: return ABILITY_MIXIN_BROADCAST_GV;
        case 125: return ABILITY_MIXIN_RECEIVE_GV;
        case 126: return ABILITY_MIXIN_RAYCAST_SELECT_TARGET;
        case 127: return ABILITY_MIXIN_ENERGY_CRYSTAL_TARGET;
        case 128: return ABILITY_MIXIN_ROTATION_FOLLOW_CAMERA;
        case 129: return ABILITY_MIXIN_BUOYANT_FORCE;
        case 130: return ABILITY_MIXIN_FILMFEST_BALL_GAME;
        case 131: return ABILITY_MIXIN_CHECK_SCAN_ENTITY;
        case 133: return ABILITY_MIXIN_TIME_TRACK_PLAYER;
        case 134: return ABILITY_MIXIN_PART_FOLLOW;
        case 135: return ABILITY_MIXIN_CHANGE_PHLOGISTON;
        case 136: return ABILITY_MIXIN_HUMAN_DRAGON_COLLAB_PICK_PHLOGISTON_BALL;
        case 137: return ABILITY_MIXIN_FREQUENCY_SHIELD_BAR;
        case 141: return ABILITY_MIXIN_VEHICLE_STEER_BY_CAMERA;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AbilityInvokeArgument>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AbilityInvokeArgument> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AbilityInvokeArgument>() {
            public AbilityInvokeArgument findValueByNumber(int number) {
              return AbilityInvokeArgument.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return emu.grasscutter.net.proto.AbilityInvokeArgumentOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final AbilityInvokeArgument[] VALUES = values();

    public static AbilityInvokeArgument valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AbilityInvokeArgument(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:AbilityInvokeArgument)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033AbilityInvokeArgument.proto*\242\031\n\025Abilit" +
      "yInvokeArgument\022\020\n\014ABILITY_NONE\020\000\022 \n\034ABI" +
      "LITY_META_MODIFIER_CHANGE\020\001\0220\n,ABILITY_M" +
      "ETA_COMMAND_MODIFIER_CHANGE_REQUEST\020\002\022\'\n" +
      "#ABILITY_META_SPECIAL_FLOAT_ARGUMENT\020\003\022\037" +
      "\n\033ABILITY_META_OVERRIDE_PARAM\020\004\022%\n!ABILI" +
      "TY_META_CLEAR_OVERRIDE_PARAM\020\005\022#\n\037ABILIT" +
      "Y_META_REINIT_OVERRIDEMAP\020\006\022#\n\037ABILITY_M" +
      "ETA_GLOBAL_FLOAT_VALUE\020\007\022)\n%ABILITY_META" +
      "_CLEAR_GLOBAL_FLOAT_VALUE\020\010\022)\n%ABILITY_M" +
      "ETA_ABILITY_ELEMENT_STRENGTH\020\t\022/\n+ABILIT" +
      "Y_META_ADD_OR_GET_ABILITY_AND_TRIGGER\020\n\022" +
      "\"\n\036ABILITY_META_SET_KILLED_SETATE\020\013\022$\n A" +
      "BILITY_META_SET_ABILITY_TRIGGER\020\014\022 \n\034ABI" +
      "LITY_META_ADD_NEW_ABILITY\020\r\022\037\n\033ABILITY_M" +
      "ETA_REMOVE_ABILITY\020\016\022*\n&ABILITY_META_SET" +
      "_MODIFIER_APPLY_ENTITY\020\017\022+\n\'ABILITY_META" +
      "_MODIFIER_DURABILITY_CHANGE\020\020\022(\n$ABILITY" +
      "_META_ELEMENT_REACTION_VISUAL\020\021\022#\n\037ABILI" +
      "TY_META_SET_POSE_PARAMETER\020\022\022,\n(ABILITY_" +
      "META_UPDATE_BASE_REACTION_DAMAGE\020\023\022)\n%AB" +
      "ILITY_META_TRIGGER_ELEMENT_REACTION\020\024\022\030\n" +
      "\024ABILITY_META_LOSE_HP\020\025\022#\n\037ABILITY_META_" +
      "DURABILITY_IS_ZERO\020\026\022\'\n#ABILITY_META_TRI" +
      "GGER_ARKHE_REACTION\020\027\022!\n\035ABILITY_META_CH" +
      "ANGE_NYX_VALUE\020\030\022\"\n\036ABILITY_ACTION_TRIGG" +
      "ER_ABILITY\0202\022#\n\037ABILITY_ACTION_SET_CRASH" +
      "_DAMAGE\0203\022\031\n\025ABILITY_ACTION_EFFECT\0204\022\031\n\025" +
      "ABILITY_ACTION_SUMMON\0205\022\030\n\024ABILITY_ACTIO" +
      "N_BLINK\0206\022 \n\034ABILITY_ACTION_CREATE_GADGE" +
      "T\0207\022\'\n#ABILITY_ACTION_APPLY_LEVEL_MODIFI" +
      "ER\0208\022%\n!ABILITY_ACTION_GENERATE_ELEM_BAL" +
      "L\0209\0220\n,ABILITY_ACTION_SET_RANDOM_OVERRID" +
      "E_MAP_VALUE\020:\022%\n!ABILITY_ACTION_SERVER_M" +
      "ONSTER_LOG\020;\022\036\n\032ABILITY_ACTION_CREATE_TI" +
      "LE\020<\022\037\n\033ABILITY_ACTION_DESTROY_TILE\020=\022#\n" +
      "\037ABILITY_ACTION_FIRE_AFTER_IMAGE\020>\022!\n\035AB" +
      "ILITY_ACTION_DEDUCT_STAMINA\020?\022\035\n\031ABILITY" +
      "_ACTION_HIT_EFFECT\020@\022*\n&ABILITY_ACTION_S" +
      "ET_BULLET_TRACK_TARGET\020A\022\"\n\036ABILITY_ACTI" +
      "ON_FIREWORK_EFFECT\020B\022\'\n#ABILITY_ACTION_L" +
      "EVEL_BANK_ADD_STUFF\020C\022+\n\'ABILITY_ACTION_" +
      "GET_MATERIAL_PARAM_FLOAT\020D\022,\n(ABILITY_AC" +
      "TION_GET_MATERIAL_PARAM_VECTOR\020E\0222\n.ABIL" +
      "ITY_ACTION_SPECTACLE_BUILD_RECREATE_GADG" +
      "ET\020F\022(\n$ABILITY_MIXIN_AVATAR_STEER_BY_CA" +
      "MERA\020d\022 \n\034ABILITY_MIXIN_MONSTER_DEFEND\020e" +
      "\022\033\n\027ABILITY_MIXIN_WIND_ZONE\020f\022\036\n\032ABILITY" +
      "_MIXIN_COST_STAMINA\020g\022\036\n\032ABILITY_MIXIN_E" +
      "LITE_SHIELD\020h\022 \n\034ABILITY_MIXIN_ELEMENT_S" +
      "HIELD\020i\022\037\n\033ABILITY_MIXIN_GLOBAL_SHIELD\020j" +
      "\022\034\n\030ABILITY_MIXIN_SHIELD_BAR\020k\022#\n\037ABILIT" +
      "Y_MIXIN_WIND_SEED_SPAWNER\020l\022/\n+ABILITY_M" +
      "IXIN_DO_ACTION_BY_ELEMENT_REACTION\020m\022+\n\'" +
      "ABILITY_MIXIN_FIELD_ENTITY_COUNT_CHANGE\020" +
      "n\022!\n\035ABILITY_MIXIN_SCENE_PROP_SYNC\020o\022#\n\037" +
      "ABILITY_MIXIN_WIDGET_MP_SUPPORT\020p\022E\nAABI" +
      "LITY_MIXIN_DO_ACTION_BY_SELF_MODIFIER_EL" +
      "EMENT_DURABILITY_RATIO\020q\022$\n ABILITY_MIXI" +
      "N_FIREWORKS_LAUNCHER\020r\022,\n(ABILITY_MIXIN_" +
      "ATTACK_RESULT_CREATE_COUNT\020s\022\"\n\036ABILITY_" +
      "MIXIN_UGC_TIME_CONTROL\020t\022\037\n\033ABILITY_MIXI" +
      "N_AVATAR_COMBAT\020u\0220\n,ABILITY_MIXIN_DEATH" +
      "_ZONE_REGIONAL_PLAY_MIXIN\020v\022\035\n\031ABILITY_M" +
      "IXIN_UI_INTERACT\020w\022#\n\037ABILITY_MIXIN_SHOO" +
      "T_FROM_CAMERA\020x\022&\n\"ABILITY_MIXIN_ERASE_B" +
      "RICK_ACTIVITY\020y\022\032\n\026ABILITY_MIXIN_BREAKOU" +
      "T\020z\022\035\n\031ABILITY_MIXIN_DAMAGE_LOAN\020{\022\036\n\032AB" +
      "ILITY_MIXIN_BROADCAST_GV\020|\022\034\n\030ABILITY_MI" +
      "XIN_RECEIVE_GV\020}\022\'\n#ABILITY_MIXIN_RAYCAS" +
      "T_SELECT_TARGET\020~\022\'\n#ABILITY_MIXIN_ENERG" +
      "Y_CRYSTAL_TARGET\020\177\022)\n$ABILITY_MIXIN_ROTA" +
      "TION_FOLLOW_CAMERA\020\200\001\022 \n\033ABILITY_MIXIN_B" +
      "UOYANT_FORCE\020\201\001\022%\n ABILITY_MIXIN_FILMFES" +
      "T_BALL_GAME\020\202\001\022$\n\037ABILITY_MIXIN_CHECK_SC" +
      "AN_ENTITY\020\203\001\022$\n\037ABILITY_MIXIN_TIME_TRACK" +
      "_PLAYER\020\205\001\022\036\n\031ABILITY_MIXIN_PART_FOLLOW\020" +
      "\206\001\022$\n\037ABILITY_MIXIN_CHANGE_PHLOGISTON\020\207\001" +
      "\022;\n6ABILITY_MIXIN_HUMAN_DRAGON_COLLAB_PI" +
      "CK_PHLOGISTON_BALL\020\210\001\022\'\n\"ABILITY_MIXIN_F" +
      "REQUENCY_SHIELD_BAR\020\211\001\022*\n%ABILITY_MIXIN_" +
      "VEHICLE_STEER_BY_CAMERA\020\215\001B\033\n\031emu.grassc" +
      "utter.net.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
