// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AvatarAddNotify.proto

package emu.grasscutter.net.proto;

public final class AvatarAddNotifyOuterClass {
  private AvatarAddNotifyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AvatarAddNotifyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AvatarAddNotify)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool is_in_team = 3;</code>
     * @return The isInTeam.
     */
    boolean getIsInTeam();

    /**
     * <code>.AvatarInfo avatar = 12;</code>
     * @return Whether the avatar field is set.
     */
    boolean hasAvatar();
    /**
     * <code>.AvatarInfo avatar = 12;</code>
     * @return The avatar.
     */
    AvatarInfoOuterClass.AvatarInfo getAvatar();
    /**
     * <code>.AvatarInfo avatar = 12;</code>
     */
    AvatarInfoOuterClass.AvatarInfoOrBuilder getAvatarOrBuilder();
  }
  /**
   * <pre>
   * CmdId: 4216
   * 5.0.0
   * obf: NCLFINCCBGF
   * </pre>
   *
   * Protobuf type {@code AvatarAddNotify}
   */
  public static final class AvatarAddNotify extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AvatarAddNotify)
      AvatarAddNotifyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AvatarAddNotify.newBuilder() to construct.
    private AvatarAddNotify(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AvatarAddNotify() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new AvatarAddNotify();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AvatarAddNotify(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 24: {

              isInTeam_ = input.readBool();
              break;
            }
            case 98: {
              AvatarInfoOuterClass.AvatarInfo.Builder subBuilder = null;
              if (avatar_ != null) {
                subBuilder = avatar_.toBuilder();
              }
              avatar_ = input.readMessage(AvatarInfoOuterClass.AvatarInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(avatar_);
                avatar_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AvatarAddNotifyOuterClass.internal_static_AvatarAddNotify_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AvatarAddNotifyOuterClass.internal_static_AvatarAddNotify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AvatarAddNotify.class, Builder.class);
    }

    public static final int IS_IN_TEAM_FIELD_NUMBER = 3;
    private boolean isInTeam_;
    /**
     * <code>bool is_in_team = 3;</code>
     * @return The isInTeam.
     */
    @Override
    public boolean getIsInTeam() {
      return isInTeam_;
    }

    public static final int AVATAR_FIELD_NUMBER = 12;
    private AvatarInfoOuterClass.AvatarInfo avatar_;
    /**
     * <code>.AvatarInfo avatar = 12;</code>
     * @return Whether the avatar field is set.
     */
    @Override
    public boolean hasAvatar() {
      return avatar_ != null;
    }
    /**
     * <code>.AvatarInfo avatar = 12;</code>
     * @return The avatar.
     */
    @Override
    public AvatarInfoOuterClass.AvatarInfo getAvatar() {
      return avatar_ == null ? AvatarInfoOuterClass.AvatarInfo.getDefaultInstance() : avatar_;
    }
    /**
     * <code>.AvatarInfo avatar = 12;</code>
     */
    @Override
    public AvatarInfoOuterClass.AvatarInfoOrBuilder getAvatarOrBuilder() {
      return getAvatar();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (isInTeam_ != false) {
        output.writeBool(3, isInTeam_);
      }
      if (avatar_ != null) {
        output.writeMessage(12, getAvatar());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (isInTeam_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isInTeam_);
      }
      if (avatar_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, getAvatar());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AvatarAddNotify)) {
        return super.equals(obj);
      }
      AvatarAddNotify other = (AvatarAddNotify) obj;

      if (getIsInTeam()
          != other.getIsInTeam()) return false;
      if (hasAvatar() != other.hasAvatar()) return false;
      if (hasAvatar()) {
        if (!getAvatar()
            .equals(other.getAvatar())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IS_IN_TEAM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsInTeam());
      if (hasAvatar()) {
        hash = (37 * hash) + AVATAR_FIELD_NUMBER;
        hash = (53 * hash) + getAvatar().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AvatarAddNotify parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AvatarAddNotify parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AvatarAddNotify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AvatarAddNotify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AvatarAddNotify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AvatarAddNotify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AvatarAddNotify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AvatarAddNotify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AvatarAddNotify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AvatarAddNotify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AvatarAddNotify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AvatarAddNotify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AvatarAddNotify prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * CmdId: 4216
     * 5.0.0
     * obf: NCLFINCCBGF
     * </pre>
     *
     * Protobuf type {@code AvatarAddNotify}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AvatarAddNotify)
        AvatarAddNotifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AvatarAddNotifyOuterClass.internal_static_AvatarAddNotify_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AvatarAddNotifyOuterClass.internal_static_AvatarAddNotify_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AvatarAddNotify.class, Builder.class);
      }

      // Construct using emu.grasscutter.net.proto.AvatarAddNotifyOuterClass.AvatarAddNotify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        isInTeam_ = false;

        if (avatarBuilder_ == null) {
          avatar_ = null;
        } else {
          avatar_ = null;
          avatarBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AvatarAddNotifyOuterClass.internal_static_AvatarAddNotify_descriptor;
      }

      @Override
      public AvatarAddNotify getDefaultInstanceForType() {
        return AvatarAddNotify.getDefaultInstance();
      }

      @Override
      public AvatarAddNotify build() {
        AvatarAddNotify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public AvatarAddNotify buildPartial() {
        AvatarAddNotify result = new AvatarAddNotify(this);
        result.isInTeam_ = isInTeam_;
        if (avatarBuilder_ == null) {
          result.avatar_ = avatar_;
        } else {
          result.avatar_ = avatarBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AvatarAddNotify) {
          return mergeFrom((AvatarAddNotify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AvatarAddNotify other) {
        if (other == AvatarAddNotify.getDefaultInstance()) return this;
        if (other.getIsInTeam() != false) {
          setIsInTeam(other.getIsInTeam());
        }
        if (other.hasAvatar()) {
          mergeAvatar(other.getAvatar());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AvatarAddNotify parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AvatarAddNotify) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean isInTeam_ ;
      /**
       * <code>bool is_in_team = 3;</code>
       * @return The isInTeam.
       */
      @Override
      public boolean getIsInTeam() {
        return isInTeam_;
      }
      /**
       * <code>bool is_in_team = 3;</code>
       * @param value The isInTeam to set.
       * @return This builder for chaining.
       */
      public Builder setIsInTeam(boolean value) {

        isInTeam_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_in_team = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsInTeam() {

        isInTeam_ = false;
        onChanged();
        return this;
      }

      private AvatarInfoOuterClass.AvatarInfo avatar_;
      private com.google.protobuf.SingleFieldBuilderV3<
          AvatarInfoOuterClass.AvatarInfo, AvatarInfoOuterClass.AvatarInfo.Builder, AvatarInfoOuterClass.AvatarInfoOrBuilder> avatarBuilder_;
      /**
       * <code>.AvatarInfo avatar = 12;</code>
       * @return Whether the avatar field is set.
       */
      public boolean hasAvatar() {
        return avatarBuilder_ != null || avatar_ != null;
      }
      /**
       * <code>.AvatarInfo avatar = 12;</code>
       * @return The avatar.
       */
      public AvatarInfoOuterClass.AvatarInfo getAvatar() {
        if (avatarBuilder_ == null) {
          return avatar_ == null ? AvatarInfoOuterClass.AvatarInfo.getDefaultInstance() : avatar_;
        } else {
          return avatarBuilder_.getMessage();
        }
      }
      /**
       * <code>.AvatarInfo avatar = 12;</code>
       */
      public Builder setAvatar(AvatarInfoOuterClass.AvatarInfo value) {
        if (avatarBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          avatar_ = value;
          onChanged();
        } else {
          avatarBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.AvatarInfo avatar = 12;</code>
       */
      public Builder setAvatar(
          AvatarInfoOuterClass.AvatarInfo.Builder builderForValue) {
        if (avatarBuilder_ == null) {
          avatar_ = builderForValue.build();
          onChanged();
        } else {
          avatarBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.AvatarInfo avatar = 12;</code>
       */
      public Builder mergeAvatar(AvatarInfoOuterClass.AvatarInfo value) {
        if (avatarBuilder_ == null) {
          if (avatar_ != null) {
            avatar_ =
              AvatarInfoOuterClass.AvatarInfo.newBuilder(avatar_).mergeFrom(value).buildPartial();
          } else {
            avatar_ = value;
          }
          onChanged();
        } else {
          avatarBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.AvatarInfo avatar = 12;</code>
       */
      public Builder clearAvatar() {
        if (avatarBuilder_ == null) {
          avatar_ = null;
          onChanged();
        } else {
          avatar_ = null;
          avatarBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.AvatarInfo avatar = 12;</code>
       */
      public AvatarInfoOuterClass.AvatarInfo.Builder getAvatarBuilder() {

        onChanged();
        return getAvatarFieldBuilder().getBuilder();
      }
      /**
       * <code>.AvatarInfo avatar = 12;</code>
       */
      public AvatarInfoOuterClass.AvatarInfoOrBuilder getAvatarOrBuilder() {
        if (avatarBuilder_ != null) {
          return avatarBuilder_.getMessageOrBuilder();
        } else {
          return avatar_ == null ?
              AvatarInfoOuterClass.AvatarInfo.getDefaultInstance() : avatar_;
        }
      }
      /**
       * <code>.AvatarInfo avatar = 12;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          AvatarInfoOuterClass.AvatarInfo, AvatarInfoOuterClass.AvatarInfo.Builder, AvatarInfoOuterClass.AvatarInfoOrBuilder>
          getAvatarFieldBuilder() {
        if (avatarBuilder_ == null) {
          avatarBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              AvatarInfoOuterClass.AvatarInfo, AvatarInfoOuterClass.AvatarInfo.Builder, AvatarInfoOuterClass.AvatarInfoOrBuilder>(
                  getAvatar(),
                  getParentForChildren(),
                  isClean());
          avatar_ = null;
        }
        return avatarBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AvatarAddNotify)
    }

    // @@protoc_insertion_point(class_scope:AvatarAddNotify)
    private static final AvatarAddNotify DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AvatarAddNotify();
    }

    public static AvatarAddNotify getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AvatarAddNotify>
        PARSER = new com.google.protobuf.AbstractParser<AvatarAddNotify>() {
      @Override
      public AvatarAddNotify parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AvatarAddNotify(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AvatarAddNotify> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AvatarAddNotify> getParserForType() {
      return PARSER;
    }

    @Override
    public AvatarAddNotify getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AvatarAddNotify_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AvatarAddNotify_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025AvatarAddNotify.proto\032\020AvatarInfo.prot" +
      "o\"B\n\017AvatarAddNotify\022\022\n\nis_in_team\030\003 \001(\010" +
      "\022\033\n\006avatar\030\014 \001(\0132\013.AvatarInfoB\033\n\031emu.gra" +
      "sscutter.net.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          AvatarInfoOuterClass.getDescriptor(),
        });
    internal_static_AvatarAddNotify_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AvatarAddNotify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AvatarAddNotify_descriptor,
        new String[] { "IsInTeam", "Avatar", });
    AvatarInfoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
