// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BladeDanceSettleInfo.proto

package emu.grasscutter.net.proto;

public final class BladeDanceSettleInfoOuterClass {
  private BladeDanceSettleInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BladeDanceSettleInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BladeDanceSettleInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 JOFBEIACLOF = 2;</code>
     * @return The jOFBEIACLOF.
     */
    int getJOFBEIACLOF();

    /**
     * <code>uint32 APAFIPOFLOJ = 7;</code>
     * @return The aPAFIPOFLOJ.
     */
    int getAPAFIPOFLOJ();

    /**
     * <code>bool is_new_record = 10;</code>
     * @return The isNewRecord.
     */
    boolean getIsNewRecord();

    /**
     * <code>uint32 PJJAOILBFBN = 15;</code>
     * @return The pJJAOILBFBN.
     */
    int getPJJAOILBFBN();
  }
  /**
   * Protobuf type {@code BladeDanceSettleInfo}
   */
  public static final class BladeDanceSettleInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BladeDanceSettleInfo)
      BladeDanceSettleInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BladeDanceSettleInfo.newBuilder() to construct.
    private BladeDanceSettleInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BladeDanceSettleInfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BladeDanceSettleInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BladeDanceSettleInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 16: {

              jOFBEIACLOF_ = input.readUInt32();
              break;
            }
            case 56: {

              aPAFIPOFLOJ_ = input.readUInt32();
              break;
            }
            case 80: {

              isNewRecord_ = input.readBool();
              break;
            }
            case 120: {

              pJJAOILBFBN_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.internal_static_BladeDanceSettleInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.internal_static_BladeDanceSettleInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo.class, emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo.Builder.class);
    }

    public static final int JOFBEIACLOF_FIELD_NUMBER = 2;
    private int jOFBEIACLOF_;
    /**
     * <code>uint32 JOFBEIACLOF = 2;</code>
     * @return The jOFBEIACLOF.
     */
    @java.lang.Override
    public int getJOFBEIACLOF() {
      return jOFBEIACLOF_;
    }

    public static final int APAFIPOFLOJ_FIELD_NUMBER = 7;
    private int aPAFIPOFLOJ_;
    /**
     * <code>uint32 APAFIPOFLOJ = 7;</code>
     * @return The aPAFIPOFLOJ.
     */
    @java.lang.Override
    public int getAPAFIPOFLOJ() {
      return aPAFIPOFLOJ_;
    }

    public static final int IS_NEW_RECORD_FIELD_NUMBER = 10;
    private boolean isNewRecord_;
    /**
     * <code>bool is_new_record = 10;</code>
     * @return The isNewRecord.
     */
    @java.lang.Override
    public boolean getIsNewRecord() {
      return isNewRecord_;
    }

    public static final int PJJAOILBFBN_FIELD_NUMBER = 15;
    private int pJJAOILBFBN_;
    /**
     * <code>uint32 PJJAOILBFBN = 15;</code>
     * @return The pJJAOILBFBN.
     */
    @java.lang.Override
    public int getPJJAOILBFBN() {
      return pJJAOILBFBN_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (jOFBEIACLOF_ != 0) {
        output.writeUInt32(2, jOFBEIACLOF_);
      }
      if (aPAFIPOFLOJ_ != 0) {
        output.writeUInt32(7, aPAFIPOFLOJ_);
      }
      if (isNewRecord_ != false) {
        output.writeBool(10, isNewRecord_);
      }
      if (pJJAOILBFBN_ != 0) {
        output.writeUInt32(15, pJJAOILBFBN_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (jOFBEIACLOF_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, jOFBEIACLOF_);
      }
      if (aPAFIPOFLOJ_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, aPAFIPOFLOJ_);
      }
      if (isNewRecord_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, isNewRecord_);
      }
      if (pJJAOILBFBN_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(15, pJJAOILBFBN_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo)) {
        return super.equals(obj);
      }
      emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo other = (emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo) obj;

      if (getJOFBEIACLOF()
          != other.getJOFBEIACLOF()) return false;
      if (getAPAFIPOFLOJ()
          != other.getAPAFIPOFLOJ()) return false;
      if (getIsNewRecord()
          != other.getIsNewRecord()) return false;
      if (getPJJAOILBFBN()
          != other.getPJJAOILBFBN()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JOFBEIACLOF_FIELD_NUMBER;
      hash = (53 * hash) + getJOFBEIACLOF();
      hash = (37 * hash) + APAFIPOFLOJ_FIELD_NUMBER;
      hash = (53 * hash) + getAPAFIPOFLOJ();
      hash = (37 * hash) + IS_NEW_RECORD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsNewRecord());
      hash = (37 * hash) + PJJAOILBFBN_FIELD_NUMBER;
      hash = (53 * hash) + getPJJAOILBFBN();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BladeDanceSettleInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BladeDanceSettleInfo)
        emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.internal_static_BladeDanceSettleInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.internal_static_BladeDanceSettleInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo.class, emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo.Builder.class);
      }

      // Construct using emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        jOFBEIACLOF_ = 0;

        aPAFIPOFLOJ_ = 0;

        isNewRecord_ = false;

        pJJAOILBFBN_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.internal_static_BladeDanceSettleInfo_descriptor;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo getDefaultInstanceForType() {
        return emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo.getDefaultInstance();
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo build() {
        emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo buildPartial() {
        emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo result = new emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo(this);
        result.jOFBEIACLOF_ = jOFBEIACLOF_;
        result.aPAFIPOFLOJ_ = aPAFIPOFLOJ_;
        result.isNewRecord_ = isNewRecord_;
        result.pJJAOILBFBN_ = pJJAOILBFBN_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo) {
          return mergeFrom((emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo other) {
        if (other == emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo.getDefaultInstance()) return this;
        if (other.getJOFBEIACLOF() != 0) {
          setJOFBEIACLOF(other.getJOFBEIACLOF());
        }
        if (other.getAPAFIPOFLOJ() != 0) {
          setAPAFIPOFLOJ(other.getAPAFIPOFLOJ());
        }
        if (other.getIsNewRecord() != false) {
          setIsNewRecord(other.getIsNewRecord());
        }
        if (other.getPJJAOILBFBN() != 0) {
          setPJJAOILBFBN(other.getPJJAOILBFBN());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int jOFBEIACLOF_ ;
      /**
       * <code>uint32 JOFBEIACLOF = 2;</code>
       * @return The jOFBEIACLOF.
       */
      @java.lang.Override
      public int getJOFBEIACLOF() {
        return jOFBEIACLOF_;
      }
      /**
       * <code>uint32 JOFBEIACLOF = 2;</code>
       * @param value The jOFBEIACLOF to set.
       * @return This builder for chaining.
       */
      public Builder setJOFBEIACLOF(int value) {
        
        jOFBEIACLOF_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 JOFBEIACLOF = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearJOFBEIACLOF() {
        
        jOFBEIACLOF_ = 0;
        onChanged();
        return this;
      }

      private int aPAFIPOFLOJ_ ;
      /**
       * <code>uint32 APAFIPOFLOJ = 7;</code>
       * @return The aPAFIPOFLOJ.
       */
      @java.lang.Override
      public int getAPAFIPOFLOJ() {
        return aPAFIPOFLOJ_;
      }
      /**
       * <code>uint32 APAFIPOFLOJ = 7;</code>
       * @param value The aPAFIPOFLOJ to set.
       * @return This builder for chaining.
       */
      public Builder setAPAFIPOFLOJ(int value) {
        
        aPAFIPOFLOJ_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 APAFIPOFLOJ = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAPAFIPOFLOJ() {
        
        aPAFIPOFLOJ_ = 0;
        onChanged();
        return this;
      }

      private boolean isNewRecord_ ;
      /**
       * <code>bool is_new_record = 10;</code>
       * @return The isNewRecord.
       */
      @java.lang.Override
      public boolean getIsNewRecord() {
        return isNewRecord_;
      }
      /**
       * <code>bool is_new_record = 10;</code>
       * @param value The isNewRecord to set.
       * @return This builder for chaining.
       */
      public Builder setIsNewRecord(boolean value) {
        
        isNewRecord_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_new_record = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsNewRecord() {
        
        isNewRecord_ = false;
        onChanged();
        return this;
      }

      private int pJJAOILBFBN_ ;
      /**
       * <code>uint32 PJJAOILBFBN = 15;</code>
       * @return The pJJAOILBFBN.
       */
      @java.lang.Override
      public int getPJJAOILBFBN() {
        return pJJAOILBFBN_;
      }
      /**
       * <code>uint32 PJJAOILBFBN = 15;</code>
       * @param value The pJJAOILBFBN to set.
       * @return This builder for chaining.
       */
      public Builder setPJJAOILBFBN(int value) {
        
        pJJAOILBFBN_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 PJJAOILBFBN = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearPJJAOILBFBN() {
        
        pJJAOILBFBN_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BladeDanceSettleInfo)
    }

    // @@protoc_insertion_point(class_scope:BladeDanceSettleInfo)
    private static final emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo();
    }

    public static emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BladeDanceSettleInfo>
        PARSER = new com.google.protobuf.AbstractParser<BladeDanceSettleInfo>() {
      @java.lang.Override
      public BladeDanceSettleInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BladeDanceSettleInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BladeDanceSettleInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BladeDanceSettleInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public emu.grasscutter.net.proto.BladeDanceSettleInfoOuterClass.BladeDanceSettleInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BladeDanceSettleInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BladeDanceSettleInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032BladeDanceSettleInfo.proto\"l\n\024BladeDan" +
      "ceSettleInfo\022\023\n\013JOFBEIACLOF\030\002 \001(\r\022\023\n\013APA" +
      "FIPOFLOJ\030\007 \001(\r\022\025\n\ris_new_record\030\n \001(\010\022\023\n" +
      "\013PJJAOILBFBN\030\017 \001(\rB\033\n\031emu.grasscutter.ne" +
      "t.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BladeDanceSettleInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BladeDanceSettleInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BladeDanceSettleInfo_descriptor,
        new java.lang.String[] { "JOFBEIACLOF", "APAFIPOFLOJ", "IsNewRecord", "PJJAOILBFBN", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
