// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CrystalLinkDungeonSettleInfo.proto

package emu.grasscutter.net.proto;

public final class CrystalLinkDungeonSettleInfoOuterClass {
  private CrystalLinkDungeonSettleInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CrystalLinkDungeonSettleInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CrystalLinkDungeonSettleInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 DFPNKFEKIIG = 2;</code>
     * @return The dFPNKFEKIIG.
     */
    int getDFPNKFEKIIG();

    /**
     * <code>uint32 ONHOJOBNAPM = 3;</code>
     * @return The oNHOJOBNAPM.
     */
    int getONHOJOBNAPM();

    /**
     * <code>uint32 DEOOCBAKMCJ = 5;</code>
     * @return The dEOOCBAKMCJ.
     */
    int getDEOOCBAKMCJ();

    /**
     * <code>bool DGCMIKFMKHP = 6;</code>
     * @return The dGCMIKFMKHP.
     */
    boolean getDGCMIKFMKHP();

    /**
     * <code>bool is_new_record = 8;</code>
     * @return The isNewRecord.
     */
    boolean getIsNewRecord();

    /**
     * <code>uint32 PJJAOILBFBN = 11;</code>
     * @return The pJJAOILBFBN.
     */
    int getPJJAOILBFBN();

    /**
     * <code>uint32 final_score = 15;</code>
     * @return The finalScore.
     */
    int getFinalScore();
  }
  /**
   * Protobuf type {@code CrystalLinkDungeonSettleInfo}
   */
  public static final class CrystalLinkDungeonSettleInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CrystalLinkDungeonSettleInfo)
      CrystalLinkDungeonSettleInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CrystalLinkDungeonSettleInfo.newBuilder() to construct.
    private CrystalLinkDungeonSettleInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CrystalLinkDungeonSettleInfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CrystalLinkDungeonSettleInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CrystalLinkDungeonSettleInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 16: {

              dFPNKFEKIIG_ = input.readUInt32();
              break;
            }
            case 24: {

              oNHOJOBNAPM_ = input.readUInt32();
              break;
            }
            case 40: {

              dEOOCBAKMCJ_ = input.readUInt32();
              break;
            }
            case 48: {

              dGCMIKFMKHP_ = input.readBool();
              break;
            }
            case 64: {

              isNewRecord_ = input.readBool();
              break;
            }
            case 88: {

              pJJAOILBFBN_ = input.readUInt32();
              break;
            }
            case 120: {

              finalScore_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.internal_static_CrystalLinkDungeonSettleInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.internal_static_CrystalLinkDungeonSettleInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo.class, emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo.Builder.class);
    }

    public static final int DFPNKFEKIIG_FIELD_NUMBER = 2;
    private int dFPNKFEKIIG_;
    /**
     * <code>uint32 DFPNKFEKIIG = 2;</code>
     * @return The dFPNKFEKIIG.
     */
    @java.lang.Override
    public int getDFPNKFEKIIG() {
      return dFPNKFEKIIG_;
    }

    public static final int ONHOJOBNAPM_FIELD_NUMBER = 3;
    private int oNHOJOBNAPM_;
    /**
     * <code>uint32 ONHOJOBNAPM = 3;</code>
     * @return The oNHOJOBNAPM.
     */
    @java.lang.Override
    public int getONHOJOBNAPM() {
      return oNHOJOBNAPM_;
    }

    public static final int DEOOCBAKMCJ_FIELD_NUMBER = 5;
    private int dEOOCBAKMCJ_;
    /**
     * <code>uint32 DEOOCBAKMCJ = 5;</code>
     * @return The dEOOCBAKMCJ.
     */
    @java.lang.Override
    public int getDEOOCBAKMCJ() {
      return dEOOCBAKMCJ_;
    }

    public static final int DGCMIKFMKHP_FIELD_NUMBER = 6;
    private boolean dGCMIKFMKHP_;
    /**
     * <code>bool DGCMIKFMKHP = 6;</code>
     * @return The dGCMIKFMKHP.
     */
    @java.lang.Override
    public boolean getDGCMIKFMKHP() {
      return dGCMIKFMKHP_;
    }

    public static final int IS_NEW_RECORD_FIELD_NUMBER = 8;
    private boolean isNewRecord_;
    /**
     * <code>bool is_new_record = 8;</code>
     * @return The isNewRecord.
     */
    @java.lang.Override
    public boolean getIsNewRecord() {
      return isNewRecord_;
    }

    public static final int PJJAOILBFBN_FIELD_NUMBER = 11;
    private int pJJAOILBFBN_;
    /**
     * <code>uint32 PJJAOILBFBN = 11;</code>
     * @return The pJJAOILBFBN.
     */
    @java.lang.Override
    public int getPJJAOILBFBN() {
      return pJJAOILBFBN_;
    }

    public static final int FINAL_SCORE_FIELD_NUMBER = 15;
    private int finalScore_;
    /**
     * <code>uint32 final_score = 15;</code>
     * @return The finalScore.
     */
    @java.lang.Override
    public int getFinalScore() {
      return finalScore_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dFPNKFEKIIG_ != 0) {
        output.writeUInt32(2, dFPNKFEKIIG_);
      }
      if (oNHOJOBNAPM_ != 0) {
        output.writeUInt32(3, oNHOJOBNAPM_);
      }
      if (dEOOCBAKMCJ_ != 0) {
        output.writeUInt32(5, dEOOCBAKMCJ_);
      }
      if (dGCMIKFMKHP_ != false) {
        output.writeBool(6, dGCMIKFMKHP_);
      }
      if (isNewRecord_ != false) {
        output.writeBool(8, isNewRecord_);
      }
      if (pJJAOILBFBN_ != 0) {
        output.writeUInt32(11, pJJAOILBFBN_);
      }
      if (finalScore_ != 0) {
        output.writeUInt32(15, finalScore_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dFPNKFEKIIG_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, dFPNKFEKIIG_);
      }
      if (oNHOJOBNAPM_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, oNHOJOBNAPM_);
      }
      if (dEOOCBAKMCJ_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, dEOOCBAKMCJ_);
      }
      if (dGCMIKFMKHP_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, dGCMIKFMKHP_);
      }
      if (isNewRecord_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, isNewRecord_);
      }
      if (pJJAOILBFBN_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(11, pJJAOILBFBN_);
      }
      if (finalScore_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(15, finalScore_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo)) {
        return super.equals(obj);
      }
      emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo other = (emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo) obj;

      if (getDFPNKFEKIIG()
          != other.getDFPNKFEKIIG()) return false;
      if (getONHOJOBNAPM()
          != other.getONHOJOBNAPM()) return false;
      if (getDEOOCBAKMCJ()
          != other.getDEOOCBAKMCJ()) return false;
      if (getDGCMIKFMKHP()
          != other.getDGCMIKFMKHP()) return false;
      if (getIsNewRecord()
          != other.getIsNewRecord()) return false;
      if (getPJJAOILBFBN()
          != other.getPJJAOILBFBN()) return false;
      if (getFinalScore()
          != other.getFinalScore()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DFPNKFEKIIG_FIELD_NUMBER;
      hash = (53 * hash) + getDFPNKFEKIIG();
      hash = (37 * hash) + ONHOJOBNAPM_FIELD_NUMBER;
      hash = (53 * hash) + getONHOJOBNAPM();
      hash = (37 * hash) + DEOOCBAKMCJ_FIELD_NUMBER;
      hash = (53 * hash) + getDEOOCBAKMCJ();
      hash = (37 * hash) + DGCMIKFMKHP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDGCMIKFMKHP());
      hash = (37 * hash) + IS_NEW_RECORD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsNewRecord());
      hash = (37 * hash) + PJJAOILBFBN_FIELD_NUMBER;
      hash = (53 * hash) + getPJJAOILBFBN();
      hash = (37 * hash) + FINAL_SCORE_FIELD_NUMBER;
      hash = (53 * hash) + getFinalScore();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CrystalLinkDungeonSettleInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CrystalLinkDungeonSettleInfo)
        emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.internal_static_CrystalLinkDungeonSettleInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.internal_static_CrystalLinkDungeonSettleInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo.class, emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo.Builder.class);
      }

      // Construct using emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dFPNKFEKIIG_ = 0;

        oNHOJOBNAPM_ = 0;

        dEOOCBAKMCJ_ = 0;

        dGCMIKFMKHP_ = false;

        isNewRecord_ = false;

        pJJAOILBFBN_ = 0;

        finalScore_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.internal_static_CrystalLinkDungeonSettleInfo_descriptor;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo getDefaultInstanceForType() {
        return emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo.getDefaultInstance();
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo build() {
        emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo buildPartial() {
        emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo result = new emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo(this);
        result.dFPNKFEKIIG_ = dFPNKFEKIIG_;
        result.oNHOJOBNAPM_ = oNHOJOBNAPM_;
        result.dEOOCBAKMCJ_ = dEOOCBAKMCJ_;
        result.dGCMIKFMKHP_ = dGCMIKFMKHP_;
        result.isNewRecord_ = isNewRecord_;
        result.pJJAOILBFBN_ = pJJAOILBFBN_;
        result.finalScore_ = finalScore_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo) {
          return mergeFrom((emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo other) {
        if (other == emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo.getDefaultInstance()) return this;
        if (other.getDFPNKFEKIIG() != 0) {
          setDFPNKFEKIIG(other.getDFPNKFEKIIG());
        }
        if (other.getONHOJOBNAPM() != 0) {
          setONHOJOBNAPM(other.getONHOJOBNAPM());
        }
        if (other.getDEOOCBAKMCJ() != 0) {
          setDEOOCBAKMCJ(other.getDEOOCBAKMCJ());
        }
        if (other.getDGCMIKFMKHP() != false) {
          setDGCMIKFMKHP(other.getDGCMIKFMKHP());
        }
        if (other.getIsNewRecord() != false) {
          setIsNewRecord(other.getIsNewRecord());
        }
        if (other.getPJJAOILBFBN() != 0) {
          setPJJAOILBFBN(other.getPJJAOILBFBN());
        }
        if (other.getFinalScore() != 0) {
          setFinalScore(other.getFinalScore());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int dFPNKFEKIIG_ ;
      /**
       * <code>uint32 DFPNKFEKIIG = 2;</code>
       * @return The dFPNKFEKIIG.
       */
      @java.lang.Override
      public int getDFPNKFEKIIG() {
        return dFPNKFEKIIG_;
      }
      /**
       * <code>uint32 DFPNKFEKIIG = 2;</code>
       * @param value The dFPNKFEKIIG to set.
       * @return This builder for chaining.
       */
      public Builder setDFPNKFEKIIG(int value) {
        
        dFPNKFEKIIG_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 DFPNKFEKIIG = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDFPNKFEKIIG() {
        
        dFPNKFEKIIG_ = 0;
        onChanged();
        return this;
      }

      private int oNHOJOBNAPM_ ;
      /**
       * <code>uint32 ONHOJOBNAPM = 3;</code>
       * @return The oNHOJOBNAPM.
       */
      @java.lang.Override
      public int getONHOJOBNAPM() {
        return oNHOJOBNAPM_;
      }
      /**
       * <code>uint32 ONHOJOBNAPM = 3;</code>
       * @param value The oNHOJOBNAPM to set.
       * @return This builder for chaining.
       */
      public Builder setONHOJOBNAPM(int value) {
        
        oNHOJOBNAPM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 ONHOJOBNAPM = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearONHOJOBNAPM() {
        
        oNHOJOBNAPM_ = 0;
        onChanged();
        return this;
      }

      private int dEOOCBAKMCJ_ ;
      /**
       * <code>uint32 DEOOCBAKMCJ = 5;</code>
       * @return The dEOOCBAKMCJ.
       */
      @java.lang.Override
      public int getDEOOCBAKMCJ() {
        return dEOOCBAKMCJ_;
      }
      /**
       * <code>uint32 DEOOCBAKMCJ = 5;</code>
       * @param value The dEOOCBAKMCJ to set.
       * @return This builder for chaining.
       */
      public Builder setDEOOCBAKMCJ(int value) {
        
        dEOOCBAKMCJ_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 DEOOCBAKMCJ = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDEOOCBAKMCJ() {
        
        dEOOCBAKMCJ_ = 0;
        onChanged();
        return this;
      }

      private boolean dGCMIKFMKHP_ ;
      /**
       * <code>bool DGCMIKFMKHP = 6;</code>
       * @return The dGCMIKFMKHP.
       */
      @java.lang.Override
      public boolean getDGCMIKFMKHP() {
        return dGCMIKFMKHP_;
      }
      /**
       * <code>bool DGCMIKFMKHP = 6;</code>
       * @param value The dGCMIKFMKHP to set.
       * @return This builder for chaining.
       */
      public Builder setDGCMIKFMKHP(boolean value) {
        
        dGCMIKFMKHP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool DGCMIKFMKHP = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDGCMIKFMKHP() {
        
        dGCMIKFMKHP_ = false;
        onChanged();
        return this;
      }

      private boolean isNewRecord_ ;
      /**
       * <code>bool is_new_record = 8;</code>
       * @return The isNewRecord.
       */
      @java.lang.Override
      public boolean getIsNewRecord() {
        return isNewRecord_;
      }
      /**
       * <code>bool is_new_record = 8;</code>
       * @param value The isNewRecord to set.
       * @return This builder for chaining.
       */
      public Builder setIsNewRecord(boolean value) {
        
        isNewRecord_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_new_record = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsNewRecord() {
        
        isNewRecord_ = false;
        onChanged();
        return this;
      }

      private int pJJAOILBFBN_ ;
      /**
       * <code>uint32 PJJAOILBFBN = 11;</code>
       * @return The pJJAOILBFBN.
       */
      @java.lang.Override
      public int getPJJAOILBFBN() {
        return pJJAOILBFBN_;
      }
      /**
       * <code>uint32 PJJAOILBFBN = 11;</code>
       * @param value The pJJAOILBFBN to set.
       * @return This builder for chaining.
       */
      public Builder setPJJAOILBFBN(int value) {
        
        pJJAOILBFBN_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 PJJAOILBFBN = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearPJJAOILBFBN() {
        
        pJJAOILBFBN_ = 0;
        onChanged();
        return this;
      }

      private int finalScore_ ;
      /**
       * <code>uint32 final_score = 15;</code>
       * @return The finalScore.
       */
      @java.lang.Override
      public int getFinalScore() {
        return finalScore_;
      }
      /**
       * <code>uint32 final_score = 15;</code>
       * @param value The finalScore to set.
       * @return This builder for chaining.
       */
      public Builder setFinalScore(int value) {
        
        finalScore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 final_score = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearFinalScore() {
        
        finalScore_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CrystalLinkDungeonSettleInfo)
    }

    // @@protoc_insertion_point(class_scope:CrystalLinkDungeonSettleInfo)
    private static final emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo();
    }

    public static emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CrystalLinkDungeonSettleInfo>
        PARSER = new com.google.protobuf.AbstractParser<CrystalLinkDungeonSettleInfo>() {
      @java.lang.Override
      public CrystalLinkDungeonSettleInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CrystalLinkDungeonSettleInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CrystalLinkDungeonSettleInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CrystalLinkDungeonSettleInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public emu.grasscutter.net.proto.CrystalLinkDungeonSettleInfoOuterClass.CrystalLinkDungeonSettleInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CrystalLinkDungeonSettleInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CrystalLinkDungeonSettleInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"CrystalLinkDungeonSettleInfo.proto\"\263\001\n" +
      "\034CrystalLinkDungeonSettleInfo\022\023\n\013DFPNKFE" +
      "KIIG\030\002 \001(\r\022\023\n\013ONHOJOBNAPM\030\003 \001(\r\022\023\n\013DEOOC" +
      "BAKMCJ\030\005 \001(\r\022\023\n\013DGCMIKFMKHP\030\006 \001(\010\022\025\n\ris_" +
      "new_record\030\010 \001(\010\022\023\n\013PJJAOILBFBN\030\013 \001(\r\022\023\n" +
      "\013final_score\030\017 \001(\rB\033\n\031emu.grasscutter.ne" +
      "t.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CrystalLinkDungeonSettleInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CrystalLinkDungeonSettleInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CrystalLinkDungeonSettleInfo_descriptor,
        new java.lang.String[] { "DFPNKFEKIIG", "ONHOJOBNAPM", "DEOOCBAKMCJ", "DGCMIKFMKHP", "IsNewRecord", "PJJAOILBFBN", "FinalScore", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
