// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EffigyChallengeV2SettleInfo.proto

package emu.grasscutter.net.proto;

public final class EffigyChallengeV2SettleInfoOuterClass {
  private EffigyChallengeV2SettleInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EffigyChallengeV2SettleInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EffigyChallengeV2SettleInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 KJJCCECPOFH = 4;</code>
     * @return The kJJCCECPOFH.
     */
    int getKJJCCECPOFH();

    /**
     * <code>uint32 GDJKLHGOHIF = 5;</code>
     * @return The gDJKLHGOHIF.
     */
    int getGDJKLHGOHIF();

    /**
     * <code>uint32 IADEOMKIMKB = 7;</code>
     * @return The iADEOMKIMKB.
     */
    int getIADEOMKIMKB();

    /**
     * <code>bool CLNJBIBJCMG = 11;</code>
     * @return The cLNJBIBJCMG.
     */
    boolean getCLNJBIBJCMG();

    /**
     * <code>uint32 GJGHLMEKEHM = 12;</code>
     * @return The gJGHLMEKEHM.
     */
    int getGJGHLMEKEHM();

    /**
     * <code>bool JCOOJLJOPEH = 14;</code>
     * @return The jCOOJLJOPEH.
     */
    boolean getJCOOJLJOPEH();
  }
  /**
   * Protobuf type {@code EffigyChallengeV2SettleInfo}
   */
  public static final class EffigyChallengeV2SettleInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EffigyChallengeV2SettleInfo)
      EffigyChallengeV2SettleInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EffigyChallengeV2SettleInfo.newBuilder() to construct.
    private EffigyChallengeV2SettleInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EffigyChallengeV2SettleInfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EffigyChallengeV2SettleInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EffigyChallengeV2SettleInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 32: {

              kJJCCECPOFH_ = input.readUInt32();
              break;
            }
            case 40: {

              gDJKLHGOHIF_ = input.readUInt32();
              break;
            }
            case 56: {

              iADEOMKIMKB_ = input.readUInt32();
              break;
            }
            case 88: {

              cLNJBIBJCMG_ = input.readBool();
              break;
            }
            case 96: {

              gJGHLMEKEHM_ = input.readUInt32();
              break;
            }
            case 112: {

              jCOOJLJOPEH_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.internal_static_EffigyChallengeV2SettleInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.internal_static_EffigyChallengeV2SettleInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo.class, emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo.Builder.class);
    }

    public static final int KJJCCECPOFH_FIELD_NUMBER = 4;
    private int kJJCCECPOFH_;
    /**
     * <code>uint32 KJJCCECPOFH = 4;</code>
     * @return The kJJCCECPOFH.
     */
    @java.lang.Override
    public int getKJJCCECPOFH() {
      return kJJCCECPOFH_;
    }

    public static final int GDJKLHGOHIF_FIELD_NUMBER = 5;
    private int gDJKLHGOHIF_;
    /**
     * <code>uint32 GDJKLHGOHIF = 5;</code>
     * @return The gDJKLHGOHIF.
     */
    @java.lang.Override
    public int getGDJKLHGOHIF() {
      return gDJKLHGOHIF_;
    }

    public static final int IADEOMKIMKB_FIELD_NUMBER = 7;
    private int iADEOMKIMKB_;
    /**
     * <code>uint32 IADEOMKIMKB = 7;</code>
     * @return The iADEOMKIMKB.
     */
    @java.lang.Override
    public int getIADEOMKIMKB() {
      return iADEOMKIMKB_;
    }

    public static final int CLNJBIBJCMG_FIELD_NUMBER = 11;
    private boolean cLNJBIBJCMG_;
    /**
     * <code>bool CLNJBIBJCMG = 11;</code>
     * @return The cLNJBIBJCMG.
     */
    @java.lang.Override
    public boolean getCLNJBIBJCMG() {
      return cLNJBIBJCMG_;
    }

    public static final int GJGHLMEKEHM_FIELD_NUMBER = 12;
    private int gJGHLMEKEHM_;
    /**
     * <code>uint32 GJGHLMEKEHM = 12;</code>
     * @return The gJGHLMEKEHM.
     */
    @java.lang.Override
    public int getGJGHLMEKEHM() {
      return gJGHLMEKEHM_;
    }

    public static final int JCOOJLJOPEH_FIELD_NUMBER = 14;
    private boolean jCOOJLJOPEH_;
    /**
     * <code>bool JCOOJLJOPEH = 14;</code>
     * @return The jCOOJLJOPEH.
     */
    @java.lang.Override
    public boolean getJCOOJLJOPEH() {
      return jCOOJLJOPEH_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (kJJCCECPOFH_ != 0) {
        output.writeUInt32(4, kJJCCECPOFH_);
      }
      if (gDJKLHGOHIF_ != 0) {
        output.writeUInt32(5, gDJKLHGOHIF_);
      }
      if (iADEOMKIMKB_ != 0) {
        output.writeUInt32(7, iADEOMKIMKB_);
      }
      if (cLNJBIBJCMG_ != false) {
        output.writeBool(11, cLNJBIBJCMG_);
      }
      if (gJGHLMEKEHM_ != 0) {
        output.writeUInt32(12, gJGHLMEKEHM_);
      }
      if (jCOOJLJOPEH_ != false) {
        output.writeBool(14, jCOOJLJOPEH_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (kJJCCECPOFH_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, kJJCCECPOFH_);
      }
      if (gDJKLHGOHIF_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, gDJKLHGOHIF_);
      }
      if (iADEOMKIMKB_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, iADEOMKIMKB_);
      }
      if (cLNJBIBJCMG_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(11, cLNJBIBJCMG_);
      }
      if (gJGHLMEKEHM_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(12, gJGHLMEKEHM_);
      }
      if (jCOOJLJOPEH_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(14, jCOOJLJOPEH_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo)) {
        return super.equals(obj);
      }
      emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo other = (emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo) obj;

      if (getKJJCCECPOFH()
          != other.getKJJCCECPOFH()) return false;
      if (getGDJKLHGOHIF()
          != other.getGDJKLHGOHIF()) return false;
      if (getIADEOMKIMKB()
          != other.getIADEOMKIMKB()) return false;
      if (getCLNJBIBJCMG()
          != other.getCLNJBIBJCMG()) return false;
      if (getGJGHLMEKEHM()
          != other.getGJGHLMEKEHM()) return false;
      if (getJCOOJLJOPEH()
          != other.getJCOOJLJOPEH()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KJJCCECPOFH_FIELD_NUMBER;
      hash = (53 * hash) + getKJJCCECPOFH();
      hash = (37 * hash) + GDJKLHGOHIF_FIELD_NUMBER;
      hash = (53 * hash) + getGDJKLHGOHIF();
      hash = (37 * hash) + IADEOMKIMKB_FIELD_NUMBER;
      hash = (53 * hash) + getIADEOMKIMKB();
      hash = (37 * hash) + CLNJBIBJCMG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCLNJBIBJCMG());
      hash = (37 * hash) + GJGHLMEKEHM_FIELD_NUMBER;
      hash = (53 * hash) + getGJGHLMEKEHM();
      hash = (37 * hash) + JCOOJLJOPEH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getJCOOJLJOPEH());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EffigyChallengeV2SettleInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EffigyChallengeV2SettleInfo)
        emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.internal_static_EffigyChallengeV2SettleInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.internal_static_EffigyChallengeV2SettleInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo.class, emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo.Builder.class);
      }

      // Construct using emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        kJJCCECPOFH_ = 0;

        gDJKLHGOHIF_ = 0;

        iADEOMKIMKB_ = 0;

        cLNJBIBJCMG_ = false;

        gJGHLMEKEHM_ = 0;

        jCOOJLJOPEH_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.internal_static_EffigyChallengeV2SettleInfo_descriptor;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo getDefaultInstanceForType() {
        return emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo.getDefaultInstance();
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo build() {
        emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo buildPartial() {
        emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo result = new emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo(this);
        result.kJJCCECPOFH_ = kJJCCECPOFH_;
        result.gDJKLHGOHIF_ = gDJKLHGOHIF_;
        result.iADEOMKIMKB_ = iADEOMKIMKB_;
        result.cLNJBIBJCMG_ = cLNJBIBJCMG_;
        result.gJGHLMEKEHM_ = gJGHLMEKEHM_;
        result.jCOOJLJOPEH_ = jCOOJLJOPEH_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo) {
          return mergeFrom((emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo other) {
        if (other == emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo.getDefaultInstance()) return this;
        if (other.getKJJCCECPOFH() != 0) {
          setKJJCCECPOFH(other.getKJJCCECPOFH());
        }
        if (other.getGDJKLHGOHIF() != 0) {
          setGDJKLHGOHIF(other.getGDJKLHGOHIF());
        }
        if (other.getIADEOMKIMKB() != 0) {
          setIADEOMKIMKB(other.getIADEOMKIMKB());
        }
        if (other.getCLNJBIBJCMG() != false) {
          setCLNJBIBJCMG(other.getCLNJBIBJCMG());
        }
        if (other.getGJGHLMEKEHM() != 0) {
          setGJGHLMEKEHM(other.getGJGHLMEKEHM());
        }
        if (other.getJCOOJLJOPEH() != false) {
          setJCOOJLJOPEH(other.getJCOOJLJOPEH());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int kJJCCECPOFH_ ;
      /**
       * <code>uint32 KJJCCECPOFH = 4;</code>
       * @return The kJJCCECPOFH.
       */
      @java.lang.Override
      public int getKJJCCECPOFH() {
        return kJJCCECPOFH_;
      }
      /**
       * <code>uint32 KJJCCECPOFH = 4;</code>
       * @param value The kJJCCECPOFH to set.
       * @return This builder for chaining.
       */
      public Builder setKJJCCECPOFH(int value) {
        
        kJJCCECPOFH_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 KJJCCECPOFH = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearKJJCCECPOFH() {
        
        kJJCCECPOFH_ = 0;
        onChanged();
        return this;
      }

      private int gDJKLHGOHIF_ ;
      /**
       * <code>uint32 GDJKLHGOHIF = 5;</code>
       * @return The gDJKLHGOHIF.
       */
      @java.lang.Override
      public int getGDJKLHGOHIF() {
        return gDJKLHGOHIF_;
      }
      /**
       * <code>uint32 GDJKLHGOHIF = 5;</code>
       * @param value The gDJKLHGOHIF to set.
       * @return This builder for chaining.
       */
      public Builder setGDJKLHGOHIF(int value) {
        
        gDJKLHGOHIF_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 GDJKLHGOHIF = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearGDJKLHGOHIF() {
        
        gDJKLHGOHIF_ = 0;
        onChanged();
        return this;
      }

      private int iADEOMKIMKB_ ;
      /**
       * <code>uint32 IADEOMKIMKB = 7;</code>
       * @return The iADEOMKIMKB.
       */
      @java.lang.Override
      public int getIADEOMKIMKB() {
        return iADEOMKIMKB_;
      }
      /**
       * <code>uint32 IADEOMKIMKB = 7;</code>
       * @param value The iADEOMKIMKB to set.
       * @return This builder for chaining.
       */
      public Builder setIADEOMKIMKB(int value) {
        
        iADEOMKIMKB_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 IADEOMKIMKB = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearIADEOMKIMKB() {
        
        iADEOMKIMKB_ = 0;
        onChanged();
        return this;
      }

      private boolean cLNJBIBJCMG_ ;
      /**
       * <code>bool CLNJBIBJCMG = 11;</code>
       * @return The cLNJBIBJCMG.
       */
      @java.lang.Override
      public boolean getCLNJBIBJCMG() {
        return cLNJBIBJCMG_;
      }
      /**
       * <code>bool CLNJBIBJCMG = 11;</code>
       * @param value The cLNJBIBJCMG to set.
       * @return This builder for chaining.
       */
      public Builder setCLNJBIBJCMG(boolean value) {
        
        cLNJBIBJCMG_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool CLNJBIBJCMG = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearCLNJBIBJCMG() {
        
        cLNJBIBJCMG_ = false;
        onChanged();
        return this;
      }

      private int gJGHLMEKEHM_ ;
      /**
       * <code>uint32 GJGHLMEKEHM = 12;</code>
       * @return The gJGHLMEKEHM.
       */
      @java.lang.Override
      public int getGJGHLMEKEHM() {
        return gJGHLMEKEHM_;
      }
      /**
       * <code>uint32 GJGHLMEKEHM = 12;</code>
       * @param value The gJGHLMEKEHM to set.
       * @return This builder for chaining.
       */
      public Builder setGJGHLMEKEHM(int value) {
        
        gJGHLMEKEHM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 GJGHLMEKEHM = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearGJGHLMEKEHM() {
        
        gJGHLMEKEHM_ = 0;
        onChanged();
        return this;
      }

      private boolean jCOOJLJOPEH_ ;
      /**
       * <code>bool JCOOJLJOPEH = 14;</code>
       * @return The jCOOJLJOPEH.
       */
      @java.lang.Override
      public boolean getJCOOJLJOPEH() {
        return jCOOJLJOPEH_;
      }
      /**
       * <code>bool JCOOJLJOPEH = 14;</code>
       * @param value The jCOOJLJOPEH to set.
       * @return This builder for chaining.
       */
      public Builder setJCOOJLJOPEH(boolean value) {
        
        jCOOJLJOPEH_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool JCOOJLJOPEH = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearJCOOJLJOPEH() {
        
        jCOOJLJOPEH_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EffigyChallengeV2SettleInfo)
    }

    // @@protoc_insertion_point(class_scope:EffigyChallengeV2SettleInfo)
    private static final emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo();
    }

    public static emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EffigyChallengeV2SettleInfo>
        PARSER = new com.google.protobuf.AbstractParser<EffigyChallengeV2SettleInfo>() {
      @java.lang.Override
      public EffigyChallengeV2SettleInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EffigyChallengeV2SettleInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EffigyChallengeV2SettleInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EffigyChallengeV2SettleInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public emu.grasscutter.net.proto.EffigyChallengeV2SettleInfoOuterClass.EffigyChallengeV2SettleInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EffigyChallengeV2SettleInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EffigyChallengeV2SettleInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!EffigyChallengeV2SettleInfo.proto\"\233\001\n\033" +
      "EffigyChallengeV2SettleInfo\022\023\n\013KJJCCECPO" +
      "FH\030\004 \001(\r\022\023\n\013GDJKLHGOHIF\030\005 \001(\r\022\023\n\013IADEOMK" +
      "IMKB\030\007 \001(\r\022\023\n\013CLNJBIBJCMG\030\013 \001(\010\022\023\n\013GJGHL" +
      "MEKEHM\030\014 \001(\r\022\023\n\013JCOOJLJOPEH\030\016 \001(\010B\033\n\031emu" +
      ".grasscutter.net.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_EffigyChallengeV2SettleInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EffigyChallengeV2SettleInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EffigyChallengeV2SettleInfo_descriptor,
        new java.lang.String[] { "KJJCCECPOFH", "GDJKLHGOHIF", "IADEOMKIMKB", "CLNJBIBJCMG", "GJGHLMEKEHM", "JCOOJLJOPEH", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
