// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FungusFighterV2SettleInfo.proto

package emu.grasscutter.net.proto;

public final class FungusFighterV2SettleInfoOuterClass {
  private FungusFighterV2SettleInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FungusFighterV2SettleInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FungusFighterV2SettleInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool is_new_record = 1;</code>
     * @return The isNewRecord.
     */
    boolean getIsNewRecord();

    /**
     * <code>uint32 JOFBEIACLOF = 2;</code>
     * @return The jOFBEIACLOF.
     */
    int getJOFBEIACLOF();

    /**
     * <code>uint32 PJJAOILBFBN = 5;</code>
     * @return The pJJAOILBFBN.
     */
    int getPJJAOILBFBN();

    /**
     * <code>uint32 CFBLFKNOJIK = 10;</code>
     * @return The cFBLFKNOJIK.
     */
    int getCFBLFKNOJIK();

    /**
     * <code>uint32 EHGIJGCNHKL = 11;</code>
     * @return The eHGIJGCNHKL.
     */
    int getEHGIJGCNHKL();

    /**
     * <code>uint32 DHIDKFLCKBF = 15;</code>
     * @return The dHIDKFLCKBF.
     */
    int getDHIDKFLCKBF();
  }
  /**
   * Protobuf type {@code FungusFighterV2SettleInfo}
   */
  public static final class FungusFighterV2SettleInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FungusFighterV2SettleInfo)
      FungusFighterV2SettleInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FungusFighterV2SettleInfo.newBuilder() to construct.
    private FungusFighterV2SettleInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FungusFighterV2SettleInfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FungusFighterV2SettleInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FungusFighterV2SettleInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              isNewRecord_ = input.readBool();
              break;
            }
            case 16: {

              jOFBEIACLOF_ = input.readUInt32();
              break;
            }
            case 40: {

              pJJAOILBFBN_ = input.readUInt32();
              break;
            }
            case 80: {

              cFBLFKNOJIK_ = input.readUInt32();
              break;
            }
            case 88: {

              eHGIJGCNHKL_ = input.readUInt32();
              break;
            }
            case 120: {

              dHIDKFLCKBF_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.internal_static_FungusFighterV2SettleInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.internal_static_FungusFighterV2SettleInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo.class, emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo.Builder.class);
    }

    public static final int IS_NEW_RECORD_FIELD_NUMBER = 1;
    private boolean isNewRecord_;
    /**
     * <code>bool is_new_record = 1;</code>
     * @return The isNewRecord.
     */
    @java.lang.Override
    public boolean getIsNewRecord() {
      return isNewRecord_;
    }

    public static final int JOFBEIACLOF_FIELD_NUMBER = 2;
    private int jOFBEIACLOF_;
    /**
     * <code>uint32 JOFBEIACLOF = 2;</code>
     * @return The jOFBEIACLOF.
     */
    @java.lang.Override
    public int getJOFBEIACLOF() {
      return jOFBEIACLOF_;
    }

    public static final int PJJAOILBFBN_FIELD_NUMBER = 5;
    private int pJJAOILBFBN_;
    /**
     * <code>uint32 PJJAOILBFBN = 5;</code>
     * @return The pJJAOILBFBN.
     */
    @java.lang.Override
    public int getPJJAOILBFBN() {
      return pJJAOILBFBN_;
    }

    public static final int CFBLFKNOJIK_FIELD_NUMBER = 10;
    private int cFBLFKNOJIK_;
    /**
     * <code>uint32 CFBLFKNOJIK = 10;</code>
     * @return The cFBLFKNOJIK.
     */
    @java.lang.Override
    public int getCFBLFKNOJIK() {
      return cFBLFKNOJIK_;
    }

    public static final int EHGIJGCNHKL_FIELD_NUMBER = 11;
    private int eHGIJGCNHKL_;
    /**
     * <code>uint32 EHGIJGCNHKL = 11;</code>
     * @return The eHGIJGCNHKL.
     */
    @java.lang.Override
    public int getEHGIJGCNHKL() {
      return eHGIJGCNHKL_;
    }

    public static final int DHIDKFLCKBF_FIELD_NUMBER = 15;
    private int dHIDKFLCKBF_;
    /**
     * <code>uint32 DHIDKFLCKBF = 15;</code>
     * @return The dHIDKFLCKBF.
     */
    @java.lang.Override
    public int getDHIDKFLCKBF() {
      return dHIDKFLCKBF_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (isNewRecord_ != false) {
        output.writeBool(1, isNewRecord_);
      }
      if (jOFBEIACLOF_ != 0) {
        output.writeUInt32(2, jOFBEIACLOF_);
      }
      if (pJJAOILBFBN_ != 0) {
        output.writeUInt32(5, pJJAOILBFBN_);
      }
      if (cFBLFKNOJIK_ != 0) {
        output.writeUInt32(10, cFBLFKNOJIK_);
      }
      if (eHGIJGCNHKL_ != 0) {
        output.writeUInt32(11, eHGIJGCNHKL_);
      }
      if (dHIDKFLCKBF_ != 0) {
        output.writeUInt32(15, dHIDKFLCKBF_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (isNewRecord_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isNewRecord_);
      }
      if (jOFBEIACLOF_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, jOFBEIACLOF_);
      }
      if (pJJAOILBFBN_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, pJJAOILBFBN_);
      }
      if (cFBLFKNOJIK_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, cFBLFKNOJIK_);
      }
      if (eHGIJGCNHKL_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(11, eHGIJGCNHKL_);
      }
      if (dHIDKFLCKBF_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(15, dHIDKFLCKBF_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo)) {
        return super.equals(obj);
      }
      emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo other = (emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo) obj;

      if (getIsNewRecord()
          != other.getIsNewRecord()) return false;
      if (getJOFBEIACLOF()
          != other.getJOFBEIACLOF()) return false;
      if (getPJJAOILBFBN()
          != other.getPJJAOILBFBN()) return false;
      if (getCFBLFKNOJIK()
          != other.getCFBLFKNOJIK()) return false;
      if (getEHGIJGCNHKL()
          != other.getEHGIJGCNHKL()) return false;
      if (getDHIDKFLCKBF()
          != other.getDHIDKFLCKBF()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IS_NEW_RECORD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsNewRecord());
      hash = (37 * hash) + JOFBEIACLOF_FIELD_NUMBER;
      hash = (53 * hash) + getJOFBEIACLOF();
      hash = (37 * hash) + PJJAOILBFBN_FIELD_NUMBER;
      hash = (53 * hash) + getPJJAOILBFBN();
      hash = (37 * hash) + CFBLFKNOJIK_FIELD_NUMBER;
      hash = (53 * hash) + getCFBLFKNOJIK();
      hash = (37 * hash) + EHGIJGCNHKL_FIELD_NUMBER;
      hash = (53 * hash) + getEHGIJGCNHKL();
      hash = (37 * hash) + DHIDKFLCKBF_FIELD_NUMBER;
      hash = (53 * hash) + getDHIDKFLCKBF();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FungusFighterV2SettleInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FungusFighterV2SettleInfo)
        emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.internal_static_FungusFighterV2SettleInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.internal_static_FungusFighterV2SettleInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo.class, emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo.Builder.class);
      }

      // Construct using emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        isNewRecord_ = false;

        jOFBEIACLOF_ = 0;

        pJJAOILBFBN_ = 0;

        cFBLFKNOJIK_ = 0;

        eHGIJGCNHKL_ = 0;

        dHIDKFLCKBF_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.internal_static_FungusFighterV2SettleInfo_descriptor;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo getDefaultInstanceForType() {
        return emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo.getDefaultInstance();
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo build() {
        emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo buildPartial() {
        emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo result = new emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo(this);
        result.isNewRecord_ = isNewRecord_;
        result.jOFBEIACLOF_ = jOFBEIACLOF_;
        result.pJJAOILBFBN_ = pJJAOILBFBN_;
        result.cFBLFKNOJIK_ = cFBLFKNOJIK_;
        result.eHGIJGCNHKL_ = eHGIJGCNHKL_;
        result.dHIDKFLCKBF_ = dHIDKFLCKBF_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo) {
          return mergeFrom((emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo other) {
        if (other == emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo.getDefaultInstance()) return this;
        if (other.getIsNewRecord() != false) {
          setIsNewRecord(other.getIsNewRecord());
        }
        if (other.getJOFBEIACLOF() != 0) {
          setJOFBEIACLOF(other.getJOFBEIACLOF());
        }
        if (other.getPJJAOILBFBN() != 0) {
          setPJJAOILBFBN(other.getPJJAOILBFBN());
        }
        if (other.getCFBLFKNOJIK() != 0) {
          setCFBLFKNOJIK(other.getCFBLFKNOJIK());
        }
        if (other.getEHGIJGCNHKL() != 0) {
          setEHGIJGCNHKL(other.getEHGIJGCNHKL());
        }
        if (other.getDHIDKFLCKBF() != 0) {
          setDHIDKFLCKBF(other.getDHIDKFLCKBF());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean isNewRecord_ ;
      /**
       * <code>bool is_new_record = 1;</code>
       * @return The isNewRecord.
       */
      @java.lang.Override
      public boolean getIsNewRecord() {
        return isNewRecord_;
      }
      /**
       * <code>bool is_new_record = 1;</code>
       * @param value The isNewRecord to set.
       * @return This builder for chaining.
       */
      public Builder setIsNewRecord(boolean value) {
        
        isNewRecord_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_new_record = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsNewRecord() {
        
        isNewRecord_ = false;
        onChanged();
        return this;
      }

      private int jOFBEIACLOF_ ;
      /**
       * <code>uint32 JOFBEIACLOF = 2;</code>
       * @return The jOFBEIACLOF.
       */
      @java.lang.Override
      public int getJOFBEIACLOF() {
        return jOFBEIACLOF_;
      }
      /**
       * <code>uint32 JOFBEIACLOF = 2;</code>
       * @param value The jOFBEIACLOF to set.
       * @return This builder for chaining.
       */
      public Builder setJOFBEIACLOF(int value) {
        
        jOFBEIACLOF_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 JOFBEIACLOF = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearJOFBEIACLOF() {
        
        jOFBEIACLOF_ = 0;
        onChanged();
        return this;
      }

      private int pJJAOILBFBN_ ;
      /**
       * <code>uint32 PJJAOILBFBN = 5;</code>
       * @return The pJJAOILBFBN.
       */
      @java.lang.Override
      public int getPJJAOILBFBN() {
        return pJJAOILBFBN_;
      }
      /**
       * <code>uint32 PJJAOILBFBN = 5;</code>
       * @param value The pJJAOILBFBN to set.
       * @return This builder for chaining.
       */
      public Builder setPJJAOILBFBN(int value) {
        
        pJJAOILBFBN_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 PJJAOILBFBN = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPJJAOILBFBN() {
        
        pJJAOILBFBN_ = 0;
        onChanged();
        return this;
      }

      private int cFBLFKNOJIK_ ;
      /**
       * <code>uint32 CFBLFKNOJIK = 10;</code>
       * @return The cFBLFKNOJIK.
       */
      @java.lang.Override
      public int getCFBLFKNOJIK() {
        return cFBLFKNOJIK_;
      }
      /**
       * <code>uint32 CFBLFKNOJIK = 10;</code>
       * @param value The cFBLFKNOJIK to set.
       * @return This builder for chaining.
       */
      public Builder setCFBLFKNOJIK(int value) {
        
        cFBLFKNOJIK_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 CFBLFKNOJIK = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearCFBLFKNOJIK() {
        
        cFBLFKNOJIK_ = 0;
        onChanged();
        return this;
      }

      private int eHGIJGCNHKL_ ;
      /**
       * <code>uint32 EHGIJGCNHKL = 11;</code>
       * @return The eHGIJGCNHKL.
       */
      @java.lang.Override
      public int getEHGIJGCNHKL() {
        return eHGIJGCNHKL_;
      }
      /**
       * <code>uint32 EHGIJGCNHKL = 11;</code>
       * @param value The eHGIJGCNHKL to set.
       * @return This builder for chaining.
       */
      public Builder setEHGIJGCNHKL(int value) {
        
        eHGIJGCNHKL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 EHGIJGCNHKL = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearEHGIJGCNHKL() {
        
        eHGIJGCNHKL_ = 0;
        onChanged();
        return this;
      }

      private int dHIDKFLCKBF_ ;
      /**
       * <code>uint32 DHIDKFLCKBF = 15;</code>
       * @return The dHIDKFLCKBF.
       */
      @java.lang.Override
      public int getDHIDKFLCKBF() {
        return dHIDKFLCKBF_;
      }
      /**
       * <code>uint32 DHIDKFLCKBF = 15;</code>
       * @param value The dHIDKFLCKBF to set.
       * @return This builder for chaining.
       */
      public Builder setDHIDKFLCKBF(int value) {
        
        dHIDKFLCKBF_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 DHIDKFLCKBF = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearDHIDKFLCKBF() {
        
        dHIDKFLCKBF_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FungusFighterV2SettleInfo)
    }

    // @@protoc_insertion_point(class_scope:FungusFighterV2SettleInfo)
    private static final emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo();
    }

    public static emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FungusFighterV2SettleInfo>
        PARSER = new com.google.protobuf.AbstractParser<FungusFighterV2SettleInfo>() {
      @java.lang.Override
      public FungusFighterV2SettleInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FungusFighterV2SettleInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FungusFighterV2SettleInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FungusFighterV2SettleInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public emu.grasscutter.net.proto.FungusFighterV2SettleInfoOuterClass.FungusFighterV2SettleInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FungusFighterV2SettleInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FungusFighterV2SettleInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037FungusFighterV2SettleInfo.proto\"\233\001\n\031Fu" +
      "ngusFighterV2SettleInfo\022\025\n\ris_new_record" +
      "\030\001 \001(\010\022\023\n\013JOFBEIACLOF\030\002 \001(\r\022\023\n\013PJJAOILBF" +
      "BN\030\005 \001(\r\022\023\n\013CFBLFKNOJIK\030\n \001(\r\022\023\n\013EHGIJGC" +
      "NHKL\030\013 \001(\r\022\023\n\013DHIDKFLCKBF\030\017 \001(\rB\033\n\031emu.g" +
      "rasscutter.net.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FungusFighterV2SettleInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FungusFighterV2SettleInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FungusFighterV2SettleInfo_descriptor,
        new java.lang.String[] { "IsNewRecord", "JOFBEIACLOF", "PJJAOILBFBN", "CFBLFKNOJIK", "EHGIJGCNHKL", "DHIDKFLCKBF", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
