// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InstableSprayDungeonSettleInfo.proto

package emu.grasscutter.net.proto;

public final class InstableSprayDungeonSettleInfoOuterClass {
  private InstableSprayDungeonSettleInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InstableSprayDungeonSettleInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InstableSprayDungeonSettleInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 MEMPKCGNNMF = 4;</code>
     * @return The mEMPKCGNNMF.
     */
    int getMEMPKCGNNMF();

    /**
     * <code>uint32 DMNLDPPGOKG = 5;</code>
     * @return The dMNLDPPGOKG.
     */
    int getDMNLDPPGOKG();

    /**
     * <code>bool is_new_record = 7;</code>
     * @return The isNewRecord.
     */
    boolean getIsNewRecord();

    /**
     * <code>repeated uint32 KNBIFCCIBLE = 11;</code>
     * @return A list containing the kNBIFCCIBLE.
     */
    java.util.List<java.lang.Integer> getKNBIFCCIBLEList();
    /**
     * <code>repeated uint32 KNBIFCCIBLE = 11;</code>
     * @return The count of kNBIFCCIBLE.
     */
    int getKNBIFCCIBLECount();
    /**
     * <code>repeated uint32 KNBIFCCIBLE = 11;</code>
     * @param index The index of the element to return.
     * @return The kNBIFCCIBLE at the given index.
     */
    int getKNBIFCCIBLE(int index);

    /**
     * <code>uint32 PJJAOILBFBN = 12;</code>
     * @return The pJJAOILBFBN.
     */
    int getPJJAOILBFBN();

    /**
     * <code>uint32 PBKEAOCBPMN = 13;</code>
     * @return The pBKEAOCBPMN.
     */
    int getPBKEAOCBPMN();
  }
  /**
   * Protobuf type {@code InstableSprayDungeonSettleInfo}
   */
  public static final class InstableSprayDungeonSettleInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:InstableSprayDungeonSettleInfo)
      InstableSprayDungeonSettleInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InstableSprayDungeonSettleInfo.newBuilder() to construct.
    private InstableSprayDungeonSettleInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InstableSprayDungeonSettleInfo() {
      kNBIFCCIBLE_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InstableSprayDungeonSettleInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InstableSprayDungeonSettleInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 32: {

              mEMPKCGNNMF_ = input.readUInt32();
              break;
            }
            case 40: {

              dMNLDPPGOKG_ = input.readUInt32();
              break;
            }
            case 56: {

              isNewRecord_ = input.readBool();
              break;
            }
            case 88: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                kNBIFCCIBLE_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              kNBIFCCIBLE_.addInt(input.readUInt32());
              break;
            }
            case 90: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                kNBIFCCIBLE_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                kNBIFCCIBLE_.addInt(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 96: {

              pJJAOILBFBN_ = input.readUInt32();
              break;
            }
            case 104: {

              pBKEAOCBPMN_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          kNBIFCCIBLE_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.internal_static_InstableSprayDungeonSettleInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.internal_static_InstableSprayDungeonSettleInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo.class, emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo.Builder.class);
    }

    public static final int MEMPKCGNNMF_FIELD_NUMBER = 4;
    private int mEMPKCGNNMF_;
    /**
     * <code>uint32 MEMPKCGNNMF = 4;</code>
     * @return The mEMPKCGNNMF.
     */
    @java.lang.Override
    public int getMEMPKCGNNMF() {
      return mEMPKCGNNMF_;
    }

    public static final int DMNLDPPGOKG_FIELD_NUMBER = 5;
    private int dMNLDPPGOKG_;
    /**
     * <code>uint32 DMNLDPPGOKG = 5;</code>
     * @return The dMNLDPPGOKG.
     */
    @java.lang.Override
    public int getDMNLDPPGOKG() {
      return dMNLDPPGOKG_;
    }

    public static final int IS_NEW_RECORD_FIELD_NUMBER = 7;
    private boolean isNewRecord_;
    /**
     * <code>bool is_new_record = 7;</code>
     * @return The isNewRecord.
     */
    @java.lang.Override
    public boolean getIsNewRecord() {
      return isNewRecord_;
    }

    public static final int KNBIFCCIBLE_FIELD_NUMBER = 11;
    private com.google.protobuf.Internal.IntList kNBIFCCIBLE_;
    /**
     * <code>repeated uint32 KNBIFCCIBLE = 11;</code>
     * @return A list containing the kNBIFCCIBLE.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getKNBIFCCIBLEList() {
      return kNBIFCCIBLE_;
    }
    /**
     * <code>repeated uint32 KNBIFCCIBLE = 11;</code>
     * @return The count of kNBIFCCIBLE.
     */
    public int getKNBIFCCIBLECount() {
      return kNBIFCCIBLE_.size();
    }
    /**
     * <code>repeated uint32 KNBIFCCIBLE = 11;</code>
     * @param index The index of the element to return.
     * @return The kNBIFCCIBLE at the given index.
     */
    public int getKNBIFCCIBLE(int index) {
      return kNBIFCCIBLE_.getInt(index);
    }
    private int kNBIFCCIBLEMemoizedSerializedSize = -1;

    public static final int PJJAOILBFBN_FIELD_NUMBER = 12;
    private int pJJAOILBFBN_;
    /**
     * <code>uint32 PJJAOILBFBN = 12;</code>
     * @return The pJJAOILBFBN.
     */
    @java.lang.Override
    public int getPJJAOILBFBN() {
      return pJJAOILBFBN_;
    }

    public static final int PBKEAOCBPMN_FIELD_NUMBER = 13;
    private int pBKEAOCBPMN_;
    /**
     * <code>uint32 PBKEAOCBPMN = 13;</code>
     * @return The pBKEAOCBPMN.
     */
    @java.lang.Override
    public int getPBKEAOCBPMN() {
      return pBKEAOCBPMN_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (mEMPKCGNNMF_ != 0) {
        output.writeUInt32(4, mEMPKCGNNMF_);
      }
      if (dMNLDPPGOKG_ != 0) {
        output.writeUInt32(5, dMNLDPPGOKG_);
      }
      if (isNewRecord_ != false) {
        output.writeBool(7, isNewRecord_);
      }
      if (getKNBIFCCIBLEList().size() > 0) {
        output.writeUInt32NoTag(90);
        output.writeUInt32NoTag(kNBIFCCIBLEMemoizedSerializedSize);
      }
      for (int i = 0; i < kNBIFCCIBLE_.size(); i++) {
        output.writeUInt32NoTag(kNBIFCCIBLE_.getInt(i));
      }
      if (pJJAOILBFBN_ != 0) {
        output.writeUInt32(12, pJJAOILBFBN_);
      }
      if (pBKEAOCBPMN_ != 0) {
        output.writeUInt32(13, pBKEAOCBPMN_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mEMPKCGNNMF_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, mEMPKCGNNMF_);
      }
      if (dMNLDPPGOKG_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, dMNLDPPGOKG_);
      }
      if (isNewRecord_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, isNewRecord_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < kNBIFCCIBLE_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(kNBIFCCIBLE_.getInt(i));
        }
        size += dataSize;
        if (!getKNBIFCCIBLEList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        kNBIFCCIBLEMemoizedSerializedSize = dataSize;
      }
      if (pJJAOILBFBN_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(12, pJJAOILBFBN_);
      }
      if (pBKEAOCBPMN_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(13, pBKEAOCBPMN_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo)) {
        return super.equals(obj);
      }
      emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo other = (emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo) obj;

      if (getMEMPKCGNNMF()
          != other.getMEMPKCGNNMF()) return false;
      if (getDMNLDPPGOKG()
          != other.getDMNLDPPGOKG()) return false;
      if (getIsNewRecord()
          != other.getIsNewRecord()) return false;
      if (!getKNBIFCCIBLEList()
          .equals(other.getKNBIFCCIBLEList())) return false;
      if (getPJJAOILBFBN()
          != other.getPJJAOILBFBN()) return false;
      if (getPBKEAOCBPMN()
          != other.getPBKEAOCBPMN()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MEMPKCGNNMF_FIELD_NUMBER;
      hash = (53 * hash) + getMEMPKCGNNMF();
      hash = (37 * hash) + DMNLDPPGOKG_FIELD_NUMBER;
      hash = (53 * hash) + getDMNLDPPGOKG();
      hash = (37 * hash) + IS_NEW_RECORD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsNewRecord());
      if (getKNBIFCCIBLECount() > 0) {
        hash = (37 * hash) + KNBIFCCIBLE_FIELD_NUMBER;
        hash = (53 * hash) + getKNBIFCCIBLEList().hashCode();
      }
      hash = (37 * hash) + PJJAOILBFBN_FIELD_NUMBER;
      hash = (53 * hash) + getPJJAOILBFBN();
      hash = (37 * hash) + PBKEAOCBPMN_FIELD_NUMBER;
      hash = (53 * hash) + getPBKEAOCBPMN();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InstableSprayDungeonSettleInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InstableSprayDungeonSettleInfo)
        emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.internal_static_InstableSprayDungeonSettleInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.internal_static_InstableSprayDungeonSettleInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo.class, emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo.Builder.class);
      }

      // Construct using emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        mEMPKCGNNMF_ = 0;

        dMNLDPPGOKG_ = 0;

        isNewRecord_ = false;

        kNBIFCCIBLE_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        pJJAOILBFBN_ = 0;

        pBKEAOCBPMN_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.internal_static_InstableSprayDungeonSettleInfo_descriptor;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo getDefaultInstanceForType() {
        return emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo.getDefaultInstance();
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo build() {
        emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo buildPartial() {
        emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo result = new emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo(this);
        int from_bitField0_ = bitField0_;
        result.mEMPKCGNNMF_ = mEMPKCGNNMF_;
        result.dMNLDPPGOKG_ = dMNLDPPGOKG_;
        result.isNewRecord_ = isNewRecord_;
        if (((bitField0_ & 0x00000001) != 0)) {
          kNBIFCCIBLE_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.kNBIFCCIBLE_ = kNBIFCCIBLE_;
        result.pJJAOILBFBN_ = pJJAOILBFBN_;
        result.pBKEAOCBPMN_ = pBKEAOCBPMN_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo) {
          return mergeFrom((emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo other) {
        if (other == emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo.getDefaultInstance()) return this;
        if (other.getMEMPKCGNNMF() != 0) {
          setMEMPKCGNNMF(other.getMEMPKCGNNMF());
        }
        if (other.getDMNLDPPGOKG() != 0) {
          setDMNLDPPGOKG(other.getDMNLDPPGOKG());
        }
        if (other.getIsNewRecord() != false) {
          setIsNewRecord(other.getIsNewRecord());
        }
        if (!other.kNBIFCCIBLE_.isEmpty()) {
          if (kNBIFCCIBLE_.isEmpty()) {
            kNBIFCCIBLE_ = other.kNBIFCCIBLE_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureKNBIFCCIBLEIsMutable();
            kNBIFCCIBLE_.addAll(other.kNBIFCCIBLE_);
          }
          onChanged();
        }
        if (other.getPJJAOILBFBN() != 0) {
          setPJJAOILBFBN(other.getPJJAOILBFBN());
        }
        if (other.getPBKEAOCBPMN() != 0) {
          setPBKEAOCBPMN(other.getPBKEAOCBPMN());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int mEMPKCGNNMF_ ;
      /**
       * <code>uint32 MEMPKCGNNMF = 4;</code>
       * @return The mEMPKCGNNMF.
       */
      @java.lang.Override
      public int getMEMPKCGNNMF() {
        return mEMPKCGNNMF_;
      }
      /**
       * <code>uint32 MEMPKCGNNMF = 4;</code>
       * @param value The mEMPKCGNNMF to set.
       * @return This builder for chaining.
       */
      public Builder setMEMPKCGNNMF(int value) {
        
        mEMPKCGNNMF_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 MEMPKCGNNMF = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMEMPKCGNNMF() {
        
        mEMPKCGNNMF_ = 0;
        onChanged();
        return this;
      }

      private int dMNLDPPGOKG_ ;
      /**
       * <code>uint32 DMNLDPPGOKG = 5;</code>
       * @return The dMNLDPPGOKG.
       */
      @java.lang.Override
      public int getDMNLDPPGOKG() {
        return dMNLDPPGOKG_;
      }
      /**
       * <code>uint32 DMNLDPPGOKG = 5;</code>
       * @param value The dMNLDPPGOKG to set.
       * @return This builder for chaining.
       */
      public Builder setDMNLDPPGOKG(int value) {
        
        dMNLDPPGOKG_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 DMNLDPPGOKG = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDMNLDPPGOKG() {
        
        dMNLDPPGOKG_ = 0;
        onChanged();
        return this;
      }

      private boolean isNewRecord_ ;
      /**
       * <code>bool is_new_record = 7;</code>
       * @return The isNewRecord.
       */
      @java.lang.Override
      public boolean getIsNewRecord() {
        return isNewRecord_;
      }
      /**
       * <code>bool is_new_record = 7;</code>
       * @param value The isNewRecord to set.
       * @return This builder for chaining.
       */
      public Builder setIsNewRecord(boolean value) {
        
        isNewRecord_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_new_record = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsNewRecord() {
        
        isNewRecord_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList kNBIFCCIBLE_ = emptyIntList();
      private void ensureKNBIFCCIBLEIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          kNBIFCCIBLE_ = mutableCopy(kNBIFCCIBLE_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated uint32 KNBIFCCIBLE = 11;</code>
       * @return A list containing the kNBIFCCIBLE.
       */
      public java.util.List<java.lang.Integer>
          getKNBIFCCIBLEList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(kNBIFCCIBLE_) : kNBIFCCIBLE_;
      }
      /**
       * <code>repeated uint32 KNBIFCCIBLE = 11;</code>
       * @return The count of kNBIFCCIBLE.
       */
      public int getKNBIFCCIBLECount() {
        return kNBIFCCIBLE_.size();
      }
      /**
       * <code>repeated uint32 KNBIFCCIBLE = 11;</code>
       * @param index The index of the element to return.
       * @return The kNBIFCCIBLE at the given index.
       */
      public int getKNBIFCCIBLE(int index) {
        return kNBIFCCIBLE_.getInt(index);
      }
      /**
       * <code>repeated uint32 KNBIFCCIBLE = 11;</code>
       * @param index The index to set the value at.
       * @param value The kNBIFCCIBLE to set.
       * @return This builder for chaining.
       */
      public Builder setKNBIFCCIBLE(
          int index, int value) {
        ensureKNBIFCCIBLEIsMutable();
        kNBIFCCIBLE_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 KNBIFCCIBLE = 11;</code>
       * @param value The kNBIFCCIBLE to add.
       * @return This builder for chaining.
       */
      public Builder addKNBIFCCIBLE(int value) {
        ensureKNBIFCCIBLEIsMutable();
        kNBIFCCIBLE_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 KNBIFCCIBLE = 11;</code>
       * @param values The kNBIFCCIBLE to add.
       * @return This builder for chaining.
       */
      public Builder addAllKNBIFCCIBLE(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureKNBIFCCIBLEIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, kNBIFCCIBLE_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 KNBIFCCIBLE = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearKNBIFCCIBLE() {
        kNBIFCCIBLE_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private int pJJAOILBFBN_ ;
      /**
       * <code>uint32 PJJAOILBFBN = 12;</code>
       * @return The pJJAOILBFBN.
       */
      @java.lang.Override
      public int getPJJAOILBFBN() {
        return pJJAOILBFBN_;
      }
      /**
       * <code>uint32 PJJAOILBFBN = 12;</code>
       * @param value The pJJAOILBFBN to set.
       * @return This builder for chaining.
       */
      public Builder setPJJAOILBFBN(int value) {
        
        pJJAOILBFBN_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 PJJAOILBFBN = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearPJJAOILBFBN() {
        
        pJJAOILBFBN_ = 0;
        onChanged();
        return this;
      }

      private int pBKEAOCBPMN_ ;
      /**
       * <code>uint32 PBKEAOCBPMN = 13;</code>
       * @return The pBKEAOCBPMN.
       */
      @java.lang.Override
      public int getPBKEAOCBPMN() {
        return pBKEAOCBPMN_;
      }
      /**
       * <code>uint32 PBKEAOCBPMN = 13;</code>
       * @param value The pBKEAOCBPMN to set.
       * @return This builder for chaining.
       */
      public Builder setPBKEAOCBPMN(int value) {
        
        pBKEAOCBPMN_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 PBKEAOCBPMN = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearPBKEAOCBPMN() {
        
        pBKEAOCBPMN_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:InstableSprayDungeonSettleInfo)
    }

    // @@protoc_insertion_point(class_scope:InstableSprayDungeonSettleInfo)
    private static final emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo();
    }

    public static emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InstableSprayDungeonSettleInfo>
        PARSER = new com.google.protobuf.AbstractParser<InstableSprayDungeonSettleInfo>() {
      @java.lang.Override
      public InstableSprayDungeonSettleInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InstableSprayDungeonSettleInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InstableSprayDungeonSettleInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InstableSprayDungeonSettleInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public emu.grasscutter.net.proto.InstableSprayDungeonSettleInfoOuterClass.InstableSprayDungeonSettleInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InstableSprayDungeonSettleInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InstableSprayDungeonSettleInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$InstableSprayDungeonSettleInfo.proto\"\240" +
      "\001\n\036InstableSprayDungeonSettleInfo\022\023\n\013MEM" +
      "PKCGNNMF\030\004 \001(\r\022\023\n\013DMNLDPPGOKG\030\005 \001(\r\022\025\n\ri" +
      "s_new_record\030\007 \001(\010\022\023\n\013KNBIFCCIBLE\030\013 \003(\r\022" +
      "\023\n\013PJJAOILBFBN\030\014 \001(\r\022\023\n\013PBKEAOCBPMN\030\r \001(" +
      "\rB\033\n\031emu.grasscutter.net.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_InstableSprayDungeonSettleInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_InstableSprayDungeonSettleInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InstableSprayDungeonSettleInfo_descriptor,
        new java.lang.String[] { "MEMPKCGNNMF", "DMNLDPPGOKG", "IsNewRecord", "KNBIFCCIBLE", "PJJAOILBFBN", "PBKEAOCBPMN", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
