// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoguelikeDungeonSettleInfo.proto

package emu.grasscutter.net.proto;

public final class RoguelikeDungeonSettleInfoOuterClass {
  private RoguelikeDungeonSettleInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RoguelikeDungeonSettleInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RoguelikeDungeonSettleInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;uint32, .RoguelikeSettleCoinInfo&gt; CDNIIBLIFII = 1;</code>
     */
    int getCDNIIBLIFIICount();
    /**
     * <code>map&lt;uint32, .RoguelikeSettleCoinInfo&gt; CDNIIBLIFII = 1;</code>
     */
    boolean containsCDNIIBLIFII(
        int key);
    /**
     * Use {@link #getCDNIIBLIFIIMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo>
    getCDNIIBLIFII();
    /**
     * <code>map&lt;uint32, .RoguelikeSettleCoinInfo&gt; CDNIIBLIFII = 1;</code>
     */
    java.util.Map<java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo>
    getCDNIIBLIFIIMap();
    /**
     * <code>map&lt;uint32, .RoguelikeSettleCoinInfo&gt; CDNIIBLIFII = 1;</code>
     */

    emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo getCDNIIBLIFIIOrDefault(
        int key,
        emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo defaultValue);
    /**
     * <code>map&lt;uint32, .RoguelikeSettleCoinInfo&gt; CDNIIBLIFII = 1;</code>
     */

    emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo getCDNIIBLIFIIOrThrow(
        int key);

    /**
     * <code>uint32 HBINBDBMOED = 2;</code>
     * @return The hBINBDBMOED.
     */
    int getHBINBDBMOED();

    /**
     * <code>bool PKOELLIPBHP = 3;</code>
     * @return The pKOELLIPBHP.
     */
    boolean getPKOELLIPBHP();

    /**
     * <code>uint32 ELHPDAEIMPJ = 4;</code>
     * @return The eLHPDAEIMPJ.
     */
    int getELHPDAEIMPJ();

    /**
     * <code>uint32 cur_level = 6;</code>
     * @return The curLevel.
     */
    int getCurLevel();

    /**
     * <code>uint32 MEMPKCGNNMF = 10;</code>
     * @return The mEMPKCGNNMF.
     */
    int getMEMPKCGNNMF();

    /**
     * <code>bool CMFPJHFFHBI = 14;</code>
     * @return The cMFPJHFFHBI.
     */
    boolean getCMFPJHFFHBI();
  }
  /**
   * Protobuf type {@code RoguelikeDungeonSettleInfo}
   */
  public static final class RoguelikeDungeonSettleInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RoguelikeDungeonSettleInfo)
      RoguelikeDungeonSettleInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoguelikeDungeonSettleInfo.newBuilder() to construct.
    private RoguelikeDungeonSettleInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoguelikeDungeonSettleInfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RoguelikeDungeonSettleInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RoguelikeDungeonSettleInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                cDNIIBLIFII_ = com.google.protobuf.MapField.newMapField(
                    CDNIIBLIFIIDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo>
              cDNIIBLIFII__ = input.readMessage(
                  CDNIIBLIFIIDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              cDNIIBLIFII_.getMutableMap().put(
                  cDNIIBLIFII__.getKey(), cDNIIBLIFII__.getValue());
              break;
            }
            case 16: {

              hBINBDBMOED_ = input.readUInt32();
              break;
            }
            case 24: {

              pKOELLIPBHP_ = input.readBool();
              break;
            }
            case 32: {

              eLHPDAEIMPJ_ = input.readUInt32();
              break;
            }
            case 48: {

              curLevel_ = input.readUInt32();
              break;
            }
            case 80: {

              mEMPKCGNNMF_ = input.readUInt32();
              break;
            }
            case 112: {

              cMFPJHFFHBI_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.internal_static_RoguelikeDungeonSettleInfo_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetCDNIIBLIFII();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.internal_static_RoguelikeDungeonSettleInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo.class, emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo.Builder.class);
    }

    public static final int CDNIIBLIFII_FIELD_NUMBER = 1;
    private static final class CDNIIBLIFIIDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo>newDefaultInstance(
                  emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.internal_static_RoguelikeDungeonSettleInfo_CDNIIBLIFIIEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.UINT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo> cDNIIBLIFII_;
    private com.google.protobuf.MapField<java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo>
    internalGetCDNIIBLIFII() {
      if (cDNIIBLIFII_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CDNIIBLIFIIDefaultEntryHolder.defaultEntry);
      }
      return cDNIIBLIFII_;
    }

    public int getCDNIIBLIFIICount() {
      return internalGetCDNIIBLIFII().getMap().size();
    }
    /**
     * <code>map&lt;uint32, .RoguelikeSettleCoinInfo&gt; CDNIIBLIFII = 1;</code>
     */

    @java.lang.Override
    public boolean containsCDNIIBLIFII(
        int key) {
      
      return internalGetCDNIIBLIFII().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCDNIIBLIFIIMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo> getCDNIIBLIFII() {
      return getCDNIIBLIFIIMap();
    }
    /**
     * <code>map&lt;uint32, .RoguelikeSettleCoinInfo&gt; CDNIIBLIFII = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo> getCDNIIBLIFIIMap() {
      return internalGetCDNIIBLIFII().getMap();
    }
    /**
     * <code>map&lt;uint32, .RoguelikeSettleCoinInfo&gt; CDNIIBLIFII = 1;</code>
     */
    @java.lang.Override

    public emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo getCDNIIBLIFIIOrDefault(
        int key,
        emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo defaultValue) {
      
      java.util.Map<java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo> map =
          internalGetCDNIIBLIFII().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;uint32, .RoguelikeSettleCoinInfo&gt; CDNIIBLIFII = 1;</code>
     */
    @java.lang.Override

    public emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo getCDNIIBLIFIIOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo> map =
          internalGetCDNIIBLIFII().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int HBINBDBMOED_FIELD_NUMBER = 2;
    private int hBINBDBMOED_;
    /**
     * <code>uint32 HBINBDBMOED = 2;</code>
     * @return The hBINBDBMOED.
     */
    @java.lang.Override
    public int getHBINBDBMOED() {
      return hBINBDBMOED_;
    }

    public static final int PKOELLIPBHP_FIELD_NUMBER = 3;
    private boolean pKOELLIPBHP_;
    /**
     * <code>bool PKOELLIPBHP = 3;</code>
     * @return The pKOELLIPBHP.
     */
    @java.lang.Override
    public boolean getPKOELLIPBHP() {
      return pKOELLIPBHP_;
    }

    public static final int ELHPDAEIMPJ_FIELD_NUMBER = 4;
    private int eLHPDAEIMPJ_;
    /**
     * <code>uint32 ELHPDAEIMPJ = 4;</code>
     * @return The eLHPDAEIMPJ.
     */
    @java.lang.Override
    public int getELHPDAEIMPJ() {
      return eLHPDAEIMPJ_;
    }

    public static final int CUR_LEVEL_FIELD_NUMBER = 6;
    private int curLevel_;
    /**
     * <code>uint32 cur_level = 6;</code>
     * @return The curLevel.
     */
    @java.lang.Override
    public int getCurLevel() {
      return curLevel_;
    }

    public static final int MEMPKCGNNMF_FIELD_NUMBER = 10;
    private int mEMPKCGNNMF_;
    /**
     * <code>uint32 MEMPKCGNNMF = 10;</code>
     * @return The mEMPKCGNNMF.
     */
    @java.lang.Override
    public int getMEMPKCGNNMF() {
      return mEMPKCGNNMF_;
    }

    public static final int CMFPJHFFHBI_FIELD_NUMBER = 14;
    private boolean cMFPJHFFHBI_;
    /**
     * <code>bool CMFPJHFFHBI = 14;</code>
     * @return The cMFPJHFFHBI.
     */
    @java.lang.Override
    public boolean getCMFPJHFFHBI() {
      return cMFPJHFFHBI_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetCDNIIBLIFII(),
          CDNIIBLIFIIDefaultEntryHolder.defaultEntry,
          1);
      if (hBINBDBMOED_ != 0) {
        output.writeUInt32(2, hBINBDBMOED_);
      }
      if (pKOELLIPBHP_ != false) {
        output.writeBool(3, pKOELLIPBHP_);
      }
      if (eLHPDAEIMPJ_ != 0) {
        output.writeUInt32(4, eLHPDAEIMPJ_);
      }
      if (curLevel_ != 0) {
        output.writeUInt32(6, curLevel_);
      }
      if (mEMPKCGNNMF_ != 0) {
        output.writeUInt32(10, mEMPKCGNNMF_);
      }
      if (cMFPJHFFHBI_ != false) {
        output.writeBool(14, cMFPJHFFHBI_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo> entry
           : internalGetCDNIIBLIFII().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo>
        cDNIIBLIFII__ = CDNIIBLIFIIDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, cDNIIBLIFII__);
      }
      if (hBINBDBMOED_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, hBINBDBMOED_);
      }
      if (pKOELLIPBHP_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, pKOELLIPBHP_);
      }
      if (eLHPDAEIMPJ_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, eLHPDAEIMPJ_);
      }
      if (curLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, curLevel_);
      }
      if (mEMPKCGNNMF_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, mEMPKCGNNMF_);
      }
      if (cMFPJHFFHBI_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(14, cMFPJHFFHBI_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo)) {
        return super.equals(obj);
      }
      emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo other = (emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo) obj;

      if (!internalGetCDNIIBLIFII().equals(
          other.internalGetCDNIIBLIFII())) return false;
      if (getHBINBDBMOED()
          != other.getHBINBDBMOED()) return false;
      if (getPKOELLIPBHP()
          != other.getPKOELLIPBHP()) return false;
      if (getELHPDAEIMPJ()
          != other.getELHPDAEIMPJ()) return false;
      if (getCurLevel()
          != other.getCurLevel()) return false;
      if (getMEMPKCGNNMF()
          != other.getMEMPKCGNNMF()) return false;
      if (getCMFPJHFFHBI()
          != other.getCMFPJHFFHBI()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetCDNIIBLIFII().getMap().isEmpty()) {
        hash = (37 * hash) + CDNIIBLIFII_FIELD_NUMBER;
        hash = (53 * hash) + internalGetCDNIIBLIFII().hashCode();
      }
      hash = (37 * hash) + HBINBDBMOED_FIELD_NUMBER;
      hash = (53 * hash) + getHBINBDBMOED();
      hash = (37 * hash) + PKOELLIPBHP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPKOELLIPBHP());
      hash = (37 * hash) + ELHPDAEIMPJ_FIELD_NUMBER;
      hash = (53 * hash) + getELHPDAEIMPJ();
      hash = (37 * hash) + CUR_LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getCurLevel();
      hash = (37 * hash) + MEMPKCGNNMF_FIELD_NUMBER;
      hash = (53 * hash) + getMEMPKCGNNMF();
      hash = (37 * hash) + CMFPJHFFHBI_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCMFPJHFFHBI());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RoguelikeDungeonSettleInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RoguelikeDungeonSettleInfo)
        emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.internal_static_RoguelikeDungeonSettleInfo_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetCDNIIBLIFII();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableCDNIIBLIFII();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.internal_static_RoguelikeDungeonSettleInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo.class, emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo.Builder.class);
      }

      // Construct using emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableCDNIIBLIFII().clear();
        hBINBDBMOED_ = 0;

        pKOELLIPBHP_ = false;

        eLHPDAEIMPJ_ = 0;

        curLevel_ = 0;

        mEMPKCGNNMF_ = 0;

        cMFPJHFFHBI_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.internal_static_RoguelikeDungeonSettleInfo_descriptor;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo getDefaultInstanceForType() {
        return emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo.getDefaultInstance();
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo build() {
        emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo buildPartial() {
        emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo result = new emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo(this);
        int from_bitField0_ = bitField0_;
        result.cDNIIBLIFII_ = internalGetCDNIIBLIFII();
        result.cDNIIBLIFII_.makeImmutable();
        result.hBINBDBMOED_ = hBINBDBMOED_;
        result.pKOELLIPBHP_ = pKOELLIPBHP_;
        result.eLHPDAEIMPJ_ = eLHPDAEIMPJ_;
        result.curLevel_ = curLevel_;
        result.mEMPKCGNNMF_ = mEMPKCGNNMF_;
        result.cMFPJHFFHBI_ = cMFPJHFFHBI_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo) {
          return mergeFrom((emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo other) {
        if (other == emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo.getDefaultInstance()) return this;
        internalGetMutableCDNIIBLIFII().mergeFrom(
            other.internalGetCDNIIBLIFII());
        if (other.getHBINBDBMOED() != 0) {
          setHBINBDBMOED(other.getHBINBDBMOED());
        }
        if (other.getPKOELLIPBHP() != false) {
          setPKOELLIPBHP(other.getPKOELLIPBHP());
        }
        if (other.getELHPDAEIMPJ() != 0) {
          setELHPDAEIMPJ(other.getELHPDAEIMPJ());
        }
        if (other.getCurLevel() != 0) {
          setCurLevel(other.getCurLevel());
        }
        if (other.getMEMPKCGNNMF() != 0) {
          setMEMPKCGNNMF(other.getMEMPKCGNNMF());
        }
        if (other.getCMFPJHFFHBI() != false) {
          setCMFPJHFFHBI(other.getCMFPJHFFHBI());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo> cDNIIBLIFII_;
      private com.google.protobuf.MapField<java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo>
      internalGetCDNIIBLIFII() {
        if (cDNIIBLIFII_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              CDNIIBLIFIIDefaultEntryHolder.defaultEntry);
        }
        return cDNIIBLIFII_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo>
      internalGetMutableCDNIIBLIFII() {
        onChanged();;
        if (cDNIIBLIFII_ == null) {
          cDNIIBLIFII_ = com.google.protobuf.MapField.newMapField(
              CDNIIBLIFIIDefaultEntryHolder.defaultEntry);
        }
        if (!cDNIIBLIFII_.isMutable()) {
          cDNIIBLIFII_ = cDNIIBLIFII_.copy();
        }
        return cDNIIBLIFII_;
      }

      public int getCDNIIBLIFIICount() {
        return internalGetCDNIIBLIFII().getMap().size();
      }
      /**
       * <code>map&lt;uint32, .RoguelikeSettleCoinInfo&gt; CDNIIBLIFII = 1;</code>
       */

      @java.lang.Override
      public boolean containsCDNIIBLIFII(
          int key) {
        
        return internalGetCDNIIBLIFII().getMap().containsKey(key);
      }
      /**
       * Use {@link #getCDNIIBLIFIIMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo> getCDNIIBLIFII() {
        return getCDNIIBLIFIIMap();
      }
      /**
       * <code>map&lt;uint32, .RoguelikeSettleCoinInfo&gt; CDNIIBLIFII = 1;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo> getCDNIIBLIFIIMap() {
        return internalGetCDNIIBLIFII().getMap();
      }
      /**
       * <code>map&lt;uint32, .RoguelikeSettleCoinInfo&gt; CDNIIBLIFII = 1;</code>
       */
      @java.lang.Override

      public emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo getCDNIIBLIFIIOrDefault(
          int key,
          emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo defaultValue) {
        
        java.util.Map<java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo> map =
            internalGetCDNIIBLIFII().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;uint32, .RoguelikeSettleCoinInfo&gt; CDNIIBLIFII = 1;</code>
       */
      @java.lang.Override

      public emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo getCDNIIBLIFIIOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo> map =
            internalGetCDNIIBLIFII().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearCDNIIBLIFII() {
        internalGetMutableCDNIIBLIFII().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;uint32, .RoguelikeSettleCoinInfo&gt; CDNIIBLIFII = 1;</code>
       */

      public Builder removeCDNIIBLIFII(
          int key) {
        
        internalGetMutableCDNIIBLIFII().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo>
      getMutableCDNIIBLIFII() {
        return internalGetMutableCDNIIBLIFII().getMutableMap();
      }
      /**
       * <code>map&lt;uint32, .RoguelikeSettleCoinInfo&gt; CDNIIBLIFII = 1;</code>
       */
      public Builder putCDNIIBLIFII(
          int key,
          emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableCDNIIBLIFII().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;uint32, .RoguelikeSettleCoinInfo&gt; CDNIIBLIFII = 1;</code>
       */

      public Builder putAllCDNIIBLIFII(
          java.util.Map<java.lang.Integer, emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.RoguelikeSettleCoinInfo> values) {
        internalGetMutableCDNIIBLIFII().getMutableMap()
            .putAll(values);
        return this;
      }

      private int hBINBDBMOED_ ;
      /**
       * <code>uint32 HBINBDBMOED = 2;</code>
       * @return The hBINBDBMOED.
       */
      @java.lang.Override
      public int getHBINBDBMOED() {
        return hBINBDBMOED_;
      }
      /**
       * <code>uint32 HBINBDBMOED = 2;</code>
       * @param value The hBINBDBMOED to set.
       * @return This builder for chaining.
       */
      public Builder setHBINBDBMOED(int value) {
        
        hBINBDBMOED_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 HBINBDBMOED = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHBINBDBMOED() {
        
        hBINBDBMOED_ = 0;
        onChanged();
        return this;
      }

      private boolean pKOELLIPBHP_ ;
      /**
       * <code>bool PKOELLIPBHP = 3;</code>
       * @return The pKOELLIPBHP.
       */
      @java.lang.Override
      public boolean getPKOELLIPBHP() {
        return pKOELLIPBHP_;
      }
      /**
       * <code>bool PKOELLIPBHP = 3;</code>
       * @param value The pKOELLIPBHP to set.
       * @return This builder for chaining.
       */
      public Builder setPKOELLIPBHP(boolean value) {
        
        pKOELLIPBHP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool PKOELLIPBHP = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPKOELLIPBHP() {
        
        pKOELLIPBHP_ = false;
        onChanged();
        return this;
      }

      private int eLHPDAEIMPJ_ ;
      /**
       * <code>uint32 ELHPDAEIMPJ = 4;</code>
       * @return The eLHPDAEIMPJ.
       */
      @java.lang.Override
      public int getELHPDAEIMPJ() {
        return eLHPDAEIMPJ_;
      }
      /**
       * <code>uint32 ELHPDAEIMPJ = 4;</code>
       * @param value The eLHPDAEIMPJ to set.
       * @return This builder for chaining.
       */
      public Builder setELHPDAEIMPJ(int value) {
        
        eLHPDAEIMPJ_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 ELHPDAEIMPJ = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearELHPDAEIMPJ() {
        
        eLHPDAEIMPJ_ = 0;
        onChanged();
        return this;
      }

      private int curLevel_ ;
      /**
       * <code>uint32 cur_level = 6;</code>
       * @return The curLevel.
       */
      @java.lang.Override
      public int getCurLevel() {
        return curLevel_;
      }
      /**
       * <code>uint32 cur_level = 6;</code>
       * @param value The curLevel to set.
       * @return This builder for chaining.
       */
      public Builder setCurLevel(int value) {
        
        curLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 cur_level = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurLevel() {
        
        curLevel_ = 0;
        onChanged();
        return this;
      }

      private int mEMPKCGNNMF_ ;
      /**
       * <code>uint32 MEMPKCGNNMF = 10;</code>
       * @return The mEMPKCGNNMF.
       */
      @java.lang.Override
      public int getMEMPKCGNNMF() {
        return mEMPKCGNNMF_;
      }
      /**
       * <code>uint32 MEMPKCGNNMF = 10;</code>
       * @param value The mEMPKCGNNMF to set.
       * @return This builder for chaining.
       */
      public Builder setMEMPKCGNNMF(int value) {
        
        mEMPKCGNNMF_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 MEMPKCGNNMF = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearMEMPKCGNNMF() {
        
        mEMPKCGNNMF_ = 0;
        onChanged();
        return this;
      }

      private boolean cMFPJHFFHBI_ ;
      /**
       * <code>bool CMFPJHFFHBI = 14;</code>
       * @return The cMFPJHFFHBI.
       */
      @java.lang.Override
      public boolean getCMFPJHFFHBI() {
        return cMFPJHFFHBI_;
      }
      /**
       * <code>bool CMFPJHFFHBI = 14;</code>
       * @param value The cMFPJHFFHBI to set.
       * @return This builder for chaining.
       */
      public Builder setCMFPJHFFHBI(boolean value) {
        
        cMFPJHFFHBI_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool CMFPJHFFHBI = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearCMFPJHFFHBI() {
        
        cMFPJHFFHBI_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RoguelikeDungeonSettleInfo)
    }

    // @@protoc_insertion_point(class_scope:RoguelikeDungeonSettleInfo)
    private static final emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo();
    }

    public static emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoguelikeDungeonSettleInfo>
        PARSER = new com.google.protobuf.AbstractParser<RoguelikeDungeonSettleInfo>() {
      @java.lang.Override
      public RoguelikeDungeonSettleInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoguelikeDungeonSettleInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoguelikeDungeonSettleInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoguelikeDungeonSettleInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public emu.grasscutter.net.proto.RoguelikeDungeonSettleInfoOuterClass.RoguelikeDungeonSettleInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoguelikeDungeonSettleInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoguelikeDungeonSettleInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoguelikeDungeonSettleInfo_CDNIIBLIFIIEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoguelikeDungeonSettleInfo_CDNIIBLIFIIEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n RoguelikeDungeonSettleInfo.proto\032\035Rogu" +
      "elikeSettleCoinInfo.proto\"\251\002\n\032RoguelikeD" +
      "ungeonSettleInfo\022A\n\013CDNIIBLIFII\030\001 \003(\0132,." +
      "RoguelikeDungeonSettleInfo.CDNIIBLIFIIEn" +
      "try\022\023\n\013HBINBDBMOED\030\002 \001(\r\022\023\n\013PKOELLIPBHP\030" +
      "\003 \001(\010\022\023\n\013ELHPDAEIMPJ\030\004 \001(\r\022\021\n\tcur_level\030" +
      "\006 \001(\r\022\023\n\013MEMPKCGNNMF\030\n \001(\r\022\023\n\013CMFPJHFFHB" +
      "I\030\016 \001(\010\032L\n\020CDNIIBLIFIIEntry\022\013\n\003key\030\001 \001(\r" +
      "\022\'\n\005value\030\002 \001(\0132\030.RoguelikeSettleCoinInf" +
      "o:\0028\001B\033\n\031emu.grasscutter.net.protob\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.getDescriptor(),
        });
    internal_static_RoguelikeDungeonSettleInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RoguelikeDungeonSettleInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoguelikeDungeonSettleInfo_descriptor,
        new java.lang.String[] { "CDNIIBLIFII", "HBINBDBMOED", "PKOELLIPBHP", "ELHPDAEIMPJ", "CurLevel", "MEMPKCGNNMF", "CMFPJHFFHBI", });
    internal_static_RoguelikeDungeonSettleInfo_CDNIIBLIFIIEntry_descriptor =
      internal_static_RoguelikeDungeonSettleInfo_descriptor.getNestedTypes().get(0);
    internal_static_RoguelikeDungeonSettleInfo_CDNIIBLIFIIEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoguelikeDungeonSettleInfo_CDNIIBLIFIIEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    emu.grasscutter.net.proto.RoguelikeSettleCoinInfoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
