// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TowerMonthlyCombatRecord.proto

package emu.grasscutter.net.proto;

public final class TowerMonthlyCombatRecordOuterClass {
  private TowerMonthlyCombatRecordOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TowerMonthlyCombatRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TowerMonthlyCombatRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.TowerFightRecordPair MFHLCAPDNMM = 2;</code>
     * @return Whether the mFHLCAPDNMM field is set.
     */
    boolean hasMFHLCAPDNMM();
    /**
     * <code>.TowerFightRecordPair MFHLCAPDNMM = 2;</code>
     * @return The mFHLCAPDNMM.
     */
    emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair getMFHLCAPDNMM();
    /**
     * <code>.TowerFightRecordPair MFHLCAPDNMM = 2;</code>
     */
    emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder getMFHLCAPDNMMOrBuilder();

    /**
     * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
     */
    java.util.List<emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair> 
        getMostRevealAvatarListList();
    /**
     * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
     */
    emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair getMostRevealAvatarList(int index);
    /**
     * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
     */
    int getMostRevealAvatarListCount();
    /**
     * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
     */
    java.util.List<? extends emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder> 
        getMostRevealAvatarListOrBuilderList();
    /**
     * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
     */
    emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder getMostRevealAvatarListOrBuilder(
        int index);

    /**
     * <code>.TowerFightRecordPair GJBDHBDJGED = 8;</code>
     * @return Whether the gJBDHBDJGED field is set.
     */
    boolean hasGJBDHBDJGED();
    /**
     * <code>.TowerFightRecordPair GJBDHBDJGED = 8;</code>
     * @return The gJBDHBDJGED.
     */
    emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair getGJBDHBDJGED();
    /**
     * <code>.TowerFightRecordPair GJBDHBDJGED = 8;</code>
     */
    emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder getGJBDHBDJGEDOrBuilder();

    /**
     * <code>.TowerFightRecordPair DFGIOFHBIBL = 10;</code>
     * @return Whether the dFGIOFHBIBL field is set.
     */
    boolean hasDFGIOFHBIBL();
    /**
     * <code>.TowerFightRecordPair DFGIOFHBIBL = 10;</code>
     * @return The dFGIOFHBIBL.
     */
    emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair getDFGIOFHBIBL();
    /**
     * <code>.TowerFightRecordPair DFGIOFHBIBL = 10;</code>
     */
    emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder getDFGIOFHBIBLOrBuilder();

    /**
     * <code>.TowerFightRecordPair HOPJKPLBDJI = 12;</code>
     * @return Whether the hOPJKPLBDJI field is set.
     */
    boolean hasHOPJKPLBDJI();
    /**
     * <code>.TowerFightRecordPair HOPJKPLBDJI = 12;</code>
     * @return The hOPJKPLBDJI.
     */
    emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair getHOPJKPLBDJI();
    /**
     * <code>.TowerFightRecordPair HOPJKPLBDJI = 12;</code>
     */
    emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder getHOPJKPLBDJIOrBuilder();

    /**
     * <code>.TowerFightRecordPair IPFOLMOJDIE = 15;</code>
     * @return Whether the iPFOLMOJDIE field is set.
     */
    boolean hasIPFOLMOJDIE();
    /**
     * <code>.TowerFightRecordPair IPFOLMOJDIE = 15;</code>
     * @return The iPFOLMOJDIE.
     */
    emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair getIPFOLMOJDIE();
    /**
     * <code>.TowerFightRecordPair IPFOLMOJDIE = 15;</code>
     */
    emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder getIPFOLMOJDIEOrBuilder();
  }
  /**
   * Protobuf type {@code TowerMonthlyCombatRecord}
   */
  public static final class TowerMonthlyCombatRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TowerMonthlyCombatRecord)
      TowerMonthlyCombatRecordOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TowerMonthlyCombatRecord.newBuilder() to construct.
    private TowerMonthlyCombatRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TowerMonthlyCombatRecord() {
      mostRevealAvatarList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TowerMonthlyCombatRecord();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TowerMonthlyCombatRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder subBuilder = null;
              if (mFHLCAPDNMM_ != null) {
                subBuilder = mFHLCAPDNMM_.toBuilder();
              }
              mFHLCAPDNMM_ = input.readMessage(emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(mFHLCAPDNMM_);
                mFHLCAPDNMM_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                mostRevealAvatarList_ = new java.util.ArrayList<emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair>();
                mutable_bitField0_ |= 0x00000001;
              }
              mostRevealAvatarList_.add(
                  input.readMessage(emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.parser(), extensionRegistry));
              break;
            }
            case 66: {
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder subBuilder = null;
              if (gJBDHBDJGED_ != null) {
                subBuilder = gJBDHBDJGED_.toBuilder();
              }
              gJBDHBDJGED_ = input.readMessage(emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(gJBDHBDJGED_);
                gJBDHBDJGED_ = subBuilder.buildPartial();
              }

              break;
            }
            case 82: {
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder subBuilder = null;
              if (dFGIOFHBIBL_ != null) {
                subBuilder = dFGIOFHBIBL_.toBuilder();
              }
              dFGIOFHBIBL_ = input.readMessage(emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dFGIOFHBIBL_);
                dFGIOFHBIBL_ = subBuilder.buildPartial();
              }

              break;
            }
            case 98: {
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder subBuilder = null;
              if (hOPJKPLBDJI_ != null) {
                subBuilder = hOPJKPLBDJI_.toBuilder();
              }
              hOPJKPLBDJI_ = input.readMessage(emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(hOPJKPLBDJI_);
                hOPJKPLBDJI_ = subBuilder.buildPartial();
              }

              break;
            }
            case 122: {
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder subBuilder = null;
              if (iPFOLMOJDIE_ != null) {
                subBuilder = iPFOLMOJDIE_.toBuilder();
              }
              iPFOLMOJDIE_ = input.readMessage(emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(iPFOLMOJDIE_);
                iPFOLMOJDIE_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          mostRevealAvatarList_ = java.util.Collections.unmodifiableList(mostRevealAvatarList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.internal_static_TowerMonthlyCombatRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.internal_static_TowerMonthlyCombatRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord.class, emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord.Builder.class);
    }

    public static final int MFHLCAPDNMM_FIELD_NUMBER = 2;
    private emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair mFHLCAPDNMM_;
    /**
     * <code>.TowerFightRecordPair MFHLCAPDNMM = 2;</code>
     * @return Whether the mFHLCAPDNMM field is set.
     */
    @java.lang.Override
    public boolean hasMFHLCAPDNMM() {
      return mFHLCAPDNMM_ != null;
    }
    /**
     * <code>.TowerFightRecordPair MFHLCAPDNMM = 2;</code>
     * @return The mFHLCAPDNMM.
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair getMFHLCAPDNMM() {
      return mFHLCAPDNMM_ == null ? emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.getDefaultInstance() : mFHLCAPDNMM_;
    }
    /**
     * <code>.TowerFightRecordPair MFHLCAPDNMM = 2;</code>
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder getMFHLCAPDNMMOrBuilder() {
      return getMFHLCAPDNMM();
    }

    public static final int MOST_REVEAL_AVATAR_LIST_FIELD_NUMBER = 4;
    private java.util.List<emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair> mostRevealAvatarList_;
    /**
     * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
     */
    @java.lang.Override
    public java.util.List<emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair> getMostRevealAvatarListList() {
      return mostRevealAvatarList_;
    }
    /**
     * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder> 
        getMostRevealAvatarListOrBuilderList() {
      return mostRevealAvatarList_;
    }
    /**
     * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
     */
    @java.lang.Override
    public int getMostRevealAvatarListCount() {
      return mostRevealAvatarList_.size();
    }
    /**
     * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair getMostRevealAvatarList(int index) {
      return mostRevealAvatarList_.get(index);
    }
    /**
     * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder getMostRevealAvatarListOrBuilder(
        int index) {
      return mostRevealAvatarList_.get(index);
    }

    public static final int GJBDHBDJGED_FIELD_NUMBER = 8;
    private emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair gJBDHBDJGED_;
    /**
     * <code>.TowerFightRecordPair GJBDHBDJGED = 8;</code>
     * @return Whether the gJBDHBDJGED field is set.
     */
    @java.lang.Override
    public boolean hasGJBDHBDJGED() {
      return gJBDHBDJGED_ != null;
    }
    /**
     * <code>.TowerFightRecordPair GJBDHBDJGED = 8;</code>
     * @return The gJBDHBDJGED.
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair getGJBDHBDJGED() {
      return gJBDHBDJGED_ == null ? emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.getDefaultInstance() : gJBDHBDJGED_;
    }
    /**
     * <code>.TowerFightRecordPair GJBDHBDJGED = 8;</code>
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder getGJBDHBDJGEDOrBuilder() {
      return getGJBDHBDJGED();
    }

    public static final int DFGIOFHBIBL_FIELD_NUMBER = 10;
    private emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair dFGIOFHBIBL_;
    /**
     * <code>.TowerFightRecordPair DFGIOFHBIBL = 10;</code>
     * @return Whether the dFGIOFHBIBL field is set.
     */
    @java.lang.Override
    public boolean hasDFGIOFHBIBL() {
      return dFGIOFHBIBL_ != null;
    }
    /**
     * <code>.TowerFightRecordPair DFGIOFHBIBL = 10;</code>
     * @return The dFGIOFHBIBL.
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair getDFGIOFHBIBL() {
      return dFGIOFHBIBL_ == null ? emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.getDefaultInstance() : dFGIOFHBIBL_;
    }
    /**
     * <code>.TowerFightRecordPair DFGIOFHBIBL = 10;</code>
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder getDFGIOFHBIBLOrBuilder() {
      return getDFGIOFHBIBL();
    }

    public static final int HOPJKPLBDJI_FIELD_NUMBER = 12;
    private emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair hOPJKPLBDJI_;
    /**
     * <code>.TowerFightRecordPair HOPJKPLBDJI = 12;</code>
     * @return Whether the hOPJKPLBDJI field is set.
     */
    @java.lang.Override
    public boolean hasHOPJKPLBDJI() {
      return hOPJKPLBDJI_ != null;
    }
    /**
     * <code>.TowerFightRecordPair HOPJKPLBDJI = 12;</code>
     * @return The hOPJKPLBDJI.
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair getHOPJKPLBDJI() {
      return hOPJKPLBDJI_ == null ? emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.getDefaultInstance() : hOPJKPLBDJI_;
    }
    /**
     * <code>.TowerFightRecordPair HOPJKPLBDJI = 12;</code>
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder getHOPJKPLBDJIOrBuilder() {
      return getHOPJKPLBDJI();
    }

    public static final int IPFOLMOJDIE_FIELD_NUMBER = 15;
    private emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair iPFOLMOJDIE_;
    /**
     * <code>.TowerFightRecordPair IPFOLMOJDIE = 15;</code>
     * @return Whether the iPFOLMOJDIE field is set.
     */
    @java.lang.Override
    public boolean hasIPFOLMOJDIE() {
      return iPFOLMOJDIE_ != null;
    }
    /**
     * <code>.TowerFightRecordPair IPFOLMOJDIE = 15;</code>
     * @return The iPFOLMOJDIE.
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair getIPFOLMOJDIE() {
      return iPFOLMOJDIE_ == null ? emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.getDefaultInstance() : iPFOLMOJDIE_;
    }
    /**
     * <code>.TowerFightRecordPair IPFOLMOJDIE = 15;</code>
     */
    @java.lang.Override
    public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder getIPFOLMOJDIEOrBuilder() {
      return getIPFOLMOJDIE();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mFHLCAPDNMM_ != null) {
        output.writeMessage(2, getMFHLCAPDNMM());
      }
      for (int i = 0; i < mostRevealAvatarList_.size(); i++) {
        output.writeMessage(4, mostRevealAvatarList_.get(i));
      }
      if (gJBDHBDJGED_ != null) {
        output.writeMessage(8, getGJBDHBDJGED());
      }
      if (dFGIOFHBIBL_ != null) {
        output.writeMessage(10, getDFGIOFHBIBL());
      }
      if (hOPJKPLBDJI_ != null) {
        output.writeMessage(12, getHOPJKPLBDJI());
      }
      if (iPFOLMOJDIE_ != null) {
        output.writeMessage(15, getIPFOLMOJDIE());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mFHLCAPDNMM_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getMFHLCAPDNMM());
      }
      for (int i = 0; i < mostRevealAvatarList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, mostRevealAvatarList_.get(i));
      }
      if (gJBDHBDJGED_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getGJBDHBDJGED());
      }
      if (dFGIOFHBIBL_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, getDFGIOFHBIBL());
      }
      if (hOPJKPLBDJI_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, getHOPJKPLBDJI());
      }
      if (iPFOLMOJDIE_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(15, getIPFOLMOJDIE());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord)) {
        return super.equals(obj);
      }
      emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord other = (emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord) obj;

      if (hasMFHLCAPDNMM() != other.hasMFHLCAPDNMM()) return false;
      if (hasMFHLCAPDNMM()) {
        if (!getMFHLCAPDNMM()
            .equals(other.getMFHLCAPDNMM())) return false;
      }
      if (!getMostRevealAvatarListList()
          .equals(other.getMostRevealAvatarListList())) return false;
      if (hasGJBDHBDJGED() != other.hasGJBDHBDJGED()) return false;
      if (hasGJBDHBDJGED()) {
        if (!getGJBDHBDJGED()
            .equals(other.getGJBDHBDJGED())) return false;
      }
      if (hasDFGIOFHBIBL() != other.hasDFGIOFHBIBL()) return false;
      if (hasDFGIOFHBIBL()) {
        if (!getDFGIOFHBIBL()
            .equals(other.getDFGIOFHBIBL())) return false;
      }
      if (hasHOPJKPLBDJI() != other.hasHOPJKPLBDJI()) return false;
      if (hasHOPJKPLBDJI()) {
        if (!getHOPJKPLBDJI()
            .equals(other.getHOPJKPLBDJI())) return false;
      }
      if (hasIPFOLMOJDIE() != other.hasIPFOLMOJDIE()) return false;
      if (hasIPFOLMOJDIE()) {
        if (!getIPFOLMOJDIE()
            .equals(other.getIPFOLMOJDIE())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMFHLCAPDNMM()) {
        hash = (37 * hash) + MFHLCAPDNMM_FIELD_NUMBER;
        hash = (53 * hash) + getMFHLCAPDNMM().hashCode();
      }
      if (getMostRevealAvatarListCount() > 0) {
        hash = (37 * hash) + MOST_REVEAL_AVATAR_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getMostRevealAvatarListList().hashCode();
      }
      if (hasGJBDHBDJGED()) {
        hash = (37 * hash) + GJBDHBDJGED_FIELD_NUMBER;
        hash = (53 * hash) + getGJBDHBDJGED().hashCode();
      }
      if (hasDFGIOFHBIBL()) {
        hash = (37 * hash) + DFGIOFHBIBL_FIELD_NUMBER;
        hash = (53 * hash) + getDFGIOFHBIBL().hashCode();
      }
      if (hasHOPJKPLBDJI()) {
        hash = (37 * hash) + HOPJKPLBDJI_FIELD_NUMBER;
        hash = (53 * hash) + getHOPJKPLBDJI().hashCode();
      }
      if (hasIPFOLMOJDIE()) {
        hash = (37 * hash) + IPFOLMOJDIE_FIELD_NUMBER;
        hash = (53 * hash) + getIPFOLMOJDIE().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TowerMonthlyCombatRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TowerMonthlyCombatRecord)
        emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.internal_static_TowerMonthlyCombatRecord_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.internal_static_TowerMonthlyCombatRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord.class, emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord.Builder.class);
      }

      // Construct using emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMostRevealAvatarListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (mFHLCAPDNMMBuilder_ == null) {
          mFHLCAPDNMM_ = null;
        } else {
          mFHLCAPDNMM_ = null;
          mFHLCAPDNMMBuilder_ = null;
        }
        if (mostRevealAvatarListBuilder_ == null) {
          mostRevealAvatarList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          mostRevealAvatarListBuilder_.clear();
        }
        if (gJBDHBDJGEDBuilder_ == null) {
          gJBDHBDJGED_ = null;
        } else {
          gJBDHBDJGED_ = null;
          gJBDHBDJGEDBuilder_ = null;
        }
        if (dFGIOFHBIBLBuilder_ == null) {
          dFGIOFHBIBL_ = null;
        } else {
          dFGIOFHBIBL_ = null;
          dFGIOFHBIBLBuilder_ = null;
        }
        if (hOPJKPLBDJIBuilder_ == null) {
          hOPJKPLBDJI_ = null;
        } else {
          hOPJKPLBDJI_ = null;
          hOPJKPLBDJIBuilder_ = null;
        }
        if (iPFOLMOJDIEBuilder_ == null) {
          iPFOLMOJDIE_ = null;
        } else {
          iPFOLMOJDIE_ = null;
          iPFOLMOJDIEBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.internal_static_TowerMonthlyCombatRecord_descriptor;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord getDefaultInstanceForType() {
        return emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord.getDefaultInstance();
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord build() {
        emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord buildPartial() {
        emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord result = new emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord(this);
        int from_bitField0_ = bitField0_;
        if (mFHLCAPDNMMBuilder_ == null) {
          result.mFHLCAPDNMM_ = mFHLCAPDNMM_;
        } else {
          result.mFHLCAPDNMM_ = mFHLCAPDNMMBuilder_.build();
        }
        if (mostRevealAvatarListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            mostRevealAvatarList_ = java.util.Collections.unmodifiableList(mostRevealAvatarList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.mostRevealAvatarList_ = mostRevealAvatarList_;
        } else {
          result.mostRevealAvatarList_ = mostRevealAvatarListBuilder_.build();
        }
        if (gJBDHBDJGEDBuilder_ == null) {
          result.gJBDHBDJGED_ = gJBDHBDJGED_;
        } else {
          result.gJBDHBDJGED_ = gJBDHBDJGEDBuilder_.build();
        }
        if (dFGIOFHBIBLBuilder_ == null) {
          result.dFGIOFHBIBL_ = dFGIOFHBIBL_;
        } else {
          result.dFGIOFHBIBL_ = dFGIOFHBIBLBuilder_.build();
        }
        if (hOPJKPLBDJIBuilder_ == null) {
          result.hOPJKPLBDJI_ = hOPJKPLBDJI_;
        } else {
          result.hOPJKPLBDJI_ = hOPJKPLBDJIBuilder_.build();
        }
        if (iPFOLMOJDIEBuilder_ == null) {
          result.iPFOLMOJDIE_ = iPFOLMOJDIE_;
        } else {
          result.iPFOLMOJDIE_ = iPFOLMOJDIEBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord) {
          return mergeFrom((emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord other) {
        if (other == emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord.getDefaultInstance()) return this;
        if (other.hasMFHLCAPDNMM()) {
          mergeMFHLCAPDNMM(other.getMFHLCAPDNMM());
        }
        if (mostRevealAvatarListBuilder_ == null) {
          if (!other.mostRevealAvatarList_.isEmpty()) {
            if (mostRevealAvatarList_.isEmpty()) {
              mostRevealAvatarList_ = other.mostRevealAvatarList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMostRevealAvatarListIsMutable();
              mostRevealAvatarList_.addAll(other.mostRevealAvatarList_);
            }
            onChanged();
          }
        } else {
          if (!other.mostRevealAvatarList_.isEmpty()) {
            if (mostRevealAvatarListBuilder_.isEmpty()) {
              mostRevealAvatarListBuilder_.dispose();
              mostRevealAvatarListBuilder_ = null;
              mostRevealAvatarList_ = other.mostRevealAvatarList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              mostRevealAvatarListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMostRevealAvatarListFieldBuilder() : null;
            } else {
              mostRevealAvatarListBuilder_.addAllMessages(other.mostRevealAvatarList_);
            }
          }
        }
        if (other.hasGJBDHBDJGED()) {
          mergeGJBDHBDJGED(other.getGJBDHBDJGED());
        }
        if (other.hasDFGIOFHBIBL()) {
          mergeDFGIOFHBIBL(other.getDFGIOFHBIBL());
        }
        if (other.hasHOPJKPLBDJI()) {
          mergeHOPJKPLBDJI(other.getHOPJKPLBDJI());
        }
        if (other.hasIPFOLMOJDIE()) {
          mergeIPFOLMOJDIE(other.getIPFOLMOJDIE());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair mFHLCAPDNMM_;
      private com.google.protobuf.SingleFieldBuilderV3<
          emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder> mFHLCAPDNMMBuilder_;
      /**
       * <code>.TowerFightRecordPair MFHLCAPDNMM = 2;</code>
       * @return Whether the mFHLCAPDNMM field is set.
       */
      public boolean hasMFHLCAPDNMM() {
        return mFHLCAPDNMMBuilder_ != null || mFHLCAPDNMM_ != null;
      }
      /**
       * <code>.TowerFightRecordPair MFHLCAPDNMM = 2;</code>
       * @return The mFHLCAPDNMM.
       */
      public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair getMFHLCAPDNMM() {
        if (mFHLCAPDNMMBuilder_ == null) {
          return mFHLCAPDNMM_ == null ? emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.getDefaultInstance() : mFHLCAPDNMM_;
        } else {
          return mFHLCAPDNMMBuilder_.getMessage();
        }
      }
      /**
       * <code>.TowerFightRecordPair MFHLCAPDNMM = 2;</code>
       */
      public Builder setMFHLCAPDNMM(emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair value) {
        if (mFHLCAPDNMMBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mFHLCAPDNMM_ = value;
          onChanged();
        } else {
          mFHLCAPDNMMBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.TowerFightRecordPair MFHLCAPDNMM = 2;</code>
       */
      public Builder setMFHLCAPDNMM(
          emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder builderForValue) {
        if (mFHLCAPDNMMBuilder_ == null) {
          mFHLCAPDNMM_ = builderForValue.build();
          onChanged();
        } else {
          mFHLCAPDNMMBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.TowerFightRecordPair MFHLCAPDNMM = 2;</code>
       */
      public Builder mergeMFHLCAPDNMM(emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair value) {
        if (mFHLCAPDNMMBuilder_ == null) {
          if (mFHLCAPDNMM_ != null) {
            mFHLCAPDNMM_ =
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.newBuilder(mFHLCAPDNMM_).mergeFrom(value).buildPartial();
          } else {
            mFHLCAPDNMM_ = value;
          }
          onChanged();
        } else {
          mFHLCAPDNMMBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.TowerFightRecordPair MFHLCAPDNMM = 2;</code>
       */
      public Builder clearMFHLCAPDNMM() {
        if (mFHLCAPDNMMBuilder_ == null) {
          mFHLCAPDNMM_ = null;
          onChanged();
        } else {
          mFHLCAPDNMM_ = null;
          mFHLCAPDNMMBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.TowerFightRecordPair MFHLCAPDNMM = 2;</code>
       */
      public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder getMFHLCAPDNMMBuilder() {
        
        onChanged();
        return getMFHLCAPDNMMFieldBuilder().getBuilder();
      }
      /**
       * <code>.TowerFightRecordPair MFHLCAPDNMM = 2;</code>
       */
      public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder getMFHLCAPDNMMOrBuilder() {
        if (mFHLCAPDNMMBuilder_ != null) {
          return mFHLCAPDNMMBuilder_.getMessageOrBuilder();
        } else {
          return mFHLCAPDNMM_ == null ?
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.getDefaultInstance() : mFHLCAPDNMM_;
        }
      }
      /**
       * <code>.TowerFightRecordPair MFHLCAPDNMM = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder> 
          getMFHLCAPDNMMFieldBuilder() {
        if (mFHLCAPDNMMBuilder_ == null) {
          mFHLCAPDNMMBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder>(
                  getMFHLCAPDNMM(),
                  getParentForChildren(),
                  isClean());
          mFHLCAPDNMM_ = null;
        }
        return mFHLCAPDNMMBuilder_;
      }

      private java.util.List<emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair> mostRevealAvatarList_ =
        java.util.Collections.emptyList();
      private void ensureMostRevealAvatarListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          mostRevealAvatarList_ = new java.util.ArrayList<emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair>(mostRevealAvatarList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder> mostRevealAvatarListBuilder_;

      /**
       * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
       */
      public java.util.List<emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair> getMostRevealAvatarListList() {
        if (mostRevealAvatarListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(mostRevealAvatarList_);
        } else {
          return mostRevealAvatarListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
       */
      public int getMostRevealAvatarListCount() {
        if (mostRevealAvatarListBuilder_ == null) {
          return mostRevealAvatarList_.size();
        } else {
          return mostRevealAvatarListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
       */
      public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair getMostRevealAvatarList(int index) {
        if (mostRevealAvatarListBuilder_ == null) {
          return mostRevealAvatarList_.get(index);
        } else {
          return mostRevealAvatarListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
       */
      public Builder setMostRevealAvatarList(
          int index, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair value) {
        if (mostRevealAvatarListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMostRevealAvatarListIsMutable();
          mostRevealAvatarList_.set(index, value);
          onChanged();
        } else {
          mostRevealAvatarListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
       */
      public Builder setMostRevealAvatarList(
          int index, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder builderForValue) {
        if (mostRevealAvatarListBuilder_ == null) {
          ensureMostRevealAvatarListIsMutable();
          mostRevealAvatarList_.set(index, builderForValue.build());
          onChanged();
        } else {
          mostRevealAvatarListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
       */
      public Builder addMostRevealAvatarList(emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair value) {
        if (mostRevealAvatarListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMostRevealAvatarListIsMutable();
          mostRevealAvatarList_.add(value);
          onChanged();
        } else {
          mostRevealAvatarListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
       */
      public Builder addMostRevealAvatarList(
          int index, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair value) {
        if (mostRevealAvatarListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMostRevealAvatarListIsMutable();
          mostRevealAvatarList_.add(index, value);
          onChanged();
        } else {
          mostRevealAvatarListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
       */
      public Builder addMostRevealAvatarList(
          emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder builderForValue) {
        if (mostRevealAvatarListBuilder_ == null) {
          ensureMostRevealAvatarListIsMutable();
          mostRevealAvatarList_.add(builderForValue.build());
          onChanged();
        } else {
          mostRevealAvatarListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
       */
      public Builder addMostRevealAvatarList(
          int index, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder builderForValue) {
        if (mostRevealAvatarListBuilder_ == null) {
          ensureMostRevealAvatarListIsMutable();
          mostRevealAvatarList_.add(index, builderForValue.build());
          onChanged();
        } else {
          mostRevealAvatarListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
       */
      public Builder addAllMostRevealAvatarList(
          java.lang.Iterable<? extends emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair> values) {
        if (mostRevealAvatarListBuilder_ == null) {
          ensureMostRevealAvatarListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, mostRevealAvatarList_);
          onChanged();
        } else {
          mostRevealAvatarListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
       */
      public Builder clearMostRevealAvatarList() {
        if (mostRevealAvatarListBuilder_ == null) {
          mostRevealAvatarList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          mostRevealAvatarListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
       */
      public Builder removeMostRevealAvatarList(int index) {
        if (mostRevealAvatarListBuilder_ == null) {
          ensureMostRevealAvatarListIsMutable();
          mostRevealAvatarList_.remove(index);
          onChanged();
        } else {
          mostRevealAvatarListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
       */
      public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder getMostRevealAvatarListBuilder(
          int index) {
        return getMostRevealAvatarListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
       */
      public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder getMostRevealAvatarListOrBuilder(
          int index) {
        if (mostRevealAvatarListBuilder_ == null) {
          return mostRevealAvatarList_.get(index);  } else {
          return mostRevealAvatarListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
       */
      public java.util.List<? extends emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder> 
           getMostRevealAvatarListOrBuilderList() {
        if (mostRevealAvatarListBuilder_ != null) {
          return mostRevealAvatarListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(mostRevealAvatarList_);
        }
      }
      /**
       * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
       */
      public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder addMostRevealAvatarListBuilder() {
        return getMostRevealAvatarListFieldBuilder().addBuilder(
            emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.getDefaultInstance());
      }
      /**
       * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
       */
      public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder addMostRevealAvatarListBuilder(
          int index) {
        return getMostRevealAvatarListFieldBuilder().addBuilder(
            index, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.getDefaultInstance());
      }
      /**
       * <code>repeated .TowerFightRecordPair most_reveal_avatar_list = 4;</code>
       */
      public java.util.List<emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder> 
           getMostRevealAvatarListBuilderList() {
        return getMostRevealAvatarListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder> 
          getMostRevealAvatarListFieldBuilder() {
        if (mostRevealAvatarListBuilder_ == null) {
          mostRevealAvatarListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder>(
                  mostRevealAvatarList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          mostRevealAvatarList_ = null;
        }
        return mostRevealAvatarListBuilder_;
      }

      private emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair gJBDHBDJGED_;
      private com.google.protobuf.SingleFieldBuilderV3<
          emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder> gJBDHBDJGEDBuilder_;
      /**
       * <code>.TowerFightRecordPair GJBDHBDJGED = 8;</code>
       * @return Whether the gJBDHBDJGED field is set.
       */
      public boolean hasGJBDHBDJGED() {
        return gJBDHBDJGEDBuilder_ != null || gJBDHBDJGED_ != null;
      }
      /**
       * <code>.TowerFightRecordPair GJBDHBDJGED = 8;</code>
       * @return The gJBDHBDJGED.
       */
      public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair getGJBDHBDJGED() {
        if (gJBDHBDJGEDBuilder_ == null) {
          return gJBDHBDJGED_ == null ? emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.getDefaultInstance() : gJBDHBDJGED_;
        } else {
          return gJBDHBDJGEDBuilder_.getMessage();
        }
      }
      /**
       * <code>.TowerFightRecordPair GJBDHBDJGED = 8;</code>
       */
      public Builder setGJBDHBDJGED(emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair value) {
        if (gJBDHBDJGEDBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          gJBDHBDJGED_ = value;
          onChanged();
        } else {
          gJBDHBDJGEDBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.TowerFightRecordPair GJBDHBDJGED = 8;</code>
       */
      public Builder setGJBDHBDJGED(
          emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder builderForValue) {
        if (gJBDHBDJGEDBuilder_ == null) {
          gJBDHBDJGED_ = builderForValue.build();
          onChanged();
        } else {
          gJBDHBDJGEDBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.TowerFightRecordPair GJBDHBDJGED = 8;</code>
       */
      public Builder mergeGJBDHBDJGED(emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair value) {
        if (gJBDHBDJGEDBuilder_ == null) {
          if (gJBDHBDJGED_ != null) {
            gJBDHBDJGED_ =
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.newBuilder(gJBDHBDJGED_).mergeFrom(value).buildPartial();
          } else {
            gJBDHBDJGED_ = value;
          }
          onChanged();
        } else {
          gJBDHBDJGEDBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.TowerFightRecordPair GJBDHBDJGED = 8;</code>
       */
      public Builder clearGJBDHBDJGED() {
        if (gJBDHBDJGEDBuilder_ == null) {
          gJBDHBDJGED_ = null;
          onChanged();
        } else {
          gJBDHBDJGED_ = null;
          gJBDHBDJGEDBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.TowerFightRecordPair GJBDHBDJGED = 8;</code>
       */
      public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder getGJBDHBDJGEDBuilder() {
        
        onChanged();
        return getGJBDHBDJGEDFieldBuilder().getBuilder();
      }
      /**
       * <code>.TowerFightRecordPair GJBDHBDJGED = 8;</code>
       */
      public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder getGJBDHBDJGEDOrBuilder() {
        if (gJBDHBDJGEDBuilder_ != null) {
          return gJBDHBDJGEDBuilder_.getMessageOrBuilder();
        } else {
          return gJBDHBDJGED_ == null ?
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.getDefaultInstance() : gJBDHBDJGED_;
        }
      }
      /**
       * <code>.TowerFightRecordPair GJBDHBDJGED = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder> 
          getGJBDHBDJGEDFieldBuilder() {
        if (gJBDHBDJGEDBuilder_ == null) {
          gJBDHBDJGEDBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder>(
                  getGJBDHBDJGED(),
                  getParentForChildren(),
                  isClean());
          gJBDHBDJGED_ = null;
        }
        return gJBDHBDJGEDBuilder_;
      }

      private emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair dFGIOFHBIBL_;
      private com.google.protobuf.SingleFieldBuilderV3<
          emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder> dFGIOFHBIBLBuilder_;
      /**
       * <code>.TowerFightRecordPair DFGIOFHBIBL = 10;</code>
       * @return Whether the dFGIOFHBIBL field is set.
       */
      public boolean hasDFGIOFHBIBL() {
        return dFGIOFHBIBLBuilder_ != null || dFGIOFHBIBL_ != null;
      }
      /**
       * <code>.TowerFightRecordPair DFGIOFHBIBL = 10;</code>
       * @return The dFGIOFHBIBL.
       */
      public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair getDFGIOFHBIBL() {
        if (dFGIOFHBIBLBuilder_ == null) {
          return dFGIOFHBIBL_ == null ? emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.getDefaultInstance() : dFGIOFHBIBL_;
        } else {
          return dFGIOFHBIBLBuilder_.getMessage();
        }
      }
      /**
       * <code>.TowerFightRecordPair DFGIOFHBIBL = 10;</code>
       */
      public Builder setDFGIOFHBIBL(emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair value) {
        if (dFGIOFHBIBLBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dFGIOFHBIBL_ = value;
          onChanged();
        } else {
          dFGIOFHBIBLBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.TowerFightRecordPair DFGIOFHBIBL = 10;</code>
       */
      public Builder setDFGIOFHBIBL(
          emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder builderForValue) {
        if (dFGIOFHBIBLBuilder_ == null) {
          dFGIOFHBIBL_ = builderForValue.build();
          onChanged();
        } else {
          dFGIOFHBIBLBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.TowerFightRecordPair DFGIOFHBIBL = 10;</code>
       */
      public Builder mergeDFGIOFHBIBL(emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair value) {
        if (dFGIOFHBIBLBuilder_ == null) {
          if (dFGIOFHBIBL_ != null) {
            dFGIOFHBIBL_ =
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.newBuilder(dFGIOFHBIBL_).mergeFrom(value).buildPartial();
          } else {
            dFGIOFHBIBL_ = value;
          }
          onChanged();
        } else {
          dFGIOFHBIBLBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.TowerFightRecordPair DFGIOFHBIBL = 10;</code>
       */
      public Builder clearDFGIOFHBIBL() {
        if (dFGIOFHBIBLBuilder_ == null) {
          dFGIOFHBIBL_ = null;
          onChanged();
        } else {
          dFGIOFHBIBL_ = null;
          dFGIOFHBIBLBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.TowerFightRecordPair DFGIOFHBIBL = 10;</code>
       */
      public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder getDFGIOFHBIBLBuilder() {
        
        onChanged();
        return getDFGIOFHBIBLFieldBuilder().getBuilder();
      }
      /**
       * <code>.TowerFightRecordPair DFGIOFHBIBL = 10;</code>
       */
      public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder getDFGIOFHBIBLOrBuilder() {
        if (dFGIOFHBIBLBuilder_ != null) {
          return dFGIOFHBIBLBuilder_.getMessageOrBuilder();
        } else {
          return dFGIOFHBIBL_ == null ?
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.getDefaultInstance() : dFGIOFHBIBL_;
        }
      }
      /**
       * <code>.TowerFightRecordPair DFGIOFHBIBL = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder> 
          getDFGIOFHBIBLFieldBuilder() {
        if (dFGIOFHBIBLBuilder_ == null) {
          dFGIOFHBIBLBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder>(
                  getDFGIOFHBIBL(),
                  getParentForChildren(),
                  isClean());
          dFGIOFHBIBL_ = null;
        }
        return dFGIOFHBIBLBuilder_;
      }

      private emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair hOPJKPLBDJI_;
      private com.google.protobuf.SingleFieldBuilderV3<
          emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder> hOPJKPLBDJIBuilder_;
      /**
       * <code>.TowerFightRecordPair HOPJKPLBDJI = 12;</code>
       * @return Whether the hOPJKPLBDJI field is set.
       */
      public boolean hasHOPJKPLBDJI() {
        return hOPJKPLBDJIBuilder_ != null || hOPJKPLBDJI_ != null;
      }
      /**
       * <code>.TowerFightRecordPair HOPJKPLBDJI = 12;</code>
       * @return The hOPJKPLBDJI.
       */
      public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair getHOPJKPLBDJI() {
        if (hOPJKPLBDJIBuilder_ == null) {
          return hOPJKPLBDJI_ == null ? emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.getDefaultInstance() : hOPJKPLBDJI_;
        } else {
          return hOPJKPLBDJIBuilder_.getMessage();
        }
      }
      /**
       * <code>.TowerFightRecordPair HOPJKPLBDJI = 12;</code>
       */
      public Builder setHOPJKPLBDJI(emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair value) {
        if (hOPJKPLBDJIBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          hOPJKPLBDJI_ = value;
          onChanged();
        } else {
          hOPJKPLBDJIBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.TowerFightRecordPair HOPJKPLBDJI = 12;</code>
       */
      public Builder setHOPJKPLBDJI(
          emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder builderForValue) {
        if (hOPJKPLBDJIBuilder_ == null) {
          hOPJKPLBDJI_ = builderForValue.build();
          onChanged();
        } else {
          hOPJKPLBDJIBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.TowerFightRecordPair HOPJKPLBDJI = 12;</code>
       */
      public Builder mergeHOPJKPLBDJI(emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair value) {
        if (hOPJKPLBDJIBuilder_ == null) {
          if (hOPJKPLBDJI_ != null) {
            hOPJKPLBDJI_ =
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.newBuilder(hOPJKPLBDJI_).mergeFrom(value).buildPartial();
          } else {
            hOPJKPLBDJI_ = value;
          }
          onChanged();
        } else {
          hOPJKPLBDJIBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.TowerFightRecordPair HOPJKPLBDJI = 12;</code>
       */
      public Builder clearHOPJKPLBDJI() {
        if (hOPJKPLBDJIBuilder_ == null) {
          hOPJKPLBDJI_ = null;
          onChanged();
        } else {
          hOPJKPLBDJI_ = null;
          hOPJKPLBDJIBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.TowerFightRecordPair HOPJKPLBDJI = 12;</code>
       */
      public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder getHOPJKPLBDJIBuilder() {
        
        onChanged();
        return getHOPJKPLBDJIFieldBuilder().getBuilder();
      }
      /**
       * <code>.TowerFightRecordPair HOPJKPLBDJI = 12;</code>
       */
      public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder getHOPJKPLBDJIOrBuilder() {
        if (hOPJKPLBDJIBuilder_ != null) {
          return hOPJKPLBDJIBuilder_.getMessageOrBuilder();
        } else {
          return hOPJKPLBDJI_ == null ?
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.getDefaultInstance() : hOPJKPLBDJI_;
        }
      }
      /**
       * <code>.TowerFightRecordPair HOPJKPLBDJI = 12;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder> 
          getHOPJKPLBDJIFieldBuilder() {
        if (hOPJKPLBDJIBuilder_ == null) {
          hOPJKPLBDJIBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder>(
                  getHOPJKPLBDJI(),
                  getParentForChildren(),
                  isClean());
          hOPJKPLBDJI_ = null;
        }
        return hOPJKPLBDJIBuilder_;
      }

      private emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair iPFOLMOJDIE_;
      private com.google.protobuf.SingleFieldBuilderV3<
          emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder> iPFOLMOJDIEBuilder_;
      /**
       * <code>.TowerFightRecordPair IPFOLMOJDIE = 15;</code>
       * @return Whether the iPFOLMOJDIE field is set.
       */
      public boolean hasIPFOLMOJDIE() {
        return iPFOLMOJDIEBuilder_ != null || iPFOLMOJDIE_ != null;
      }
      /**
       * <code>.TowerFightRecordPair IPFOLMOJDIE = 15;</code>
       * @return The iPFOLMOJDIE.
       */
      public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair getIPFOLMOJDIE() {
        if (iPFOLMOJDIEBuilder_ == null) {
          return iPFOLMOJDIE_ == null ? emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.getDefaultInstance() : iPFOLMOJDIE_;
        } else {
          return iPFOLMOJDIEBuilder_.getMessage();
        }
      }
      /**
       * <code>.TowerFightRecordPair IPFOLMOJDIE = 15;</code>
       */
      public Builder setIPFOLMOJDIE(emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair value) {
        if (iPFOLMOJDIEBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          iPFOLMOJDIE_ = value;
          onChanged();
        } else {
          iPFOLMOJDIEBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.TowerFightRecordPair IPFOLMOJDIE = 15;</code>
       */
      public Builder setIPFOLMOJDIE(
          emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder builderForValue) {
        if (iPFOLMOJDIEBuilder_ == null) {
          iPFOLMOJDIE_ = builderForValue.build();
          onChanged();
        } else {
          iPFOLMOJDIEBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.TowerFightRecordPair IPFOLMOJDIE = 15;</code>
       */
      public Builder mergeIPFOLMOJDIE(emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair value) {
        if (iPFOLMOJDIEBuilder_ == null) {
          if (iPFOLMOJDIE_ != null) {
            iPFOLMOJDIE_ =
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.newBuilder(iPFOLMOJDIE_).mergeFrom(value).buildPartial();
          } else {
            iPFOLMOJDIE_ = value;
          }
          onChanged();
        } else {
          iPFOLMOJDIEBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.TowerFightRecordPair IPFOLMOJDIE = 15;</code>
       */
      public Builder clearIPFOLMOJDIE() {
        if (iPFOLMOJDIEBuilder_ == null) {
          iPFOLMOJDIE_ = null;
          onChanged();
        } else {
          iPFOLMOJDIE_ = null;
          iPFOLMOJDIEBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.TowerFightRecordPair IPFOLMOJDIE = 15;</code>
       */
      public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder getIPFOLMOJDIEBuilder() {
        
        onChanged();
        return getIPFOLMOJDIEFieldBuilder().getBuilder();
      }
      /**
       * <code>.TowerFightRecordPair IPFOLMOJDIE = 15;</code>
       */
      public emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder getIPFOLMOJDIEOrBuilder() {
        if (iPFOLMOJDIEBuilder_ != null) {
          return iPFOLMOJDIEBuilder_.getMessageOrBuilder();
        } else {
          return iPFOLMOJDIE_ == null ?
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.getDefaultInstance() : iPFOLMOJDIE_;
        }
      }
      /**
       * <code>.TowerFightRecordPair IPFOLMOJDIE = 15;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder> 
          getIPFOLMOJDIEFieldBuilder() {
        if (iPFOLMOJDIEBuilder_ == null) {
          iPFOLMOJDIEBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPair.Builder, emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.TowerFightRecordPairOrBuilder>(
                  getIPFOLMOJDIE(),
                  getParentForChildren(),
                  isClean());
          iPFOLMOJDIE_ = null;
        }
        return iPFOLMOJDIEBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TowerMonthlyCombatRecord)
    }

    // @@protoc_insertion_point(class_scope:TowerMonthlyCombatRecord)
    private static final emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord();
    }

    public static emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TowerMonthlyCombatRecord>
        PARSER = new com.google.protobuf.AbstractParser<TowerMonthlyCombatRecord>() {
      @java.lang.Override
      public TowerMonthlyCombatRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TowerMonthlyCombatRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TowerMonthlyCombatRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TowerMonthlyCombatRecord> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public emu.grasscutter.net.proto.TowerMonthlyCombatRecordOuterClass.TowerMonthlyCombatRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TowerMonthlyCombatRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TowerMonthlyCombatRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036TowerMonthlyCombatRecord.proto\032\032TowerF" +
      "ightRecordPair.proto\"\256\002\n\030TowerMonthlyCom" +
      "batRecord\022*\n\013MFHLCAPDNMM\030\002 \001(\0132\025.TowerFi" +
      "ghtRecordPair\0226\n\027most_reveal_avatar_list" +
      "\030\004 \003(\0132\025.TowerFightRecordPair\022*\n\013GJBDHBD" +
      "JGED\030\010 \001(\0132\025.TowerFightRecordPair\022*\n\013DFG" +
      "IOFHBIBL\030\n \001(\0132\025.TowerFightRecordPair\022*\n" +
      "\013HOPJKPLBDJI\030\014 \001(\0132\025.TowerFightRecordPai" +
      "r\022*\n\013IPFOLMOJDIE\030\017 \001(\0132\025.TowerFightRecor" +
      "dPairB\033\n\031emu.grasscutter.net.protob\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.getDescriptor(),
        });
    internal_static_TowerMonthlyCombatRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TowerMonthlyCombatRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TowerMonthlyCombatRecord_descriptor,
        new java.lang.String[] { "MFHLCAPDNMM", "MostRevealAvatarList", "GJBDHBDJGED", "DFGIOFHBIBL", "HOPJKPLBDJI", "IPFOLMOJDIE", });
    emu.grasscutter.net.proto.TowerFightRecordPairOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
